universe = vanilla
Executable = /home/jlee/CMS/ChargedHiggs/CMSSW_7_2_4/src/TMVA/test//doCondorKinematics.sh
Should_Transfer_Files = YES
transfer_input_files = /home/jlee/CMS/ChargedHiggs/CMSSW_7_2_4/src/TMVA/test//doHists.py,/home/jlee/CMS/ChargedHiggs/CMSSW_7_2_4/src/TMVA/test//samples.py,/home/jlee/CMS/ChargedHiggs/CMSSW_7_2_4/src/TMVA/test//weights.py,/home/jlee/CMS/ChargedHiggs/CMSSW_7_2_4/src/TMVA/test//analyze.py
WhenToTransferOutput = ON_EXIT
notify_user = jmhogan@fnal.gov

arguments      = ""

Output = condor_lepPt.out
Error = condor_lepPt.err
Log = condor_lepPt.log
Notification = Error
Arguments = /home/jlee/CMS/ChargedHiggs/CMSSW_7_2_4/src/TMVA/test/ lepPt E

Queue 1