// Class: ReadBDT
// Automatically generated by MethodBase::MakeClass
//

/* configuration options =====================================================

#GEN -*-*-*-*-*-*-*-*-*-*-*- general info -*-*-*-*-*-*-*-*-*-*-*-

Method         : BDT::BDT
TMVA Release   : 4.2.0         [262656]
ROOT Release   : 5.34/18       [336402]
Creator        : jlee
Date           : Mon Nov 21 15:32:19 2016
Host           : Linux cmsdev02.cern.ch 2.6.32-431.23.3.el6.x86_64 #1 SMP Wed Jul 30 09:43:11 CEST 2014 x86_64 x86_64 x86_64 GNU/Linux
Dir            : /home/jlee/CMS/ChargedHiggs/CMSSW_7_2_4/src/TMVA/test
Training events: 824828
Analysis type  : [Classification]


#OPT -*-*-*-*-*-*-*-*-*-*-*-*- options -*-*-*-*-*-*-*-*-*-*-*-*-

# Set by User:
V: "False" [Verbose output (short form of "VerbosityLevel" below - overrides the latter one)]
H: "False" [Print method-specific help message]
NTrees: "150" [Number of trees in the forest]
MaxDepth: "3" [Max depth of the decision tree allowed]
MinNodeSize: "2.5%" [Minimum percentage of training events required in a leaf node (default: Classification: 5%, Regression: 0.2%)]
nCuts: "50" [Number of grid points in variable range used in finding optimal cut in node splitting]
BoostType: "AdaBoost" [Boosting type for the trees in the forest (note: AdaCost is still experimental)]
UseBaggedBoost: "True" [Use only a random subsample of all events for growing the trees in each boost iteration.]
AdaBoostBeta: "5.000000e-01" [Learning rate  for AdaBoost algorithm]
BaggedSampleFraction: "5.000000e-01" [Relative size of bagged event sample to original size of the data sample (used whenever bagging is used (i.e. UseBaggedBoost, Bagging,)]
SeparationType: "giniindex" [Separation criterion for node splitting]
# Default:
VerbosityLevel: "Default" [Verbosity level]
VarTransform: "None" [List of variable transformations performed before training, e.g., "D_Background,P_Signal,G,N_AllClasses" for: "Decorrelation, PCA-transformation, Gaussianisation, Normalisation, each for the given class of events ('AllClasses' denotes all events of all classes, if no class indication is given, 'All' is assumed)"]
CreateMVAPdfs: "False" [Create PDFs for classifier outputs (signal and background)]
IgnoreNegWeightsInTraining: "False" [Events with negative weights are ignored in the training (but are included for testing and performance evaluation)]
AdaBoostR2Loss: "quadratic" [Type of Loss function in AdaBoostR2]
Shrinkage: "1.000000e+00" [Learning rate for GradBoost algorithm]
UseRandomisedTrees: "False" [Determine at each node splitting the cut variable only as the best out of a random subset of variables (like in RandomForests)]
UseNvars: "4" [Size of the subset of variables used with RandomisedTree option]
UsePoissonNvars: "True" [Interpret "UseNvars" not as fixed number but as mean of a Possion distribution in each split with RandomisedTree option]
UseYesNoLeaf: "True" [Use Sig or Bkg categories, or the purity=S/(S+B) as classification of the leaf node -> Real-AdaBoost]
NegWeightTreatment: "inverseboostnegweights" [How to treat events with negative weights in the BDT training (particular the boosting) : IgnoreInTraining;  Boost With inverse boostweight; Pair events with negative and positive weights in traning sample and *annihilate* them (experimental!)]
Css: "1.000000e+00" [AdaCost: cost of true signal selected signal]
Cts_sb: "1.000000e+00" [AdaCost: cost of true signal selected bkg]
Ctb_ss: "1.000000e+00" [AdaCost: cost of true bkg    selected signal]
Cbb: "1.000000e+00" [AdaCost: cost of true bkg    selected bkg ]
NodePurityLimit: "5.000000e-01" [In boosting/pruning, nodes with purity > NodePurityLimit are signal; background otherwise.]
DoBoostMonitor: "False" [Create control plot with ROC integral vs tree number]
UseFisherCuts: "False" [Use multivariate splits using the Fisher criterion]
MinLinCorrForFisher: "8.000000e-01" [The minimum linear correlation between two variables demanded for use in Fisher criterion in node splitting]
UseExclusiveVars: "False" [Variables already used in fisher criterion are not anymore analysed individually for node splitting]
DoPreselection: "False" [and and apply automatic pre-selection for 100% efficient signal (bkg) cuts prior to training]
SigToBkgFraction: "1.000000e+00" [Sig to Bkg ratio used in Training (similar to NodePurityLimit, which cannot be used in real adaboost]
PruneMethod: "nopruning" [Note: for BDTs use small trees (e.g.MaxDepth=3) and NoPruning:  Pruning: Method used for pruning (removal) of statistically insignificant branches ]
PruneStrength: "0.000000e+00" [Pruning strength]
PruningValFraction: "5.000000e-01" [Fraction of events to use for optimizing automatic pruning.]
nEventsMin: "0" [deprecated: Use MinNodeSize (in % of training events) instead]
UseBaggedGrad: "False" [deprecated: Use *UseBaggedBoost* instead:  Use only a random subsample of all events for growing the trees in each iteration.]
GradBaggingFraction: "5.000000e-01" [deprecated: Use *BaggedSampleFraction* instead: Defines the fraction of events to be used in each iteration, e.g. when UseBaggedGrad=kTRUE. ]
UseNTrainEvents: "0" [deprecated: Use *BaggedSampleFraction* instead: Number of randomly picked training events used in randomised (and bagged) trees]
NNodesMax: "0" [deprecated: Use MaxDepth instead to limit the tree size]
##


#VAR -*-*-*-*-*-*-*-*-*-*-*-* variables *-*-*-*-*-*-*-*-*-*-*-*-

NVar 17
mass_minBBdr                  mass_minBBdr                  mass_minBBdr                  mass_minBBdr                                                    'F'    [13.898809433,2138.31689453]
mass_minLLdr                  mass_minLLdr                  mass_minLLdr                  mass_minLLdr                                                    'F'    [0,3297.81518555]
lepDR_minBBdr                 lepDR_minBBdr                 lepDR_minBBdr                 lepDR_minBBdr                                                   'F'    [0.00221863086335,8.542760849]
mass_maxBBpt                  mass_maxBBpt                  mass_maxBBpt                  mass_maxBBpt                                                    'F'    [13.898809433,2795.05615234]
mass_maxBBmass                mass_maxBBmass                mass_maxBBmass                mass_maxBBmass                                                  'F'    [21.6002540588,3443.09277344]
mass_maxJJJpt                 mass_maxJJJpt                 mass_maxJJJpt                 mass_maxJJJpt                                                   'F'    [33.1896476746,4502.73583984]
aveBBdr                       aveBBdr                       aveBBdr                       aveBBdr                                                         'F'    [0.413950562477,4.17268610001]
theJetLeadPt                  theJetLeadPt                  theJetLeadPt                  theJetLeadPt                                                    'F'    [50.0213356018,2446.94482422]
AK4HT                         AK4HT                         AK4HT                         AK4HT                                                           'F'    [145.58102417,5389.95605469]
BJetLeadPt                    BJetLeadPt                    BJetLeadPt                    BJetLeadPt                                                      'F'    [30.7579555511,2099.68896484]
AK4HTpMETpLepPt               AK4HTpMETpLepPt               AK4HTpMETpLepPt               AK4HTpMETpLepPt                                                 'F'    [223.396728516,5715.50146484]
topPt                         topPt                         topPt                         topPt                                                           'F'    [0.341156244278,6426.11572266]
minDR_lepJet                  minDR_lepJet                  minDR_lepJet                  minDR_lepJet                                                    'F'    [0.000263258320047,4.19701051712]
ptRel_lepJet                  ptRel_lepJet                  ptRel_lepJet                  ptRel_lepJet                                                    'F'    [0.0265650507063,1411.31054688]
MT_lepMet                     MT_lepMet                     MT_lepMet                     MT_lepMet                                                       'F'    [0.00100133905653,1340.8572998]
mass_lepJets                  mass_lepJets                  mass_lepJets                  mass_lepJets                                                    'F'    [2.0952539444,3147.93457031]
deltaPhi_lepJets              deltaPhi_lepJets              deltaPhi_lepJets              deltaPhi_lepJets                                                'F'    [-3.14157819748,3.14158725739]
NSpec 0


============================================================================ */

#include <vector>
#include <cmath>
#include <string>
#include <iostream>

#define NN new BDTNode
   
#ifndef BDTNode__def
#define BDTNode__def
   
class BDTNode {
   
public:
   
   // constructor of an essentially "empty" node floating in space
   BDTNode ( BDTNode* left,BDTNode* right,
                          int selector, double cutValue, bool cutType, 
                          int nodeType, double purity, double response ) :
   fLeft         ( left         ),
   fRight        ( right        ),
   fSelector     ( selector     ),
   fCutValue     ( cutValue     ),
   fCutType      ( cutType      ),
   fNodeType     ( nodeType     ),
   fPurity       ( purity       ),
   fResponse     ( response     ){
   }

   virtual ~BDTNode();

   // test event if it decends the tree at this node to the right
   virtual bool GoesRight( const std::vector<double>& inputValues ) const;
   BDTNode* GetRight( void )  {return fRight; };

   // test event if it decends the tree at this node to the left 
   virtual bool GoesLeft ( const std::vector<double>& inputValues ) const;
   BDTNode* GetLeft( void ) { return fLeft; };   

   // return  S/(S+B) (purity) at this node (from  training)

   double GetPurity( void ) const { return fPurity; } 
   // return the node type
   int    GetNodeType( void ) const { return fNodeType; }
   double GetResponse(void) const {return fResponse;}

private:

   BDTNode*   fLeft;     // pointer to the left daughter node
   BDTNode*   fRight;    // pointer to the right daughter node
   int                     fSelector; // index of variable used in node selection (decision tree)   
   double                  fCutValue; // cut value appplied on this node to discriminate bkg against sig
   bool                    fCutType;  // true: if event variable > cutValue ==> signal , false otherwise
   int                     fNodeType; // Type of node: -1 == Bkg-leaf, 1 == Signal-leaf, 0 = internal 
   double                  fPurity;   // Purity of node from training
   double                  fResponse; // Regression response value of node
}; 
   
//_______________________________________________________________________
   BDTNode::~BDTNode()
{
   if (fLeft  != NULL) delete fLeft;
   if (fRight != NULL) delete fRight;
}; 
   
//_______________________________________________________________________
bool BDTNode::GoesRight( const std::vector<double>& inputValues ) const
{
   // test event if it decends the tree at this node to the right
   bool result;
     result = (inputValues[fSelector] > fCutValue );
   if (fCutType == true) return result; //the cuts are selecting Signal ;
   else return !result;
}
   
//_______________________________________________________________________
bool BDTNode::GoesLeft( const std::vector<double>& inputValues ) const
{
   // test event if it decends the tree at this node to the left
   if (!this->GoesRight(inputValues)) return true;
   else return false;
}
   
#endif
   
#ifndef IClassifierReader__def
#define IClassifierReader__def

class IClassifierReader {

 public:

   // constructor
   IClassifierReader() : fStatusIsClean( true ) {}
   virtual ~IClassifierReader() {}

   // return classifier response
   virtual double GetMvaValue( const std::vector<double>& inputValues ) const = 0;

   // returns classifier status
   bool IsStatusClean() const { return fStatusIsClean; }

 protected:

   bool fStatusIsClean;
};

#endif

class ReadBDT : public IClassifierReader {

 public:

   // constructor
   ReadBDT( std::vector<std::string>& theInputVars ) 
      : IClassifierReader(),
        fClassName( "ReadBDT" ),
        fNvars( 17 ),
        fIsNormalised( false )
   {      
      // the training input variables
      const char* inputVars[] = { "mass_minBBdr", "mass_minLLdr", "lepDR_minBBdr", "mass_maxBBpt", "mass_maxBBmass", "mass_maxJJJpt", "aveBBdr", "theJetLeadPt", "AK4HT", "BJetLeadPt", "AK4HTpMETpLepPt", "topPt", "minDR_lepJet", "ptRel_lepJet", "MT_lepMet", "mass_lepJets", "deltaPhi_lepJets" };

      // sanity checks
      if (theInputVars.size() <= 0) {
         std::cout << "Problem in class \"" << fClassName << "\": empty input vector" << std::endl;
         fStatusIsClean = false;
      }

      if (theInputVars.size() != fNvars) {
         std::cout << "Problem in class \"" << fClassName << "\": mismatch in number of input values: "
                   << theInputVars.size() << " != " << fNvars << std::endl;
         fStatusIsClean = false;
      }

      // validate input variables
      for (size_t ivar = 0; ivar < theInputVars.size(); ivar++) {
         if (theInputVars[ivar] != inputVars[ivar]) {
            std::cout << "Problem in class \"" << fClassName << "\": mismatch in input variable names" << std::endl
                      << " for variable [" << ivar << "]: " << theInputVars[ivar].c_str() << " != " << inputVars[ivar] << std::endl;
            fStatusIsClean = false;
         }
      }

      // initialize min and max vectors (for normalisation)
      fVmin[0] = 0;
      fVmax[0] = 0;
      fVmin[1] = 0;
      fVmax[1] = 0;
      fVmin[2] = 0;
      fVmax[2] = 0;
      fVmin[3] = 0;
      fVmax[3] = 0;
      fVmin[4] = 0;
      fVmax[4] = 0;
      fVmin[5] = 0;
      fVmax[5] = 0;
      fVmin[6] = 0;
      fVmax[6] = 0;
      fVmin[7] = 0;
      fVmax[7] = 0;
      fVmin[8] = 0;
      fVmax[8] = 0;
      fVmin[9] = 0;
      fVmax[9] = 0;
      fVmin[10] = 0;
      fVmax[10] = 0;
      fVmin[11] = 0;
      fVmax[11] = 0;
      fVmin[12] = 0;
      fVmax[12] = 0;
      fVmin[13] = 0;
      fVmax[13] = 0;
      fVmin[14] = 0;
      fVmax[14] = 0;
      fVmin[15] = 0;
      fVmax[15] = 0;
      fVmin[16] = 0;
      fVmax[16] = 0;

      // initialize input variable types
      fType[0] = 'F';
      fType[1] = 'F';
      fType[2] = 'F';
      fType[3] = 'F';
      fType[4] = 'F';
      fType[5] = 'F';
      fType[6] = 'F';
      fType[7] = 'F';
      fType[8] = 'F';
      fType[9] = 'F';
      fType[10] = 'F';
      fType[11] = 'F';
      fType[12] = 'F';
      fType[13] = 'F';
      fType[14] = 'F';
      fType[15] = 'F';
      fType[16] = 'F';

      // initialize constants
      Initialize();

   }

   // destructor
   virtual ~ReadBDT() {
      Clear(); // method-specific
   }

   // the classifier response
   // "inputValues" is a vector of input values in the same order as the 
   // variables given to the constructor
   double GetMvaValue( const std::vector<double>& inputValues ) const;

 private:

   // method-specific destructor
   void Clear();

   // common member variables
   const char* fClassName;

   const size_t fNvars;
   size_t GetNvar()           const { return fNvars; }
   char   GetType( int ivar ) const { return fType[ivar]; }

   // normalisation of input variables
   const bool fIsNormalised;
   bool IsNormalised() const { return fIsNormalised; }
   double fVmin[17];
   double fVmax[17];
   double NormVariable( double x, double xmin, double xmax ) const {
      // normalise to output range: [-1, 1]
      return 2*(x - xmin)/(xmax - xmin) - 1.0;
   }

   // type of input variable: 'F' or 'I'
   char   fType[17];

   // initialize internal variables
   void Initialize();
   double GetMvaValue__( const std::vector<double>& inputValues ) const;

   // private members (method specific)
   std::vector<BDTNode*> fForest;       // i.e. root nodes of decision trees
   std::vector<double>                fBoostWeights; // the weights applied in the individual boosts
};

double ReadBDT::GetMvaValue__( const std::vector<double>& inputValues ) const
{
   double myMVA = 0;
   double norm  = 0;
   for (unsigned int itree=0; itree<fForest.size(); itree++){
      BDTNode *current = fForest[itree];
      while (current->GetNodeType() == 0) { //intermediate node
         if (current->GoesRight(inputValues)) current=(BDTNode*)current->GetRight();
         else current=(BDTNode*)current->GetLeft();
      }
      myMVA += fBoostWeights[itree] *  current->GetNodeType();
      norm  += fBoostWeights[itree];
   }
   return myMVA /= norm;
};

void ReadBDT::Initialize()
{
  // itree = 0
  fBoostWeights.push_back(0.529249977159378);
  fForest.push_back( 
NN(
NN(
NN(
NN(
0, 
0, 
-1, 0, 1, 1, 0.782076,-99) , 
NN(
0, 
0, 
-1, 0, 1, -1, 0.470467,-99) , 
12, 0.518539, 0, 0, 0.749051,-99) , 
NN(
NN(
0, 
0, 
-1, 0, 1, 1, 0.610618,-99) , 
NN(
0, 
0, 
-1, 0, 1, -1, 0.327474,-99) , 
8, 484.939, 0, 0, 0.527186,-99) , 
3, 176.619, 0, 0, 0.629771,-99) , 
NN(
0, 
0, 
-1, 459.269, 0, -1, 0.106236,-99) , 
10, 523.978, 0, 0, 0.490095,-99)    );
  // itree = 1
  fBoostWeights.push_back(0.391217);
  fForest.push_back( 
NN(
NN(
NN(
0, 
0, 
-1, 541.733, 0, 1, 0.739608,-99) , 
NN(
NN(
0, 
0, 
-1, 0, 1, 1, 0.542721,-99) , 
NN(
0, 
0, 
-1, 0, 1, -1, 0.261087,-99) , 
12, 0.41254, 0, 0, 0.51912,-99) , 
3, 176.619, 0, 0, 0.625135,-99) , 
NN(
0, 
0, 
-1, 452.909, 0, -1, 0.210024,-99) , 
10, 547.902, 0, 0, 0.509061,-99)    );
  // itree = 2
  fBoostWeights.push_back(0.354481);
  fForest.push_back( 
NN(
NN(
NN(
NN(
0, 
0, 
-1, 0, 1, 1, 0.726954,-99) , 
NN(
0, 
0, 
-1, 0, 1, -1, 0.41585,-99) , 
12, 0.427679, 0, 0, 0.696604,-99) , 
NN(
NN(
0, 
0, 
-1, 0, 1, 1, 0.555028,-99) , 
NN(
0, 
0, 
-1, 0, 1, -1, 0.419307,-99) , 
4, 235.909, 0, 0, 0.488924,-99) , 
3, 176.619, 0, 0, 0.583549,-99) , 
NN(
0, 
0, 
-1, 282.688, 0, -1, 0.175377,-99) , 
8, 351.243, 0, 0, 0.505784,-99)    );
  // itree = 3
  fBoostWeights.push_back(0.251232);
  fForest.push_back( 
NN(
NN(
NN(
NN(
0, 
0, 
-1, 0, 1, 1, 0.661345,-99) , 
NN(
0, 
0, 
-1, 0, 1, -1, 0.384676,-99) , 
7, 437.117, 1, 0, 0.63824,-99) , 
NN(
NN(
0, 
0, 
-1, 0, 1, 1, 0.502463,-99) , 
NN(
0, 
0, 
-1, 0, 1, -1, 0.242479,-99) , 
12, 0.486324, 0, 0, 0.474326,-99) , 
8, 568.534, 0, 0, 0.55233,-99) , 
NN(
0, 
0, 
-1, 205.145, 0, -1, 0.130741,-99) , 
10, 438.773, 0, 0, 0.503401,-99)    );
  // itree = 4
  fBoostWeights.push_back(0.283047);
  fForest.push_back( 
NN(
NN(
NN(
0, 
0, 
-1, 182.289, 0, 1, 0.65692,-99) , 
NN(
NN(
0, 
0, 
-1, 0, 1, 1, 0.563705,-99) , 
NN(
0, 
0, 
-1, 0, 1, -1, 0.411566,-99) , 
3, 133.449, 0, 0, 0.494485,-99) , 
8, 647.64, 0, 0, 0.559816,-99) , 
NN(
0, 
0, 
-1, 163.618, 0, -1, 0.227322,-99) , 
8, 351.243, 0, 0, 0.499395,-99)    );
  // itree = 5
  fBoostWeights.push_back(0.232141);
  fForest.push_back( 
NN(
NN(
NN(
0, 
0, 
-1, 140.672, 0, 1, 0.654248,-99) , 
NN(
NN(
0, 
0, 
-1, 0, 1, 1, 0.533376,-99) , 
NN(
0, 
0, 
-1, 0, 1, -1, 0.40964,-99) , 
5, 190.47, 0, 0, 0.493043,-99) , 
8, 671.352, 0, 0, 0.551056,-99) , 
NN(
0, 
0, 
-1, 217.489, 0, -1, 0.174075,-99) , 
10, 438.773, 0, 0, 0.510896,-99)    );
  // itree = 6
  fBoostWeights.push_back(0.165539);
  fForest.push_back( 
NN(
NN(
NN(
0, 
0, 
-1, 180.52, 0, 1, 0.5449,-99) , 
NN(
0, 
0, 
-1, 0, 1, -1, 0.209464,-99) , 
12, 0.247882, 0, 0, 0.530635,-99) , 
NN(
0, 
0, 
-1, 378.22, 0, -1, 0.188906,-99) , 
10, 441.533, 0, 0, 0.494991,-99)    );
  // itree = 7
  fBoostWeights.push_back(0.164597);
  fForest.push_back( 
NN(
NN(
NN(
0, 
0, 
-1, 222.175, 0, 1, 0.536593,-99) , 
NN(
0, 
0, 
-1, 0, 1, -1, 0.253582,-99) , 
12, 0.247131, 0, 0, 0.524078,-99) , 
NN(
NN(
NN(
0, 
0, 
-1, 0, 1, 1, 0.576272,-99) , 
NN(
0, 
0, 
-1, 0, 1, -1, 0.292285,-99) , 
3, 161.968, 0, 0, 0.366728,-99) , 
NN(
0, 
0, 
-1, 146.32, 0, -1, 0.115171,-99) , 
8, 271.849, 0, 0, 0.273058,-99) , 
8, 352.482, 0, 0, 0.480621,-99)    );
  // itree = 8
  fBoostWeights.push_back(0.137621);
  fForest.push_back( 
NN(
NN(
NN(
0, 
0, 
-1, 416.191, 0, 1, 0.65289,-99) , 
NN(
NN(
0, 
0, 
-1, 0, 1, 1, 0.500184,-99) , 
NN(
0, 
0, 
-1, 0, 1, -1, 0.280393,-99) , 
12, 0.290494, 0, 0, 0.49052,-99) , 
0, 222.175, 0, 0, 0.511226,-99) , 
NN(
NN(
NN(
0, 
0, 
-1, 0, 1, 1, 0.50431,-99) , 
NN(
0, 
0, 
-1, 0, 1, -1, 0.326872,-99) , 
5, 286.059, 0, 0, 0.381062,-99) , 
NN(
0, 
0, 
-1, 271.465, 0, -1, 0.169603,-99) , 
4, 168.011, 0, 0, 0.294545,-99) , 
10, 530.065, 0, 0, 0.46242,-99)    );
  // itree = 9
  fBoostWeights.push_back(0.155758);
  fForest.push_back( 
NN(
NN(
NN(
NN(
0, 
0, 
-1, 0, 1, 1, 0.651164,-99) , 
NN(
0, 
0, 
-1, 0, 1, -1, 0.498031,-99) , 
9, 172.645, 0, 0, 0.602507,-99) , 
NN(
0, 
0, 
-1, 513.465, 0, -1, 0.44532,-99) , 
0, 180.52, 0, 0, 0.473485,-99) , 
NN(
0, 
0, 
-1, 0, 1, -1, 0.0935678,-99) , 
8, 248.412, 0, 0, 0.458219,-99)    );
  // itree = 10
  fBoostWeights.push_back(0.211424);
  fForest.push_back( 
NN(
NN(
NN(
NN(
0, 
0, 
-1, 0, 1, 1, 0.612361,-99) , 
NN(
0, 
0, 
-1, 0, 1, -1, 0.444165,-99) , 
11, 327.579, 1, 0, 0.586371,-99) , 
NN(
NN(
0, 
0, 
-1, 0, 1, 1, 0.613536,-99) , 
NN(
0, 
0, 
-1, 0, 1, -1, 0.387412,-99) , 
3, 220.914, 0, 0, 0.461577,-99) , 
1, 170.121, 1, 0, 0.563802,-99) , 
NN(
NN(
NN(
0, 
0, 
-1, 0, 1, 1, 0.505114,-99) , 
NN(
0, 
0, 
-1, 0, 1, -1, 0.397903,-99) , 
6, 2.421, 0, 0, 0.440399,-99) , 
NN(
0, 
0, 
-1, 2.27262, 0, -1, 0.124328,-99) , 
8, 267.216, 0, 0, 0.400951,-99) , 
10, 655.56, 0, 0, 0.495268,-99)    );
  // itree = 11
  fBoostWeights.push_back(0.166182);
  fForest.push_back( 
NN(
NN(
NN(
0, 
0, 
-1, 140.672, 0, 1, 0.587418,-99) , 
NN(
NN(
0, 
0, 
-1, 0, 1, 1, 0.515884,-99) , 
NN(
0, 
0, 
-1, 0, 1, -1, 0.331995,-99) , 
4, 417.997, 1, 0, 0.497199,-99) , 
8, 590.96, 0, 0, 0.549326,-99) , 
NN(
0, 
0, 
-1, 268.993, 0, -1, 0.368596,-99) , 
8, 419.247, 0, 0, 0.499662,-99)    );
  // itree = 12
  fBoostWeights.push_back(0.13306);
  fForest.push_back( 
NN(
NN(
NN(
NN(
0, 
0, 
-1, 0, 1, 1, 0.589823,-99) , 
NN(
0, 
0, 
-1, 0, 1, -1, 0.49721,-99) , 
1, 129.326, 1, 0, 0.565691,-99) , 
NN(
0, 
0, 
-1, 282.688, 0, -1, 0.475513,-99) , 
8, 556.905, 0, 0, 0.522083,-99) , 
NN(
0, 
0, 
-1, 294.567, 0, -1, 0.322818,-99) , 
4, 155.776, 0, 0, 0.492156,-99)    );
  // itree = 13
  fBoostWeights.push_back(0.147347);
  fForest.push_back( 
NN(
NN(
NN(
0, 
0, 
-1, 1351.14, 0, 1, 0.588984,-99) , 
NN(
NN(
0, 
0, 
-1, 0, 1, 1, 0.527792,-99) , 
NN(
0, 
0, 
-1, 0, 1, -1, 0.391573,-99) , 
13, 26.2385, 0, 0, 0.510042,-99) , 
0, 138.865, 0, 0, 0.538125,-99) , 
NN(
NN(
0, 
0, 
-1, 0, 1, 1, 0.527288,-99) , 
NN(
0, 
0, 
-1, 274.623, 0, -1, 0.269693,-99) , 
4, 214.116, 0, 0, 0.351876,-99) , 
8, 351.243, 0, 0, 0.509447,-99)    );
  // itree = 14
  fBoostWeights.push_back(0.158662);
  fForest.push_back( 
NN(
NN(
NN(
NN(
0, 
0, 
-1, 0, 1, 1, 0.565043,-99) , 
NN(
0, 
0, 
-1, 0, 1, -1, 0.467544,-99) , 
5, 217.752, 0, 0, 0.533964,-99) , 
NN(
0, 
0, 
-1, 0, 1, -1, 0.314447,-99) , 
12, 0.32366, 0, 0, 0.522317,-99) , 
NN(
0, 
0, 
-1, 279.332, 0, -1, 0.333261,-99) , 
4, 160.397, 0, 0, 0.491619,-99)    );
  // itree = 15
  fBoostWeights.push_back(0.117528);
  fForest.push_back( 
NN(
NN(
NN(
0, 
0, 
-1, 2.86232, 1, 1, 0.586565,-99) , 
NN(
NN(
0, 
0, 
-1, 0, 1, 1, 0.621315,-99) , 
NN(
0, 
0, 
-1, 0, 1, -1, 0.475813,-99) , 
8, 1048.26, 0, 0, 0.489114,-99) , 
14, 105.167, 0, 0, 0.509857,-99) , 
NN(
0, 
0, 
-1, 153.657, 0, -1, 0.258961,-99) , 
10, 423.974, 0, 0, 0.491937,-99)    );
  // itree = 16
  fBoostWeights.push_back(0.113717);
  fForest.push_back( 
NN(
NN(
NN(
0, 
0, 
-1, 652.175, 0, 1, 0.538972,-99) , 
NN(
0, 
0, 
-1, 37.9104, 0, -1, 0.414724,-99) , 
10, 524.396, 0, 0, 0.518199,-99) , 
NN(
0, 
0, 
-1, 0, 1, -1, 0.171663,-99) , 
8, 248.412, 0, 0, 0.506016,-99)    );
  // itree = 17
  fBoostWeights.push_back(0.103247);
  fForest.push_back( 
NN(
NN(
NN(
NN(
0, 
0, 
-1, 0, 1, 1, 0.577799,-99) , 
NN(
0, 
0, 
-1, 0, 1, -1, 0.418158,-99) , 
7, 493.256, 1, 0, 0.564179,-99) , 
NN(
NN(
0, 
0, 
-1, 0, 1, 1, 0.50582,-99) , 
NN(
0, 
0, 
-1, 0, 1, -1, 0.355158,-99) , 
11, 258.55, 1, 0, 0.486782,-99) , 
8, 651.671, 0, 0, 0.514324,-99) , 
NN(
0, 
0, 
-1, 0, 1, -1, 0.198199,-99) , 
8, 248.412, 0, 0, 0.503863,-99)    );
  // itree = 18
  fBoostWeights.push_back(0.122715);
  fForest.push_back( 
NN(
NN(
NN(
NN(
0, 
0, 
-1, 0, 1, 1, 0.563732,-99) , 
NN(
0, 
0, 
-1, 0, 1, -1, 0.44862,-99) , 
2, 2.98019, 1, 0, 0.538499,-99) , 
NN(
0, 
0, 
-1, 123.984, 0, -1, 0.468319,-99) , 
9, 144.195, 0, 0, 0.508114,-99) , 
NN(
0, 
0, 
-1, 2.30048, 0, -1, 0.248002,-99) , 
10, 414.366, 0, 0, 0.491854,-99)    );
  // itree = 19
  fBoostWeights.push_back(0.122205);
  fForest.push_back( 
NN(
NN(
NN(
NN(
0, 
0, 
-1, 0, 1, 1, 0.543152,-99) , 
NN(
0, 
0, 
-1, 0, 1, -1, 0.470595,-99) , 
2, 2.86625, 1, 0, 0.523749,-99) , 
NN(
0, 
0, 
-1, 0, 1, -1, 0.331856,-99) , 
12, 0.32942, 0, 0, 0.512318,-99) , 
NN(
NN(
NN(
0, 
0, 
-1, 0, 1, 1, 0.541547,-99) , 
NN(
0, 
0, 
-1, 0, 1, -1, 0.343506,-99) , 
6, 2.38905, 0, 0, 0.437122,-99) , 
NN(
0, 
0, 
-1, 0, 1, -1, 0.197236,-99) , 
8, 263.631, 0, 0, 0.352086,-99) , 
8, 328.025, 0, 0, 0.494965,-99)    );
  // itree = 20
  fBoostWeights.push_back(0.0731539);
  fForest.push_back( 
NN(
NN(
NN(
NN(
0, 
0, 
-1, 0, 1, 1, 0.55816,-99) , 
NN(
0, 
0, 
-1, 0, 1, -1, 0.495576,-99) , 
8, 652.841, 0, 0, 0.51764,-99) , 
NN(
0, 
0, 
-1, 0, 1, -1, 0.365442,-99) , 
6, 1.47296, 0, 0, 0.509924,-99) , 
NN(
0, 
0, 
-1, 0, 1, -1, 0.233833,-99) , 
8, 249.677, 0, 0, 0.501185,-99)    );
  // itree = 21
  fBoostWeights.push_back(0.0954176);
  fForest.push_back( 
NN(
NN(
NN(
NN(
0, 
0, 
-1, 0, 1, 1, 0.536113,-99) , 
NN(
0, 
0, 
-1, 0, 1, -1, 0.478943,-99) , 
2, 1.34756, 0, 0, 0.524886,-99) , 
NN(
0, 
0, 
-1, 0, 1, -1, 0.363138,-99) , 
12, 0.32366, 0, 0, 0.516382,-99) , 
NN(
0, 
0, 
-1, 376.281, 0, -1, 0.333126,-99) , 
10, 428.389, 0, 0, 0.503587,-99)    );
  // itree = 22
  fBoostWeights.push_back(0.0955127);
  fForest.push_back( 
NN(
NN(
NN(
NN(
0, 
0, 
-1, 0, 1, 1, 0.593254,-99) , 
NN(
0, 
0, 
-1, 0, 1, -1, 0.495366,-99) , 
4, 476.676, 1, 0, 0.560865,-99) , 
NN(
NN(
0, 
0, 
-1, 0, 1, 1, 0.515388,-99) , 
NN(
0, 
0, 
-1, 0, 1, -1, 0.404413,-99) , 
4, 413.607, 1, 0, 0.501665,-99) , 
3, 231.711, 0, 0, 0.519016,-99) , 
NN(
NN(
NN(
0, 
0, 
-1, 0, 1, 1, 0.503732,-99) , 
NN(
0, 
0, 
-1, 0, 1, -1, 0.416009,-99) , 
4, 135.836, 0, 0, 0.452082,-99) , 
NN(
0, 
0, 
-1, 0, 1, -1, 0.177822,-99) , 
8, 293.468, 0, 0, 0.38947,-99) , 
4, 155.776, 0, 0, 0.500357,-99)    );
  // itree = 23
  fBoostWeights.push_back(0.0643725);
  fForest.push_back( 
NN(
NN(
NN(
0, 
0, 
-1, 180.52, 0, 1, 0.515827,-99) , 
NN(
0, 
0, 
-1, 0, 1, -1, 0.278259,-99) , 
12, 0.247688, 0, 0, 0.507517,-99) , 
NN(
0, 
0, 
-1, 2.33915, 0, -1, 0.336342,-99) , 
10, 427.842, 0, 0, 0.496425,-99)    );
  // itree = 24
  fBoostWeights.push_back(0.0759659);
  fForest.push_back( 
NN(
NN(
NN(
NN(
0, 
0, 
-1, 0, 1, 1, 0.545631,-99) , 
NN(
0, 
0, 
-1, 0, 1, -1, 0.489324,-99) , 
3, 180.065, 0, 0, 0.511393,-99) , 
NN(
0, 
0, 
-1, 0, 1, -1, 0.341835,-99) , 
12, 0.247688, 0, 0, 0.504769,-99) , 
NN(
0, 
0, 
-1, 265.526, 0, -1, 0.342996,-99) , 
10, 427.842, 0, 0, 0.494221,-99)    );
  // itree = 25
  fBoostWeights.push_back(0.071467);
  fForest.push_back( 
NN(
NN(
NN(
0, 
0, 
-1, 507.959, 1, 1, 0.618915,-99) , 
NN(
NN(
0, 
0, 
-1, 0, 1, 1, 0.556784,-99) , 
NN(
0, 
0, 
-1, 0, 1, -1, 0.492196,-99) , 
0, 153.628, 0, 0, 0.508995,-99) , 
10, 1370.41, 0, 0, 0.516653,-99) , 
NN(
0, 
0, 
-1, 2.34496, 0, -1, 0.361236,-99) , 
10, 439.32, 0, 0, 0.505103,-99)    );
  // itree = 26
  fBoostWeights.push_back(0.0733457);
  fForest.push_back( 
NN(
NN(
NN(
0, 
0, 
-1, 111.547, 0, 1, 0.526168,-99) , 
NN(
0, 
0, 
-1, 0, 1, -1, 0.376656,-99) , 
12, 0.32942, 0, 0, 0.518465,-99) , 
NN(
0, 
0, 
-1, 0, 1, -1, 0.278201,-99) , 
8, 248.412, 0, 0, 0.511618,-99)    );
  // itree = 27
  fBoostWeights.push_back(0.070789);
  fForest.push_back( 
NN(
NN(
NN(
NN(
0, 
0, 
-1, 0, 1, 1, 0.518578,-99) , 
NN(
0, 
0, 
-1, 0, 1, -1, 0.37371,-99) , 
6, 1.37064, 0, 0, 0.512961,-99) , 
NN(
0, 
0, 
-1, 0, 1, -1, 0.348391,-99) , 
12, 0.247688, 0, 0, 0.507084,-99) , 
NN(
0, 
0, 
-1, 372.273, 0, -1, 0.352117,-99) , 
10, 428.389, 0, 0, 0.496825,-99)    );
  // itree = 28
  fBoostWeights.push_back(0.0603636);
  fForest.push_back( 
NN(
NN(
NN(
0, 
0, 
-1, 853.302, 0, 1, 0.517031,-99) , 
NN(
0, 
0, 
-1, 0.494702, 0, -1, 0.45959,-99) , 
14, 44.8017, 0, 0, 0.501168,-99) , 
NN(
0, 
0, 
-1, 0, 1, -1, 0.223308,-99) , 
8, 248.412, 0, 0, 0.493862,-99)    );
  // itree = 29
  fBoostWeights.push_back(0.0908554);
  fForest.push_back( 
NN(
NN(
NN(
NN(
0, 
0, 
-1, 0, 1, 1, 0.559984,-99) , 
NN(
0, 
0, 
-1, 0, 1, -1, 0.464885,-99) , 
2, 0.929676, 0, 0, 0.546612,-99) , 
NN(
0, 
0, 
-1, 0, 1, -1, 0.414645,-99) , 
4, 743.612, 1, 0, 0.538169,-99) , 
NN(
0, 
0, 
-1, 261.844, 0, -1, 0.464203,-99) , 
8, 601.69, 0, 0, 0.495402,-99)    );
  // itree = 30
  fBoostWeights.push_back(0.0619778);
  fForest.push_back( 
NN(
NN(
NN(
NN(
0, 
0, 
-1, 0, 1, 1, 0.513607,-99) , 
NN(
0, 
0, 
-1, 0, 1, -1, 0.399386,-99) , 
6, 3.07443, 1, 0, 0.507582,-99) , 
NN(
0, 
0, 
-1, 0, 1, -1, 0.344363,-99) , 
12, 0.247131, 0, 0, 0.5019,-99) , 
NN(
NN(
0, 
0, 
-1, 0, 1, 1, 0.52102,-99) , 
NN(
0, 
0, 
-1, 0, 1, -1, 0.249023,-99) , 
5, 201.117, 0, 0, 0.370191,-99) , 
10, 427.842, 0, 0, 0.493542,-99)    );
  // itree = 31
  fBoostWeights.push_back(0.0816157);
  fForest.push_back( 
NN(
NN(
NN(
NN(
0, 
0, 
-1, 0, 1, 1, 0.517595,-99) , 
NN(
0, 
0, 
-1, 0, 1, -1, 0.326194,-99) , 
13, 17.209, 0, 0, 0.509328,-99) , 
NN(
NN(
0, 
0, 
-1, 0, 1, 1, 0.541643,-99) , 
NN(
0, 
0, 
-1, 0, 1, -1, 0.402312,-99) , 
10, 1170.81, 0, 0, 0.446335,-99) , 
11, 252.332, 1, 0, 0.495691,-99) , 
NN(
0, 
0, 
-1, 0, 1, -1, 0.311117,-99) , 
8, 250.432, 0, 0, 0.49045,-99)    );
  // itree = 32
  fBoostWeights.push_back(0.0674859);
  fForest.push_back( 
NN(
NN(
NN(
NN(
0, 
0, 
-1, 0, 1, 1, 0.56965,-99) , 
NN(
0, 
0, 
-1, 0, 1, -1, 0.45242,-99) , 
7, 487.084, 1, 0, 0.544007,-99) , 
NN(
0, 
0, 
-1, 499.448, 1, -1, 0.48074,-99) , 
8, 886.215, 0, 0, 0.49056,-99) , 
NN(
NN(
0, 
0, 
-1, 0, 1, 1, 0.51334,-99) , 
NN(
0, 
0, 
-1, 0, 1, -1, 0.246361,-99) , 
8, 273.354, 0, 0, 0.369917,-99) , 
10, 427.842, 0, 0, 0.482912,-99)    );
  // itree = 33
  fBoostWeights.push_back(0.0461841);
  fForest.push_back( 
NN(
NN(
NN(
0, 
0, 
-1, 0, 1, 1, 0.582269,-99) , 
NN(
NN(
0, 
0, 
-1, 0, 1, 1, 0.503226,-99) , 
NN(
0, 
0, 
-1, 0, 1, -1, 0.424229,-99) , 
4, 502.104, 1, 0, 0.495515,-99) , 
0, 265.525, 0, 0, 0.501089,-99) , 
NN(
0, 
0, 
-1, 2.34496, 0, -1, 0.371453,-99) , 
10, 440.244, 0, 0, 0.491796,-99)    );
  // itree = 34
  fBoostWeights.push_back(0.0696832);
  fForest.push_back( 
NN(
NN(
NN(
0, 
0, 
-1, 0, 1, 1, 0.611666,-99) , 
NN(
NN(
0, 
0, 
-1, 0, 1, 1, 0.510991,-99) , 
NN(
0, 
0, 
-1, 0, 1, -1, 0.44161,-99) , 
4, 447.484, 1, 0, 0.500052,-99) , 
10, 1516.09, 0, 0, 0.505722,-99) , 
NN(
NN(
NN(
0, 
0, 
-1, 0, 1, 1, 0.500198,-99) , 
NN(
0, 
0, 
-1, 0, 1, -1, 0.422777,-99) , 
0, 86.1849, 0, 0, 0.452319,-99) , 
NN(
0, 
0, 
-1, 0, 1, -1, 0.176146,-99) , 
10, 452.437, 0, 0, 0.391051,-99) , 
4, 155.776, 0, 0, 0.49025,-99)    );
  // itree = 35
  fBoostWeights.push_back(0.0762434);
  fForest.push_back( 
NN(
NN(
NN(
0, 
0, 
-1, 144.373, 1, 1, 0.560822,-99) , 
NN(
NN(
0, 
0, 
-1, 0, 1, 1, 0.534399,-99) , 
NN(
0, 
0, 
-1, 0, 1, -1, 0.476596,-99) , 
0, 182.396, 0, 0, 0.48776,-99) , 
14, 123.442, 0, 0, 0.496522,-99) , 
NN(
NN(
NN(
0, 
0, 
-1, 0, 1, 1, 0.515163,-99) , 
NN(
0, 
0, 
-1, 0, 1, -1, 0.428151,-99) , 
5, 168.202, 1, 0, 0.452847,-99) , 
NN(
0, 
0, 
-1, 0, 1, -1, 0.261233,-99) , 
10, 453.878, 0, 0, 0.408802,-99) , 
4, 150.633, 0, 0, 0.485841,-99)    );
  // itree = 36
  fBoostWeights.push_back(0.0675742);
  fForest.push_back( 
NN(
NN(
NN(
NN(
0, 
0, 
-1, 0, 1, 1, 0.573202,-99) , 
NN(
0, 
0, 
-1, 0, 1, -1, 0.493315,-99) , 
7, 274.161, 1, 0, 0.528928,-99) , 
NN(
0, 
0, 
-1, 552.041, 1, -1, 0.478845,-99) , 
8, 671.352, 0, 0, 0.497012,-99) , 
NN(
0, 
0, 
-1, 267.797, 0, -1, 0.369831,-99) , 
10, 440.244, 0, 0, 0.488321,-99)    );
  // itree = 37
  fBoostWeights.push_back(0.0671212);
  fForest.push_back( 
NN(
NN(
NN(
0, 
0, 
-1, 317.501, 1, 1, 0.575815,-99) , 
NN(
0, 
0, 
-1, 0, 1, -1, 0.485553,-99) , 
2, 1.01514, 0, 0, 0.558502,-99) , 
NN(
NN(
NN(
0, 
0, 
-1, 0, 1, 1, 0.506961,-99) , 
NN(
0, 
0, 
-1, 0, 1, -1, 0.411173,-99) , 
11, 278.79, 1, 0, 0.495717,-99) , 
NN(
0, 
0, 
-1, 0, 1, -1, 0.330541,-99) , 
8, 266.554, 0, 0, 0.48799,-99) , 
8, 762.566, 0, 0, 0.505106,-99)    );
  // itree = 38
  fBoostWeights.push_back(0.0774062);
  fForest.push_back( 
NN(
NN(
NN(
0, 
0, 
-1, 0, 1, 1, 0.620339,-99) , 
NN(
NN(
0, 
0, 
-1, 0, 1, 1, 0.525545,-99) , 
NN(
0, 
0, 
-1, 0, 1, -1, 0.435838,-99) , 
6, 1.49748, 0, 0, 0.520163,-99) , 
5, 150.343, 1, 0, 0.526363,-99) , 
NN(
0, 
0, 
-1, 261.947, 0, -1, 0.452354,-99) , 
10, 632.288, 0, 0, 0.499828,-99)    );
  // itree = 39
  fBoostWeights.push_back(0.0513989);
  fForest.push_back( 
NN(
NN(
NN(
0, 
0, 
-1, 1.10199, 0, 1, 0.54862,-99) , 
NN(
NN(
0, 
0, 
-1, 0, 1, 1, 0.505086,-99) , 
NN(
0, 
0, 
-1, 0, 1, -1, 0.418305,-99) , 
14, 8.78527, 0, 0, 0.499517,-99) , 
14, 112.002, 0, 0, 0.507856,-99) , 
NN(
NN(
NN(
0, 
0, 
-1, 0, 1, 1, 0.509131,-99) , 
NN(
0, 
0, 
-1, 0, 1, -1, 0.39773,-99) , 
10, 574.664, 0, 0, 0.473327,-99) , 
NN(
0, 
0, 
-1, 0, 1, -1, 0.233866,-99) , 
8, 293.468, 0, 0, 0.426368,-99) , 
4, 155.776, 0, 0, 0.496774,-99)    );
  // itree = 40
  fBoostWeights.push_back(0.045833);
  fForest.push_back( 
NN(
NN(
NN(
0, 
0, 
-1, 1408.41, 0, 1, 0.510713,-99) , 
NN(
0, 
0, 
-1, 294.767, 0, -1, 0.445949,-99) , 
4, 163.858, 0, 0, 0.500529,-99) , 
NN(
0, 
0, 
-1, 0, 1, -1, 0.308957,-99) , 
12, 0.247131, 0, 0, 0.494597,-99)    );
  // itree = 41
  fBoostWeights.push_back(0.0351466);
  fForest.push_back( 
NN(
NN(
0, 
0, 
-1, 0, 1, 1, 0.622509,-99) , 
NN(
0, 
0, 
-1, 402.245, 0, -1, 0.48743,-99) , 
10, 1516.83, 0, 0, 0.493569,-99)    );
  // itree = 42
  fBoostWeights.push_back(0.0651665);
  fForest.push_back( 
NN(
NN(
NN(
0, 
0, 
-1, 941.387, 0, 1, 0.522748,-99) , 
NN(
NN(
0, 
0, 
-1, 0, 1, 1, 0.513324,-99) , 
NN(
0, 
0, 
-1, 0, 1, -1, 0.420828,-99) , 
0, 186.178, 0, 0, 0.457407,-99) , 
9, 295.019, 1, 0, 0.513639,-99) , 
NN(
0, 
0, 
-1, 275.491, 0, -1, 0.456662,-99) , 
10, 623.982, 0, 0, 0.494292,-99)    );
  // itree = 43
  fBoostWeights.push_back(0.0610497);
  fForest.push_back( 
NN(
NN(
NN(
0, 
0, 
-1, 161.258, 1, 1, 0.555122,-99) , 
NN(
NN(
0, 
0, 
-1, 0, 1, 1, 0.506805,-99) , 
NN(
0, 
0, 
-1, 0, 1, -1, 0.457553,-99) , 
4, 215.15, 0, 0, 0.490887,-99) , 
14, 131.458, 0, 0, 0.497409,-99) , 
NN(
NN(
NN(
0, 
0, 
-1, 0, 1, 1, 0.531558,-99) , 
NN(
0, 
0, 
-1, 0, 1, -1, 0.440873,-99) , 
3, 144.349, 0, 0, 0.491042,-99) , 
NN(
0, 
0, 
-1, 0, 1, -1, 0.348965,-99) , 
13, 17.9321, 0, 0, 0.443591,-99) , 
13, 27.6988, 0, 0, 0.489537,-99)    );
  // itree = 44
  fBoostWeights.push_back(0.055486);
  fForest.push_back( 
NN(
NN(
NN(
NN(
0, 
0, 
-1, 0, 1, 1, 0.547514,-99) , 
NN(
0, 
0, 
-1, 0, 1, -1, 0.477881,-99) , 
2, 1.69168, 0, 0, 0.525814,-99) , 
NN(
0, 
0, 
-1, 414.913, 0, -1, 0.481235,-99) , 
3, 230.86, 0, 0, 0.492422,-99) , 
NN(
0, 
0, 
-1, 0, 1, -1, 0.362887,-99) , 
12, 0.247131, 0, 0, 0.488161,-99)    );
  // itree = 45
  fBoostWeights.push_back(0.0568655);
  fForest.push_back( 
NN(
NN(
NN(
0, 
0, 
-1, 784.134, 0, 1, 0.516447,-99) , 
NN(
NN(
0, 
0, 
-1, 0, 1, 1, 0.5027,-99) , 
NN(
0, 
0, 
-1, 0, 1, -1, 0.39653,-99) , 
8, 988.047, 0, 0, 0.443372,-99) , 
4, 606.98, 1, 0, 0.511455,-99) , 
NN(
NN(
NN(
0, 
0, 
-1, 0, 1, 1, 0.548245,-99) , 
NN(
0, 
0, 
-1, 0, 1, -1, 0.462941,-99) , 
0, 61.1557, 1, 0, 0.496325,-99) , 
NN(
0, 
0, 
-1, 0, 1, -1, 0.232292,-99) , 
10, 453.878, 0, 0, 0.442414,-99) , 
4, 155.776, 0, 0, 0.502307,-99)    );
  // itree = 46
  fBoostWeights.push_back(0.0463546);
  fForest.push_back( 
NN(
NN(
NN(
0, 
0, 
-1, 544.82, 0, 1, 0.599491,-99) , 
NN(
0, 
0, 
-1, 0, 1, -1, 0.490432,-99) , 
7, 522.304, 1, 0, 0.570542,-99) , 
NN(
NN(
NN(
0, 
0, 
-1, 0, 1, 1, 0.501933,-99) , 
NN(
0, 
0, 
-1, 0, 1, -1, 0.409786,-99) , 
5, 532.84, 1, 0, 0.491183,-99) , 
NN(
0, 
0, 
-1, 0, 1, -1, 0.330588,-99) , 
10, 380.283, 0, 0, 0.486407,-99) , 
10, 1223.55, 0, 0, 0.495369,-99)    );
  // itree = 47
  fBoostWeights.push_back(0.0532205);
  fForest.push_back( 
NN(
NN(
NN(
0, 
0, 
-1, 1460.43, 0, 1, 0.585454,-99) , 
NN(
0, 
0, 
-1, 0, 1, -1, 0.475749,-99) , 
7, 535.117, 1, 0, 0.562489,-99) , 
NN(
0, 
0, 
-1, 0.329965, 0, -1, 0.479713,-99) , 
8, 966.578, 0, 0, 0.48967,-99)    );
  // itree = 48
  fBoostWeights.push_back(0.064398);
  fForest.push_back( 
NN(
NN(
NN(
NN(
0, 
0, 
-1, 0, 1, 1, 0.547333,-99) , 
NN(
0, 
0, 
-1, 0, 1, -1, 0.496269,-99) , 
9, 180.532, 0, 0, 0.513438,-99) , 
NN(
NN(
0, 
0, 
-1, 0, 1, 1, 0.521186,-99) , 
NN(
0, 
0, 
-1, 0, 1, -1, 0.416475,-99) , 
5, 414.235, 0, 0, 0.458898,-99) , 
11, 252.332, 1, 0, 0.500794,-99) , 
NN(
0, 
0, 
-1, 2.27262, 0, -1, 0.402233,-99) , 
10, 439.32, 0, 0, 0.494443,-99)    );
  // itree = 49
  fBoostWeights.push_back(0.0806022);
  fForest.push_back( 
NN(
NN(
NN(
NN(
0, 
0, 
-1, 0, 1, 1, 0.533541,-99) , 
NN(
0, 
0, 
-1, 0, 1, -1, 0.489717,-99) , 
11, 252.332, 1, 0, 0.523247,-99) , 
NN(
NN(
0, 
0, 
-1, 0, 1, 1, 0.515323,-99) , 
NN(
0, 
0, 
-1, 0, 1, -1, 0.370504,-99) , 
5, 328.781, 0, 0, 0.466413,-99) , 
4, 435.762, 1, 0, 0.511714,-99) , 
NN(
NN(
NN(
0, 
0, 
-1, 0, 1, 1, 0.571808,-99) , 
NN(
0, 
0, 
-1, 0, 1, -1, 0.454337,-99) , 
13, 71.6323, 0, 0, 0.488719,-99) , 
NN(
0, 
0, 
-1, 0, 1, -1, 0.333902,-99) , 
8, 268.417, 0, 0, 0.460947,-99) , 
10, 524.883, 0, 0, 0.503008,-99)    );
  // itree = 50
  fBoostWeights.push_back(0.0379106);
  fForest.push_back( 
NN(
NN(
0, 
0, 
-1, 280.286, 1, 1, 0.554867,-99) , 
NN(
NN(
NN(
0, 
0, 
-1, 0, 1, 1, 0.59817,-99) , 
NN(
0, 
0, 
-1, 0, 1, -1, 0.494639,-99) , 
10, 1517.85, 0, 0, 0.498848,-99) , 
NN(
0, 
0, 
-1, 0, 1, -1, 0.33508,-99) , 
13, 14.6866, 0, 0, 0.493644,-99) , 
13, 124.637, 0, 0, 0.500941,-99)    );
  // itree = 51
  fBoostWeights.push_back(0.0824171);
  fForest.push_back( 
NN(
NN(
NN(
0, 
0, 
-1, 0, 1, 1, 0.640215,-99) , 
NN(
NN(
0, 
0, 
-1, 0, 1, 1, 0.562776,-99) , 
NN(
0, 
0, 
-1, 0, 1, -1, 0.471947,-99) , 
7, 368.879, 1, 0, 0.533514,-99) , 
8, 1413.75, 0, 0, 0.547315,-99) , 
NN(
NN(
NN(
0, 
0, 
-1, 0, 1, 1, 0.542747,-99) , 
NN(
0, 
0, 
-1, 0, 1, -1, 0.479749,-99) , 
9, 160.617, 0, 0, 0.50035,-99) , 
NN(
0, 
0, 
-1, 0.985807, 0, -1, 0.403912,-99) , 
4, 436.104, 1, 0, 0.490753,-99) , 
8, 784.134, 0, 0, 0.503976,-99)    );
  // itree = 52
  fBoostWeights.push_back(0.0642422);
  fForest.push_back( 
NN(
NN(
NN(
NN(
0, 
0, 
-1, 0, 1, 1, 0.521574,-99) , 
NN(
0, 
0, 
-1, 0, 1, -1, 0.404511,-99) , 
10, 402.536, 0, 0, 0.516567,-99) , 
NN(
NN(
0, 
0, 
-1, 0, 1, 1, 0.508365,-99) , 
NN(
0, 
0, 
-1, 0, 1, -1, 0.36829,-99) , 
2, 2.48271, 1, 0, 0.432927,-99) , 
11, 351.845, 1, 0, 0.510059,-99) , 
NN(
0, 
0, 
-1, 0, 1, -1, 0.388292,-99) , 
12, 0.311563, 0, 0, 0.505008,-99)    );
  // itree = 53
  fBoostWeights.push_back(0.0657206);
  fForest.push_back( 
NN(
NN(
NN(
0, 
0, 
-1, 330.004, 1, 1, 0.521907,-99) , 
NN(
NN(
0, 
0, 
-1, 0, 1, 1, 0.516043,-99) , 
NN(
0, 
0, 
-1, 0, 1, -1, 0.378896,-99) , 
1, 34.3524, 0, 0, 0.481508,-99) , 
5, 208.466, 0, 0, 0.508851,-99) , 
NN(
0, 
0, 
-1, 0, 1, -1, 0.387463,-99) , 
12, 0.329965, 0, 0, 0.502706,-99)    );
  // itree = 54
  fBoostWeights.push_back(0.0420279);
  fForest.push_back( 
NN(
NN(
NN(
NN(
0, 
0, 
-1, 0, 1, 1, 0.595935,-99) , 
NN(
0, 
0, 
-1, 0, 1, -1, 0.48409,-99) , 
9, 181.616, 1, 0, 0.553565,-99) , 
NN(
NN(
0, 
0, 
-1, 0, 1, 1, 0.55685,-99) , 
NN(
0, 
0, 
-1, 0, 1, -1, 0.496349,-99) , 
10, 1409.17, 0, 0, 0.499969,-99) , 
14, 131.458, 0, 0, 0.505531,-99) , 
NN(
NN(
NN(
0, 
0, 
-1, 0, 1, 1, 0.520381,-99) , 
NN(
0, 
0, 
-1, 0, 1, -1, 0.442791,-99) , 
14, 81.4235, 0, 0, 0.471929,-99) , 
NN(
0, 
0, 
-1, 0, 1, -1, 0.334272,-99) , 
2, 1.12484, 0, 0, 0.431417,-99) , 
13, 26.2385, 0, 0, 0.496534,-99)    );
  // itree = 55
  fBoostWeights.push_back(0.034961);
  fForest.push_back( 
NN(
NN(
NN(
0, 
0, 
-1, 52.5872, 1, 1, 0.591197,-99) , 
NN(
0, 
0, 
-1, 0.330269, 0, -1, 0.494222,-99) , 
10, 1175.23, 0, 0, 0.503022,-99) , 
NN(
0, 
0, 
-1, 65.7028, 0, -1, 0.427437,-99) , 
9, 330.305, 1, 0, 0.497972,-99)    );
  // itree = 56
  fBoostWeights.push_back(0.0489758);
  fForest.push_back( 
NN(
NN(
NN(
NN(
0, 
0, 
-1, 0, 1, 1, 0.520431,-99) , 
NN(
0, 
0, 
-1, 0, 1, -1, 0.465591,-99) , 
6, 1.70058, 0, 0, 0.515342,-99) , 
NN(
0, 
0, 
-1, 112.574, 1, -1, 0.479484,-99) , 
16, -1.66319, 0, 0, 0.505499,-99) , 
NN(
0, 
0, 
-1, 0, 1, -1, 0.412784,-99) , 
12, 0.329965, 0, 0, 0.50117,-99)    );
  // itree = 57
  fBoostWeights.push_back(0.0603572);
  fForest.push_back( 
NN(
NN(
NN(
NN(
0, 
0, 
-1, 0, 1, 1, 0.523199,-99) , 
NN(
0, 
0, 
-1, 0, 1, -1, 0.458028,-99) , 
9, 315.907, 1, 0, 0.516805,-99) , 
NN(
NN(
0, 
0, 
-1, 0, 1, 1, 0.504835,-99) , 
NN(
0, 
0, 
-1, 0, 1, -1, 0.392979,-99) , 
1, 34.3524, 0, 0, 0.476279,-99) , 
5, 208.466, 0, 0, 0.503934,-99) , 
NN(
0, 
0, 
-1, 0, 1, -1, 0.378375,-99) , 
12, 0.247131, 0, 0, 0.499648,-99)    );
  // itree = 58
  fBoostWeights.push_back(0.0555384);
  fForest.push_back( 
NN(
NN(
0, 
0, 
-1, 484.799, 1, 1, 0.563684,-99) , 
NN(
NN(
NN(
0, 
0, 
-1, 0, 1, 1, 0.515239,-99) , 
NN(
0, 
0, 
-1, 0, 1, -1, 0.432634,-99) , 
5, 531.575, 1, 0, 0.506414,-99) , 
NN(
0, 
0, 
-1, 2.84712, 1, -1, 0.463238,-99) , 
11, 218.033, 1, 0, 0.494468,-99) , 
8, 1149.02, 0, 0, 0.499001,-99)    );
  // itree = 59
  fBoostWeights.push_back(0.053238);
  fForest.push_back( 
NN(
NN(
NN(
NN(
0, 
0, 
-1, 0, 1, 1, 0.545688,-99) , 
NN(
0, 
0, 
-1, 0, 1, -1, 0.498067,-99) , 
7, 229.197, 1, 0, 0.519575,-99) , 
NN(
0, 
0, 
-1, 478.482, 1, -1, 0.475407,-99) , 
10, 700.819, 0, 0, 0.498693,-99) , 
NN(
0, 
0, 
-1, 0, 1, -1, 0.346239,-99) , 
9, 442.635, 1, 0, 0.494576,-99)    );
  // itree = 60
  fBoostWeights.push_back(0.0617692);
  fForest.push_back( 
NN(
NN(
NN(
0, 
0, 
-1, 335.027, 0, 1, 0.559938,-99) , 
NN(
0, 
0, 
-1, 0, 1, -1, 0.469351,-99) , 
7, 529.059, 1, 0, 0.546888,-99) , 
NN(
NN(
NN(
0, 
0, 
-1, 0, 1, 1, 0.510482,-99) , 
NN(
0, 
0, 
-1, 0, 1, -1, 0.424273,-99) , 
5, 483.809, 1, 0, 0.500388,-99) , 
NN(
0, 
0, 
-1, 2.996, 1, -1, 0.418711,-99) , 
11, 278.79, 1, 0, 0.49208,-99) , 
10, 1023.52, 0, 0, 0.503153,-99)    );
  // itree = 61
  fBoostWeights.push_back(0.0276386);
  fForest.push_back( 
NN(
NN(
0, 
0, 
-1, 2.22449, 0, 1, 0.58981,-99) , 
NN(
0, 
0, 
-1, 0.292988, 0, -1, 0.490605,-99) , 
10, 1451.24, 0, 0, 0.496058,-99)    );
  // itree = 62
  fBoostWeights.push_back(0.074699);
  fForest.push_back( 
NN(
NN(
NN(
0, 
0, 
-1, 0, 1, 1, 0.577954,-99) , 
NN(
NN(
0, 
0, 
-1, 0, 1, 1, 0.535718,-99) , 
NN(
0, 
0, 
-1, 0, 1, -1, 0.44754,-99) , 
5, 262.426, 0, 0, 0.518237,-99) , 
7, 215.698, 1, 0, 0.530067,-99) , 
NN(
NN(
NN(
0, 
0, 
-1, 0, 1, 1, 0.580143,-99) , 
NN(
0, 
0, 
-1, 0, 1, -1, 0.486107,-99) , 
9, 194.448, 0, 0, 0.497746,-99) , 
NN(
0, 
0, 
-1, 0.995447, 0, -1, 0.416601,-99) , 
4, 368.473, 1, 0, 0.483687,-99) , 
10, 870.029, 0, 0, 0.49878,-99)    );
  // itree = 63
  fBoostWeights.push_back(0.048245);
  fForest.push_back( 
NN(
NN(
NN(
0, 
0, 
-1, 339.855, 0, 1, 0.581263,-99) , 
NN(
0, 
0, 
-1, 0, 1, -1, 0.488389,-99) , 
9, 359.622, 1, 0, 0.554667,-99) , 
NN(
NN(
NN(
0, 
0, 
-1, 0, 1, 1, 0.508406,-99) , 
NN(
0, 
0, 
-1, 0, 1, -1, 0.421354,-99) , 
7, 336.01, 1, 0, 0.50414,-99) , 
NN(
0, 
0, 
-1, 37.9957, 0, -1, 0.437625,-99) , 
13, 27.7227, 0, 0, 0.495108,-99) , 
8, 968.228, 0, 0, 0.502649,-99)    );
  // itree = 64
  fBoostWeights.push_back(0.0562836);
  fForest.push_back( 
NN(
NN(
NN(
0, 
0, 
-1, 2.2176, 1, 1, 0.576208,-99) , 
NN(
NN(
0, 
0, 
-1, 0, 1, 1, 0.558097,-99) , 
NN(
0, 
0, 
-1, 0, 1, -1, 0.483637,-99) , 
8, 804.894, 0, 0, 0.512857,-99) , 
7, 161.277, 1, 0, 0.537038,-99) , 
NN(
NN(
NN(
0, 
0, 
-1, 0, 1, 1, 0.552366,-99) , 
NN(
0, 
0, 
-1, 0, 1, -1, 0.486583,-99) , 
5, 337.8, 0, 0, 0.529075,-99) , 
NN(
0, 
0, 
-1, 373.87, 0, -1, 0.481488,-99) , 
3, 230.86, 0, 0, 0.493797,-99) , 
14, 111.547, 0, 0, 0.501238,-99)    );
  // itree = 65
  fBoostWeights.push_back(0.0486025);
  fForest.push_back( 
NN(
NN(
NN(
0, 
0, 
-1, 763.219, 0, 1, 0.520151,-99) , 
NN(
NN(
0, 
0, 
-1, 0, 1, 1, 0.524168,-99) , 
NN(
0, 
0, 
-1, 0, 1, -1, 0.39909,-99) , 
5, 422.249, 0, 0, 0.464146,-99) , 
11, 378.601, 1, 0, 0.516536,-99) , 
NN(
0, 
0, 
-1, 286.991, 0, -1, 0.448916,-99) , 
6, 3.06615, 1, 0, 0.512964,-99)    );
  // itree = 66
  fBoostWeights.push_back(0.0576597);
  fForest.push_back( 
NN(
NN(
NN(
0, 
0, 
-1, 2.30864, 0, 1, 0.520496,-99) , 
NN(
NN(
0, 
0, 
-1, 0, 1, 1, 0.51335,-99) , 
NN(
0, 
0, 
-1, 0, 1, -1, 0.394625,-99) , 
3, 188.238, 0, 0, 0.476055,-99) , 
4, 416.121, 1, 0, 0.512154,-99) , 
NN(
NN(
NN(
0, 
0, 
-1, 0, 1, 1, 0.521017,-99) , 
NN(
0, 
0, 
-1, 0, 1, -1, 0.440619,-99) , 
0, 118.226, 1, 0, 0.480501,-99) , 
NN(
0, 
0, 
-1, 0, 1, -1, 0.377068,-99) , 
12, 0.480936, 0, 0, 0.455241,-99) , 
2, 1.008, 0, 0, 0.505476,-99)    );
  // itree = 67
  fBoostWeights.push_back(0.0484867);
  fForest.push_back( 
NN(
NN(
NN(
NN(
0, 
0, 
-1, 0, 1, 1, 0.523467,-99) , 
NN(
0, 
0, 
-1, 0, 1, -1, 0.483576,-99) , 
15, 142.738, 0, 0, 0.500876,-99) , 
NN(
0, 
0, 
-1, 950.38, 0, -1, 0.44324,-99) , 
15, 361.507, 1, 0, 0.497184,-99) , 
NN(
0, 
0, 
-1, 0, 1, -1, 0.428106,-99) , 
12, 0.330269, 0, 0, 0.493928,-99)    );
  // itree = 68
  fBoostWeights.push_back(0.042167);
  fForest.push_back( 
NN(
NN(
NN(
0, 
0, 
-1, 1447.91, 0, 1, 0.565299,-99) , 
NN(
0, 
0, 
-1, 0, 1, -1, 0.485684,-99) , 
7, 545.944, 1, 0, 0.5485,-99) , 
NN(
NN(
NN(
0, 
0, 
-1, 0, 1, 1, 0.506186,-99) , 
NN(
0, 
0, 
-1, 0, 1, -1, 0.393672,-99) , 
11, 384.635, 1, 0, 0.501958,-99) , 
NN(
0, 
0, 
-1, 0, 1, -1, 0.368671,-99) , 
8, 290.752, 0, 0, 0.495014,-99) , 
8, 968.228, 0, 0, 0.50172,-99)    );
  // itree = 69
  fBoostWeights.push_back(0.0472342);
  fForest.push_back( 
NN(
NN(
0, 
0, 
-1, 0, 1, 1, 0.561093,-99) , 
NN(
NN(
NN(
0, 
0, 
-1, 0, 1, 1, 0.507968,-99) , 
NN(
0, 
0, 
-1, 0, 1, -1, 0.419372,-99) , 
4, 743.612, 1, 0, 0.502638,-99) , 
NN(
0, 
0, 
-1, 380.693, 1, -1, 0.470288,-99) , 
8, 583.058, 0, 0, 0.48516,-99) , 
14, 157.749, 0, 0, 0.488776,-99)    );
  // itree = 70
  fBoostWeights.push_back(0.0447625);
  fForest.push_back( 
NN(
NN(
NN(
NN(
0, 
0, 
-1, 0, 1, 1, 0.517488,-99) , 
NN(
0, 
0, 
-1, 0, 1, -1, 0.48995,-99) , 
5, 208.466, 0, 0, 0.508746,-99) , 
NN(
NN(
0, 
0, 
-1, 0, 1, 1, 0.501308,-99) , 
NN(
0, 
0, 
-1, 0, 1, -1, 0.364138,-99) , 
12, 0.361154, 0, 0, 0.444494,-99) , 
13, 22.618, 0, 0, 0.503223,-99) , 
NN(
NN(
NN(
0, 
0, 
-1, 0, 1, 1, 0.503986,-99) , 
NN(
0, 
0, 
-1, 0, 1, -1, 0.44436,-99) , 
2, 2.6979, 1, 0, 0.478718,-99) , 
NN(
0, 
0, 
-1, 0, 1, -1, 0.387143,-99) , 
10, 636.086, 0, 0, 0.448657,-99) , 
16, 2.64878, 1, 0, 0.497664,-99)    );
  // itree = 71
  fBoostWeights.push_back(0.0617301);
  fForest.push_back( 
NN(
NN(
NN(
0, 
0, 
-1, 0, 1, 1, 0.581858,-99) , 
NN(
NN(
0, 
0, 
-1, 0, 1, 1, 0.542067,-99) , 
NN(
0, 
0, 
-1, 0, 1, -1, 0.476107,-99) , 
9, 292.236, 1, 0, 0.521225,-99) , 
8, 1397.7, 0, 0, 0.531728,-99) , 
NN(
NN(
NN(
0, 
0, 
-1, 0, 1, 1, 0.510874,-99) , 
NN(
0, 
0, 
-1, 0, 1, -1, 0.411833,-99) , 
7, 297.241, 1, 0, 0.504502,-99) , 
NN(
0, 
0, 
-1, 0.729971, 0, -1, 0.437152,-99) , 
1, 37.9957, 0, 0, 0.487169,-99) , 
8, 865.397, 0, 0, 0.495066,-99)    );
  // itree = 72
  fBoostWeights.push_back(0.0437947);
  fForest.push_back( 
NN(
NN(
NN(
0, 
0, 
-1, 308.609, 1, 1, 0.521901,-99) , 
NN(
0, 
0, 
-1, 299.502, 0, -1, 0.488024,-99) , 
6, 2.35435, 0, 0, 0.500988,-99) , 
NN(
NN(
NN(
0, 
0, 
-1, 0, 1, 1, 0.52212,-99) , 
NN(
0, 
0, 
-1, 0, 1, -1, 0.455156,-99) , 
6, 2.68086, 1, 0, 0.493391,-99) , 
NN(
0, 
0, 
-1, 0, 1, -1, 0.401119,-99) , 
3, 188.238, 0, 0, 0.467317,-99) , 
4, 431.55, 1, 0, 0.495116,-99)    );
  // itree = 73
  fBoostWeights.push_back(0.0374952);
  fForest.push_back( 
NN(
NN(
NN(
0, 
0, 
-1, 0, 1, 1, 0.593322,-99) , 
NN(
NN(
0, 
0, 
-1, 0, 1, 1, 0.555696,-99) , 
NN(
0, 
0, 
-1, 0, 1, -1, 0.471002,-99) , 
4, 547.757, 1, 0, 0.517231,-99) , 
9, 238.222, 1, 0, 0.550795,-99) , 
NN(
0, 
0, 
-1, 309.29, 1, -1, 0.487616,-99) , 
10, 1193.06, 0, 0, 0.495172,-99)    );
  // itree = 74
  fBoostWeights.push_back(0.024698);
  fForest.push_back( 
NN(
NN(
NN(
0, 
0, 
-1, 1178.24, 0, 1, 0.507686,-99) , 
NN(
0, 
0, 
-1, 0, 1, -1, 0.41919,-99) , 
4, 756.66, 1, 0, 0.505141,-99) , 
NN(
0, 
0, 
-1, 0, 1, -1, 0.436662,-99) , 
6, 1.44576, 0, 0, 0.501871,-99)    );
  // itree = 75
  fBoostWeights.push_back(0.0373115);
  fForest.push_back( 
NN(
NN(
NN(
0, 
0, 
-1, 0, 1, 1, 0.560465,-99) , 
NN(
NN(
0, 
0, 
-1, 0, 1, 1, 0.544216,-99) , 
NN(
0, 
0, 
-1, 0, 1, -1, 0.487343,-99) , 
13, 52.4624, 0, 0, 0.517653,-99) , 
1, 64.663, 1, 0, 0.53017,-99) , 
NN(
0, 
0, 
-1, 258.493, 0, -1, 0.485606,-99) , 
8, 865.397, 0, 0, 0.493457,-99)    );
  // itree = 76
  fBoostWeights.push_back(0.0470298);
  fForest.push_back( 
NN(
NN(
NN(
NN(
0, 
0, 
-1, 0, 1, 1, 0.51735,-99) , 
NN(
0, 
0, 
-1, 0, 1, -1, 0.479984,-99) , 
2, 1.08466, 0, 0, 0.510966,-99) , 
NN(
0, 
0, 
-1, 256.338, 1, -1, 0.464,-99) , 
2, 3.06702, 1, 0, 0.503191,-99) , 
NN(
0, 
0, 
-1, 0.0613614, 0, -1, 0.429365,-99) , 
6, 3.06615, 1, 0, 0.49922,-99)    );
  // itree = 77
  fBoostWeights.push_back(0.0765619);
  fForest.push_back( 
NN(
NN(
NN(
NN(
0, 
0, 
-1, 0, 1, 1, 0.527445,-99) , 
NN(
0, 
0, 
-1, 0, 1, -1, 0.476098,-99) , 
1, 2.22378, 0, 0, 0.514884,-99) , 
NN(
NN(
0, 
0, 
-1, 0, 1, 1, 0.555145,-99) , 
NN(
0, 
0, 
-1, 0, 1, -1, 0.455812,-99) , 
0, 181.845, 0, 0, 0.476433,-99) , 
1, 113.414, 1, 0, 0.50396,-99) , 
NN(
NN(
NN(
0, 
0, 
-1, 0, 1, 1, 0.536787,-99) , 
NN(
0, 
0, 
-1, 0, 1, -1, 0.417518,-99) , 
2, 1.5745, 0, 0, 0.500769,-99) , 
NN(
0, 
0, 
-1, 0, 1, -1, 0.356294,-99) , 
8, 366.767, 0, 0, 0.454747,-99) , 
4, 155.776, 0, 0, 0.497833,-99)    );
  // itree = 78
  fBoostWeights.push_back(0.0454717);
  fForest.push_back( 
NN(
NN(
NN(
0, 
0, 
-1, 149.669, 1, 1, 0.510846,-99) , 
NN(
NN(
0, 
0, 
-1, 0, 1, 1, 0.501615,-99) , 
NN(
0, 
0, 
-1, 0, 1, -1, 0.379392,-99) , 
8, 610.273, 0, 0, 0.463914,-99) , 
5, 490.153, 1, 0, 0.504442,-99) , 
NN(
NN(
NN(
0, 
0, 
-1, 0, 1, 1, 0.544573,-99) , 
NN(
0, 
0, 
-1, 0, 1, -1, 0.462614,-99) , 
13, 42.1964, 0, 0, 0.517151,-99) , 
NN(
0, 
0, 
-1, 2.43943, 1, -1, 0.420807,-99) , 
5, 414.435, 0, 0, 0.47276,-99) , 
4, 424.129, 1, 0, 0.498675,-99)    );
  // itree = 79
  fBoostWeights.push_back(0.0344363);
  fForest.push_back( 
NN(
NN(
NN(
0, 
0, 
-1, 0, 1, 1, 0.56944,-99) , 
NN(
0, 
0, 
-1, 3.58295, 1, -1, 0.493804,-99) , 
7, 95.8456, 1, 0, 0.497813,-99) , 
NN(
NN(
NN(
0, 
0, 
-1, 0, 1, 1, 0.528265,-99) , 
NN(
0, 
0, 
-1, 0, 1, -1, 0.45819,-99) , 
2, 2.36007, 0, 0, 0.48733,-99) , 
NN(
0, 
0, 
-1, 0, 1, -1, 0.356862,-99) , 
10, 528.784, 0, 0, 0.442888,-99) , 
4, 155.776, 0, 0, 0.491138,-99)    );
  // itree = 80
  fBoostWeights.push_back(0.0485621);
  fForest.push_back( 
NN(
NN(
NN(
NN(
0, 
0, 
-1, 0, 1, 1, 0.513912,-99) , 
NN(
0, 
0, 
-1, 0, 1, -1, 0.484211,-99) , 
2, 2.6039, 1, 0, 0.502355,-99) , 
NN(
0, 
0, 
-1, 1.95032, 0, -1, 0.452584,-99) , 
6, 2.88135, 1, 0, 0.496992,-99) , 
NN(
NN(
NN(
0, 
0, 
-1, 0, 1, 1, 0.512478,-99) , 
NN(
0, 
0, 
-1, 0, 1, -1, 0.408459,-99) , 
4, 113.681, 0, 0, 0.485733,-99) , 
NN(
0, 
0, 
-1, 0, 1, -1, 0.309454,-99) , 
1, 35.4776, 0, 0, 0.448224,-99) , 
4, 155.776, 0, 0, 0.490832,-99)    );
  // itree = 81
  fBoostWeights.push_back(0.0468998);
  fForest.push_back( 
NN(
NN(
NN(
0, 
0, 
-1, 457.07, 1, 1, 0.53426,-99) , 
NN(
0, 
0, 
-1, 0, 1, -1, 0.488723,-99) , 
4, 289.139, 0, 0, 0.526619,-99) , 
NN(
NN(
NN(
0, 
0, 
-1, 0, 1, 1, 0.508916,-99) , 
NN(
0, 
0, 
-1, 0, 1, -1, 0.40784,-99) , 
8, 302.559, 0, 0, 0.50026,-99) , 
NN(
0, 
0, 
-1, 137.31, 0, -1, 0.4489,-99) , 
5, 471.38, 1, 0, 0.492939,-99) , 
3, 232.029, 0, 0, 0.50154,-99)    );
  // itree = 82
  fBoostWeights.push_back(0.0308923);
  fForest.push_back( 
NN(
NN(
0, 
0, 
-1, 0, 1, 1, 0.55401,-99) , 
NN(
NN(
NN(
0, 
0, 
-1, 0, 1, 1, 0.574797,-99) , 
NN(
0, 
0, 
-1, 0, 1, -1, 0.493381,-99) , 
12, 1.89335, 0, 0, 0.496225,-99) , 
NN(
0, 
0, 
-1, 111.864, 0, -1, 0.445365,-99) , 
4, 144.04, 0, 0, 0.491183,-99) , 
14, 157.75, 0, 0, 0.494158,-99)    );
  // itree = 83
  fBoostWeights.push_back(0.0412641);
  fForest.push_back( 
NN(
NN(
NN(
NN(
0, 
0, 
-1, 0, 1, 1, 0.55921,-99) , 
NN(
0, 
0, 
-1, 0, 1, -1, 0.482271,-99) , 
2, 1.23569, 0, 0, 0.540332,-99) , 
NN(
NN(
0, 
0, 
-1, 0, 1, 1, 0.507136,-99) , 
NN(
0, 
0, 
-1, 0, 1, -1, 0.424758,-99) , 
5, 205.02, 0, 0, 0.493826,-99) , 
0, 140.672, 0, 0, 0.514879,-99) , 
NN(
0, 
0, 
-1, 18.5644, 0, -1, 0.484988,-99) , 
10, 869.527, 0, 0, 0.494784,-99)    );
  // itree = 84
  fBoostWeights.push_back(0.0283289);
  fForest.push_back( 
NN(
NN(
NN(
0, 
0, 
-1, 2.45025, 1, 1, 0.534257,-99) , 
NN(
NN(
0, 
0, 
-1, 0, 1, 1, 0.501402,-99) , 
NN(
0, 
0, 
-1, 0, 1, -1, 0.416621,-99) , 
10, 414.366, 0, 0, 0.496993,-99) , 
3, 233.19, 0, 0, 0.50594,-99) , 
NN(
0, 
0, 
-1, 0, 1, -1, 0.427158,-99) , 
4, 759.569, 1, 0, 0.503808,-99)    );
  // itree = 85
  fBoostWeights.push_back(0.0423399);
  fForest.push_back( 
NN(
NN(
NN(
0, 
0, 
-1, 122.502, 1, 1, 0.573782,-99) , 
NN(
NN(
0, 
0, 
-1, 0, 1, 1, 0.525912,-99) , 
NN(
0, 
0, 
-1, 0, 1, -1, 0.454168,-99) , 
9, 182.852, 1, 0, 0.49536,-99) , 
12, 1.12142, 0, 0, 0.541767,-99) , 
NN(
0, 
0, 
-1, 14.4043, 0, -1, 0.486787,-99) , 
13, 104.779, 0, 0, 0.496604,-99)    );
  // itree = 86
  fBoostWeights.push_back(0.0425319);
  fForest.push_back( 
NN(
NN(
0, 
0, 
-1, 487.493, 1, 1, 0.560428,-99) , 
NN(
NN(
NN(
0, 
0, 
-1, 0, 1, 1, 0.509908,-99) , 
NN(
0, 
0, 
-1, 0, 1, -1, 0.407081,-99) , 
8, 283.288, 0, 0, 0.504928,-99) , 
NN(
0, 
0, 
-1, 135.777, 0, -1, 0.453442,-99) , 
5, 528.203, 1, 0, 0.497883,-99) , 
8, 1149.02, 0, 0, 0.502139,-99)    );
  // itree = 87
  fBoostWeights.push_back(0.0424783);
  fForest.push_back( 
NN(
NN(
NN(
NN(
0, 
0, 
-1, 0, 1, 1, 0.514261,-99) , 
NN(
0, 
0, 
-1, 0, 1, -1, 0.423549,-99) , 
6, 3.07547, 1, 0, 0.509565,-99) , 
NN(
0, 
0, 
-1, 225.645, 0, -1, 0.475758,-99) , 
11, 218.033, 1, 0, 0.499799,-99) , 
NN(
0, 
0, 
-1, 0, 1, -1, 0.416072,-99) , 
12, 0.247131, 0, 0, 0.497472,-99)    );
  // itree = 88
  fBoostWeights.push_back(0.043779);
  fForest.push_back( 
NN(
NN(
NN(
0, 
0, 
-1, 1.74818, 1, 1, 0.577717,-99) , 
NN(
NN(
0, 
0, 
-1, 0, 1, 1, 0.527512,-99) , 
NN(
0, 
0, 
-1, 0, 1, -1, 0.463038,-99) , 
11, 142.677, 1, 0, 0.505807,-99) , 
13, 101.364, 0, 0, 0.535296,-99) , 
NN(
NN(
NN(
0, 
0, 
-1, 0, 1, 1, 0.559882,-99) , 
NN(
0, 
0, 
-1, 0, 1, -1, 0.490538,-99) , 
2, 1.26827, 0, 0, 0.538432,-99) , 
NN(
0, 
0, 
-1, 0.291502, 0, -1, 0.486858,-99) , 
10, 1192.59, 0, 0, 0.493752,-99) , 
12, 1.48198, 0, 0, 0.499563,-99)    );
  // itree = 89
  fBoostWeights.push_back(0.0521123);
  fForest.push_back( 
NN(
NN(
NN(
0, 
0, 
-1, 0, 1, 1, 0.591768,-99) , 
NN(
NN(
0, 
0, 
-1, 0, 1, 1, 0.529052,-99) , 
NN(
0, 
0, 
-1, 0, 1, -1, 0.493715,-99) , 
9, 193.027, 0, 0, 0.507738,-99) , 
10, 438.773, 1, 0, 0.511253,-99) , 
NN(
NN(
NN(
0, 
0, 
-1, 0, 1, 1, 0.515942,-99) , 
NN(
0, 
0, 
-1, 0, 1, -1, 0.4199,-99) , 
1, 25.8836, 0, 0, 0.494158,-99) , 
NN(
0, 
0, 
-1, 2.13539, 1, -1, 0.423404,-99) , 
7, 189.577, 1, 0, 0.475077,-99) , 
5, 208.466, 0, 0, 0.500115,-99)    );
  // itree = 90
  fBoostWeights.push_back(0.0638708);
  fForest.push_back( 
NN(
NN(
NN(
0, 
0, 
-1, 362.722, 1, 1, 0.52712,-99) , 
NN(
NN(
0, 
0, 
-1, 0, 1, 1, 0.520185,-99) , 
NN(
0, 
0, 
-1, 0, 1, -1, 0.464816,-99) , 
4, 207.754, 0, 0, 0.479799,-99) , 
4, 235.273, 0, 0, 0.512456,-99) , 
NN(
NN(
NN(
0, 
0, 
-1, 0, 1, 1, 0.510988,-99) , 
NN(
0, 
0, 
-1, 0, 1, -1, 0.393859,-99) , 
11, 255.067, 1, 0, 0.492494,-99) , 
NN(
0, 
0, 
-1, 0, 1, -1, 0.355301,-99) , 
8, 307.093, 0, 0, 0.476611,-99) , 
5, 208.466, 0, 0, 0.501346,-99)    );
  // itree = 91
  fBoostWeights.push_back(0.0343607);
  fForest.push_back( 
NN(
NN(
NN(
NN(
0, 
0, 
-1, 0, 1, 1, 0.543481,-99) , 
NN(
0, 
0, 
-1, 0, 1, -1, 0.495398,-99) , 
0, 70.2407, 1, 0, 0.505821,-99) , 
NN(
0, 
0, 
-1, 0, 1, -1, 0.434972,-99) , 
12, 0.324472, 0, 0, 0.503203,-99) , 
NN(
0, 
0, 
-1, 419.903, 0, -1, 0.450397,-99) , 
11, 378.328, 1, 0, 0.499815,-99)    );
  // itree = 92
  fBoostWeights.push_back(0.064105);
  fForest.push_back( 
NN(
NN(
NN(
0, 
0, 
-1, 0, 1, 1, 0.572437,-99) , 
NN(
NN(
0, 
0, 
-1, 0, 1, 1, 0.517917,-99) , 
NN(
0, 
0, 
-1, 0, 1, -1, 0.473141,-99) , 
10, 692.281, 0, 0, 0.504012,-99) , 
8, 330.004, 1, 0, 0.508135,-99) , 
NN(
NN(
NN(
0, 
0, 
-1, 0, 1, 1, 0.521042,-99) , 
NN(
0, 
0, 
-1, 0, 1, -1, 0.415609,-99) , 
11, 197.658, 1, 0, 0.490788,-99) , 
NN(
0, 
0, 
-1, 0, 1, -1, 0.359261,-99) , 
8, 303.435, 0, 0, 0.476242,-99) , 
5, 208.466, 0, 0, 0.49832,-99)    );
  // itree = 93
  fBoostWeights.push_back(0.0602642);
  fForest.push_back( 
NN(
NN(
NN(
NN(
0, 
0, 
-1, 0, 1, 1, 0.516929,-99) , 
NN(
0, 
0, 
-1, 0, 1, -1, 0.462151,-99) , 
15, 354.253, 1, 0, 0.512522,-99) , 
NN(
0, 
0, 
-1, 0, 1, -1, 0.435893,-99) , 
6, 3.06324, 1, 0, 0.507846,-99) , 
NN(
NN(
NN(
0, 
0, 
-1, 0, 1, 1, 0.542983,-99) , 
NN(
0, 
0, 
-1, 0, 1, -1, 0.459124,-99) , 
5, 153.231, 1, 0, 0.486556,-99) , 
NN(
0, 
0, 
-1, 0, 1, -1, 0.382456,-99) , 
8, 303.435, 0, 0, 0.475324,-99) , 
5, 208.466, 0, 0, 0.497866,-99)    );
  // itree = 94
  fBoostWeights.push_back(0.0317572);
  fForest.push_back( 
NN(
NN(
NN(
0, 
0, 
-1, 0, 1, 1, 0.574436,-99) , 
NN(
NN(
0, 
0, 
-1, 0, 1, 1, 0.534505,-99) , 
NN(
0, 
0, 
-1, 0, 1, -1, 0.476533,-99) , 
0, 173.625, 1, 0, 0.506789,-99) , 
9, 259.946, 1, 0, 0.539623,-99) , 
NN(
NN(
NN(
0, 
0, 
-1, 0, 1, 1, 0.501866,-99) , 
NN(
0, 
0, 
-1, 0, 1, -1, 0.435019,-99) , 
7, 316.484, 1, 0, 0.496763,-99) , 
NN(
NN(
0, 
0, 
-1, 0, 1, 1, 0.50419,-99) , 
NN(
0, 
0, 
-1, 0, 1, -1, 0.32195,-99) , 
12, 0.354044, 0, 0, 0.436786,-99) , 
13, 22.5439, 0, 0, 0.491848,-99) , 
10, 1246.08, 0, 0, 0.496846,-99)    );
  // itree = 95
  fBoostWeights.push_back(0.0241818);
  fForest.push_back( 
NN(
NN(
0, 
0, 
-1, 0, 1, 1, 0.553415,-99) , 
NN(
0, 
0, 
-1, 417.864, 1, -1, 0.489853,-99) , 
10, 1523.6, 0, 0, 0.492704,-99)    );
  // itree = 96
  fBoostWeights.push_back(0.032936);
  fForest.push_back( 
NN(
NN(
NN(
NN(
0, 
0, 
-1, 0, 1, 1, 0.507896,-99) , 
NN(
0, 
0, 
-1, 0, 1, -1, 0.467016,-99) , 
11, 70.2263, 0, 0, 0.50157,-99) , 
NN(
0, 
0, 
-1, 0, 1, -1, 0.413171,-99) , 
11, 445.859, 1, 0, 0.498985,-99) , 
NN(
0, 
0, 
-1, 0, 1, -1, 0.429166,-99) , 
12, 0.330155, 0, 0, 0.495929,-99)    );
  // itree = 97
  fBoostWeights.push_back(0.0313481);
  fForest.push_back( 
NN(
NN(
NN(
0, 
0, 
-1, 0, 1, 1, 0.54642,-99) , 
NN(
0, 
0, 
-1, 279.93, 0, -1, 0.487908,-99) , 
10, 1369.65, 0, 0, 0.490976,-99) , 
NN(
0, 
0, 
-1, 0, 1, -1, 0.42082,-99) , 
9, 436.431, 1, 0, 0.489067,-99)    );
  // itree = 98
  fBoostWeights.push_back(0.037973);
  fForest.push_back( 
NN(
NN(
0, 
0, 
-1, 0, 1, 1, 0.555417,-99) , 
NN(
NN(
NN(
0, 
0, 
-1, 0, 1, 1, 0.508141,-99) , 
NN(
0, 
0, 
-1, 0, 1, -1, 0.452387,-99) , 
4, 127.862, 0, 0, 0.504219,-99) , 
NN(
NN(
0, 
0, 
-1, 0, 1, 1, 0.508478,-99) , 
NN(
0, 
0, 
-1, 0, 1, -1, 0.411072,-99) , 
8, 968.37, 0, 0, 0.44366,-99) , 
4, 473.216, 1, 0, 0.497723,-99) , 
0, 264.363, 0, 0, 0.501536,-99)    );
  // itree = 99
  fBoostWeights.push_back(0.0503181);
  fForest.push_back( 
NN(
NN(
NN(
NN(
0, 
0, 
-1, 0, 1, 1, 0.512071,-99) , 
NN(
0, 
0, 
-1, 0, 1, -1, 0.4259,-99) , 
13, 18.5644, 0, 0, 0.508535,-99) , 
NN(
0, 
0, 
-1, 0, 1, -1, 0.391592,-99) , 
8, 268.394, 0, 0, 0.503937,-99) , 
NN(
NN(
NN(
0, 
0, 
-1, 0, 1, 1, 0.522375,-99) , 
NN(
0, 
0, 
-1, 0, 1, -1, 0.459657,-99) , 
0, 101.867, 0, 0, 0.507114,-99) , 
NN(
0, 
0, 
-1, 1095.04, 0, -1, 0.441441,-99) , 
3, 180.556, 0, 0, 0.478684,-99) , 
7, 238.015, 1, 0, 0.496168,-99)    );
  // itree = 100
  fBoostWeights.push_back(0.0438705);
  fForest.push_back( 
NN(
NN(
NN(
0, 
0, 
-1, 2.39524, 0, 1, 0.547007,-99) , 
NN(
0, 
0, 
-1, 182.852, 1, -1, 0.469361,-99) , 
12, 1.04256, 0, 0, 0.521576,-99) , 
NN(
NN(
NN(
0, 
0, 
-1, 0, 1, 1, 0.58892,-99) , 
NN(
0, 
0, 
-1, 0, 1, -1, 0.488715,-99) , 
12, 0.392189, 1, 0, 0.493054,-99) , 
NN(
0, 
0, 
-1, 0, 1, -1, 0.428478,-99) , 
13, 18.5362, 0, 0, 0.489535,-99) , 
13, 104.801, 0, 0, 0.495133,-99)    );
  // itree = 101
  fBoostWeights.push_back(0.0600536);
  fForest.push_back( 
NN(
NN(
NN(
NN(
0, 
0, 
-1, 0, 1, 1, 0.534877,-99) , 
NN(
0, 
0, 
-1, 0, 1, -1, 0.482674,-99) , 
4, 158.195, 0, 0, 0.520126,-99) , 
NN(
NN(
0, 
0, 
-1, 0, 1, 1, 0.518129,-99) , 
NN(
0, 
0, 
-1, 0, 1, -1, 0.469532,-99) , 
3, 224.667, 0, 0, 0.48486,-99) , 
0, 74.7146, 1, 0, 0.493354,-99) , 
NN(
0, 
0, 
-1, 0, 1, -1, 0.410834,-99) , 
12, 0.32942, 0, 0, 0.489869,-99)    );
  // itree = 102
  fBoostWeights.push_back(0.0425623);
  fForest.push_back( 
NN(
NN(
NN(
NN(
0, 
0, 
-1, 0, 1, 1, 0.512739,-99) , 
NN(
0, 
0, 
-1, 0, 1, -1, 0.483873,-99) , 
16, -2.20671, 0, 0, 0.50601,-99) , 
NN(
NN(
0, 
0, 
-1, 0, 1, 1, 0.523294,-99) , 
NN(
0, 
0, 
-1, 0, 1, -1, 0.449962,-99) , 
10, 954.855, 0, 0, 0.469106,-99) , 
13, 27.6988, 0, 0, 0.500832,-99) , 
NN(
0, 
0, 
-1, 175.484, 0, -1, 0.464314,-99) , 
16, 2.15599, 1, 0, 0.493541,-99)    );
  // itree = 103
  fBoostWeights.push_back(0.0369556);
  fForest.push_back( 
NN(
NN(
NN(
NN(
0, 
0, 
-1, 0, 1, 1, 0.509584,-99) , 
NN(
0, 
0, 
-1, 0, 1, -1, 0.473034,-99) , 
5, 176.742, 0, 0, 0.502341,-99) , 
NN(
0, 
0, 
-1, 0, 1, -1, 0.432473,-99) , 
2, 3.55899, 1, 0, 0.499254,-99) , 
NN(
0, 
0, 
-1, 0.55752, 0, -1, 0.44803,-99) , 
2, 0.840566, 0, 0, 0.495002,-99)    );
  // itree = 104
  fBoostWeights.push_back(0.031549);
  fForest.push_back( 
NN(
NN(
NN(
NN(
0, 
0, 
-1, 0, 1, 1, 0.540843,-99) , 
NN(
0, 
0, 
-1, 0, 1, -1, 0.49656,-99) , 
8, 815.97, 0, 0, 0.503399,-99) , 
NN(
NN(
0, 
0, 
-1, 0, 1, 1, 0.518556,-99) , 
NN(
0, 
0, 
-1, 0, 1, -1, 0.419582,-99) , 
0, 190.524, 0, 0, 0.460249,-99) , 
9, 300.555, 1, 0, 0.499445,-99) , 
NN(
0, 
0, 
-1, 0, 1, -1, 0.435353,-99) , 
6, 1.44576, 0, 0, 0.496496,-99)    );
  // itree = 105
  fBoostWeights.push_back(0.036323);
  fForest.push_back( 
NN(
NN(
NN(
NN(
0, 
0, 
-1, 0, 1, 1, 0.506372,-99) , 
NN(
0, 
0, 
-1, 0, 1, -1, 0.466953,-99) , 
2, 3.1346, 1, 0, 0.501213,-99) , 
NN(
NN(
0, 
0, 
-1, 0, 1, 1, 0.530076,-99) , 
NN(
0, 
0, 
-1, 0, 1, -1, 0.421269,-99) , 
6, 2.41198, 0, 0, 0.470871,-99) , 
10, 509.85, 0, 0, 0.496888,-99) , 
NN(
0, 
0, 
-1, 0, 1, -1, 0.421541,-99) , 
9, 436.838, 1, 0, 0.494898,-99)    );
  // itree = 106
  fBoostWeights.push_back(0.0259427);
  fForest.push_back( 
NN(
NN(
NN(
0, 
0, 
-1, 0, 1, 1, 0.556848,-99) , 
NN(
0, 
0, 
-1, 0.329965, 0, -1, 0.491638,-99) , 
10, 1357.47, 0, 0, 0.495057,-99) , 
NN(
0, 
0, 
-1, 0, 1, -1, 0.414575,-99) , 
7, 553.773, 1, 0, 0.492827,-99)    );
  // itree = 107
  fBoostWeights.push_back(0.037769);
  fForest.push_back( 
NN(
NN(
NN(
NN(
0, 
0, 
-1, 0, 1, 1, 0.616748,-99) , 
NN(
0, 
0, 
-1, 0, 1, -1, 0.464898,-99) , 
6, 2.33915, 0, 0, 0.549454,-99) , 
NN(
NN(
0, 
0, 
-1, 0, 1, 1, 0.568664,-99) , 
NN(
0, 
0, 
-1, 0, 1, -1, 0.490539,-99) , 
12, 1.8934, 0, 0, 0.493418,-99) , 
9, 71.3252, 1, 0, 0.497118,-99) , 
NN(
0, 
0, 
-1, 0.652713, 1, -1, 0.440676,-99) , 
11, 378.328, 1, 0, 0.493609,-99)    );
  // itree = 108
  fBoostWeights.push_back(0.0393071);
  fForest.push_back( 
NN(
NN(
NN(
NN(
0, 
0, 
-1, 0, 1, 1, 0.513448,-99) , 
NN(
0, 
0, 
-1, 0, 1, -1, 0.418133,-99) , 
6, 1.35442, 0, 0, 0.510689,-99) , 
NN(
0, 
0, 
-1, 0, 1, -1, 0.436399,-99) , 
0, 43.1107, 0, 0, 0.507118,-99) , 
NN(
0, 
0, 
-1, 0, 1, -1, 0.414491,-99) , 
4, 759.569, 1, 0, 0.504522,-99)    );
  // itree = 109
  fBoostWeights.push_back(0.0254124);
  fForest.push_back( 
NN(
NN(
NN(
0, 
0, 
-1, 0, 1, 1, 0.583433,-99) , 
NN(
NN(
0, 
0, 
-1, 0, 1, 1, 0.535894,-99) , 
NN(
0, 
0, 
-1, 0, 1, -1, 0.478922,-99) , 
14, 46.7883, 1, 0, 0.507508,-99) , 
14, 82.2746, 0, 0, 0.536982,-99) , 
NN(
NN(
NN(
0, 
0, 
-1, 0, 1, 1, 0.501891,-99) , 
NN(
0, 
0, 
-1, 0, 1, -1, 0.455263,-99) , 
3, 68.139, 0, 0, 0.497716,-99) , 
NN(
0, 
0, 
-1, 0.36454, 0, -1, 0.445814,-99) , 
13, 21.0496, 0, 0, 0.494012,-99) , 
12, 1.64605, 0, 0, 0.49773,-99)    );
  // itree = 110
  fBoostWeights.push_back(0.0436952);
  fForest.push_back( 
NN(
NN(
NN(
0, 
0, 
-1, 140.781, 0, 1, 0.519311,-99) , 
NN(
NN(
0, 
0, 
-1, 0, 1, 1, 0.508324,-99) , 
NN(
0, 
0, 
-1, 0, 1, -1, 0.454176,-99) , 
4, 238.927, 0, 0, 0.490761,-99) , 
2, 1.79346, 0, 0, 0.508813,-99) , 
NN(
NN(
NN(
0, 
0, 
-1, 0, 1, 1, 0.503235,-99) , 
NN(
0, 
0, 
-1, 0, 1, -1, 0.401364,-99) , 
8, 302.832, 0, 0, 0.490834,-99) , 
NN(
0, 
0, 
-1, 0, 1, -1, 0.393363,-99) , 
4, 383.291, 1, 0, 0.478399,-99) , 
5, 208.466, 0, 0, 0.499485,-99)    );
  // itree = 111
  fBoostWeights.push_back(0.0464656);
  fForest.push_back( 
NN(
NN(
NN(
NN(
0, 
0, 
-1, 0, 1, 1, 0.53447,-99) , 
NN(
0, 
0, 
-1, 0, 1, -1, 0.497347,-99) , 
0, 124.003, 0, 0, 0.517525,-99) , 
NN(
0, 
0, 
-1, 0, 1, -1, 0.46456,-99) , 
7, 503.014, 1, 0, 0.510497,-99) , 
NN(
NN(
NN(
0, 
0, 
-1, 0, 1, 1, 0.530641,-99) , 
NN(
0, 
0, 
-1, 0, 1, -1, 0.481495,-99) , 
8, 339.138, 1, 0, 0.4887,-99) , 
NN(
0, 
0, 
-1, 0, 1, -1, 0.384166,-99) , 
12, 0.329965, 0, 0, 0.485028,-99) , 
8, 762.566, 0, 0, 0.491634,-99)    );
  // itree = 112
  fBoostWeights.push_back(0.0258341);
  fForest.push_back( 
NN(
NN(
NN(
0, 
0, 
-1, 0, 1, 1, 0.560007,-99) , 
NN(
NN(
0, 
0, 
-1, 0, 1, 1, 0.501612,-99) , 
NN(
0, 
0, 
-1, 0, 1, -1, 0.46844,-99) , 
2, 1.00699, 0, 0, 0.497691,-99) , 
14, 157.749, 0, 0, 0.500492,-99) , 
NN(
NN(
NN(
0, 
0, 
-1, 0, 1, 1, 0.524849,-99) , 
NN(
0, 
0, 
-1, 0, 1, -1, 0.451342,-99) , 
5, 463.291, 0, 0, 0.497146,-99) , 
NN(
0, 
0, 
-1, 0, 1, -1, 0.417984,-99) , 
8, 796.066, 0, 0, 0.466286,-99) , 
4, 499.181, 1, 0, 0.496466,-99)    );
  // itree = 113
  fBoostWeights.push_back(0.0430105);
  fForest.push_back( 
NN(
NN(
NN(
NN(
0, 
0, 
-1, 0, 1, 1, 0.512093,-99) , 
NN(
0, 
0, 
-1, 0, 1, -1, 0.465022,-99) , 
8, 371.334, 0, 0, 0.504803,-99) , 
NN(
NN(
0, 
0, 
-1, 0, 1, 1, 0.500807,-99) , 
NN(
0, 
0, 
-1, 0, 1, -1, 0.422634,-99) , 
2, 2.15779, 0, 0, 0.462855,-99) , 
9, 296.798, 1, 0, 0.500672,-99) , 
NN(
NN(
0, 
0, 
-1, 0, 1, 1, 0.53213,-99) , 
NN(
0, 
0, 
-1, 2.09929, 0, -1, 0.459175,-99) , 
10, 491.821, 1, 0, 0.470638,-99) , 
6, 2.69867, 1, 0, 0.495596,-99)    );
  // itree = 114
  fBoostWeights.push_back(0.0317237);
  fForest.push_back( 
NN(
NN(
NN(
0, 
0, 
-1, 40.9682, 1, 1, 0.505907,-99) , 
NN(
0, 
0, 
-1, 256.854, 1, -1, 0.455689,-99) , 
1, 11.4107, 0, 0, 0.4966,-99) , 
NN(
0, 
0, 
-1, 69.7263, 0, -1, 0.462608,-99) , 
1, 193.989, 1, 0, 0.492649,-99)    );
  // itree = 115
  fBoostWeights.push_back(0.0301031);
  fForest.push_back( 
NN(
NN(
NN(
NN(
0, 
0, 
-1, 0, 1, 1, 0.530339,-99) , 
NN(
0, 
0, 
-1, 0, 1, -1, 0.491785,-99) , 
8, 328.025, 1, 0, 0.495557,-99) , 
NN(
0, 
0, 
-1, 0, 1, -1, 0.416052,-99) , 
11, 435.725, 1, 0, 0.493035,-99) , 
NN(
0, 
0, 
-1, 0, 1, -1, 0.431378,-99) , 
12, 0.330155, 0, 0, 0.49046,-99)    );
  // itree = 116
  fBoostWeights.push_back(0.0188908);
  fForest.push_back( 
NN(
NN(
NN(
0, 
0, 
-1, 0, 1, 1, 0.552853,-99) , 
NN(
NN(
0, 
0, 
-1, 0, 1, 1, 0.500181,-99) , 
NN(
0, 
0, 
-1, 0, 1, -1, 0.453445,-99) , 
7, 300.437, 1, 0, 0.494483,-99) , 
8, 1240.24, 0, 0, 0.496624,-99) , 
NN(
0, 
0, 
-1, 0, 1, -1, 0.419443,-99) , 
9, 436.431, 1, 0, 0.494632,-99)    );
  // itree = 117
  fBoostWeights.push_back(0.0279004);
  fForest.push_back( 
NN(
NN(
NN(
NN(
0, 
0, 
-1, 0, 1, 1, 0.50405,-99) , 
NN(
0, 
0, 
-1, 0, 1, -1, 0.483446,-99) , 
11, 163.394, 1, 0, 0.495355,-99) , 
NN(
0, 
0, 
-1, 0, 1, -1, 0.448491,-99) , 
16, -2.89518, 0, 0, 0.493106,-99) , 
NN(
0, 
0, 
-1, 422.249, 0, -1, 0.44751,-99) , 
11, 378.328, 1, 0, 0.490229,-99)    );
  // itree = 118
  fBoostWeights.push_back(0.045293);
  fForest.push_back( 
NN(
NN(
NN(
0, 
0, 
-1, 42.4792, 1, 1, 0.540845,-99) , 
NN(
NN(
0, 
0, 
-1, 0, 1, 1, 0.516997,-99) , 
NN(
0, 
0, 
-1, 0, 1, -1, 0.44576,-99) , 
2, 2.65597, 1, 0, 0.492028,-99) , 
11, 127.307, 1, 0, 0.518694,-99) , 
NN(
NN(
NN(
0, 
0, 
-1, 0, 1, 1, 0.581479,-99) , 
NN(
0, 
0, 
-1, 0, 1, -1, 0.489127,-99) , 
10, 450.667, 1, 0, 0.494149,-99) , 
NN(
0, 
0, 
-1, 181.526, 0, -1, 0.462626,-99) , 
11, 95.6953, 0, 0, 0.487041,-99) , 
14, 111.547, 0, 0, 0.492552,-99)    );
  // itree = 119
  fBoostWeights.push_back(0.0599263);
  fForest.push_back( 
NN(
NN(
NN(
NN(
0, 
0, 
-1, 0, 1, 1, 0.557437,-99) , 
NN(
0, 
0, 
-1, 0, 1, -1, 0.472589,-99) , 
2, 2.96735, 1, 0, 0.53957,-99) , 
NN(
NN(
0, 
0, 
-1, 0, 1, 1, 0.530769,-99) , 
NN(
0, 
0, 
-1, 0, 1, -1, 0.461116,-99) , 
11, 253.231, 0, 0, 0.483485,-99) , 
5, 302.489, 1, 0, 0.516964,-99) , 
NN(
NN(
NN(
0, 
0, 
-1, 0, 1, 1, 0.527618,-99) , 
NN(
0, 
0, 
-1, 0, 1, -1, 0.480146,-99) , 
8, 742.724, 0, 0, 0.491873,-99) , 
NN(
0, 
0, 
-1, 0, 1, -1, 0.400409,-99) , 
11, 435.725, 1, 0, 0.488527,-99) , 
6, 2.057, 1, 0, 0.495887,-99)    );
  // itree = 120
  fBoostWeights.push_back(0.0220778);
  fForest.push_back( 
NN(
NN(
NN(
0, 
0, 
-1, 156.398, 1, 1, 0.505826,-99) , 
NN(
0, 
0, 
-1, 469.836, 0, -1, 0.482808,-99) , 
11, 89.279, 0, 0, 0.500326,-99) , 
NN(
NN(
0, 
0, 
-1, 0, 1, 1, 0.500761,-99) , 
NN(
0, 
0, 
-1, 0, 1, -1, 0.405587,-99) , 
2, 2.51358, 1, 0, 0.452908,-99) , 
11, 378.328, 1, 0, 0.497316,-99)    );
  // itree = 121
  fBoostWeights.push_back(0.0580011);
  fForest.push_back( 
NN(
NN(
NN(
NN(
0, 
0, 
-1, 0, 1, 1, 0.522797,-99) , 
NN(
0, 
0, 
-1, 0, 1, -1, 0.476691,-99) , 
1, 150.928, 1, 0, 0.513941,-99) , 
NN(
NN(
0, 
0, 
-1, 0, 1, 1, 0.529485,-99) , 
NN(
0, 
0, 
-1, 0, 1, -1, 0.440787,-99) , 
3, 143.074, 0, 0, 0.48093,-99) , 
1, 30.6667, 0, 0, 0.506734,-99) , 
NN(
NN(
NN(
0, 
0, 
-1, 0, 1, 1, 0.568993,-99) , 
NN(
0, 
0, 
-1, 0, 1, -1, 0.495299,-99) , 
12, 0.597415, 1, 0, 0.522717,-99) , 
NN(
0, 
0, 
-1, 121.805, 0, -1, 0.467777,-99) , 
8, 1138.1, 0, 0, 0.480289,-99) , 
7, 238.017, 1, 0, 0.498605,-99)    );
  // itree = 122
  fBoostWeights.push_back(0.0220399);
  fForest.push_back( 
NN(
NN(
NN(
0, 
0, 
-1, 316.193, 1, 1, 0.509661,-99) , 
NN(
0, 
0, 
-1, 330.363, 0, -1, 0.491084,-99) , 
6, 2.34496, 0, 0, 0.499301,-99) , 
NN(
0, 
0, 
-1, 0, 1, -1, 0.441853,-99) , 
12, 0.311563, 0, 0, 0.497219,-99)    );
  // itree = 123
  fBoostWeights.push_back(0.030621);
  fForest.push_back( 
NN(
NN(
NN(
0, 
0, 
-1, 1.63975, 0, 1, 0.507046,-99) , 
NN(
0, 
0, 
-1, 0, 1, -1, 0.440326,-99) , 
6, 1.44224, 0, 0, 0.504063,-99) , 
NN(
NN(
NN(
0, 
0, 
-1, 0, 1, 1, 0.516039,-99) , 
NN(
0, 
0, 
-1, 0, 1, -1, 0.438206,-99) , 
1, 102.25, 1, 0, 0.491507,-99) , 
NN(
0, 
0, 
-1, 0, 1, -1, 0.37845,-99) , 
8, 448.045, 0, 0, 0.464911,-99) , 
13, 27.7227, 0, 0, 0.49862,-99)    );
  // itree = 124
  fBoostWeights.push_back(0.0471837);
  fForest.push_back( 
NN(
NN(
NN(
0, 
0, 
-1, 1515.66, 0, 1, 0.506613,-99) , 
NN(
0, 
0, 
-1, 0, 1, -1, 0.437495,-99) , 
6, 3.06718, 1, 0, 0.502423,-99) , 
NN(
NN(
NN(
0, 
0, 
-1, 0, 1, 1, 0.539612,-99) , 
NN(
0, 
0, 
-1, 0, 1, -1, 0.438835,-99) , 
8, 373.9, 0, 0, 0.507696,-99) , 
NN(
NN(
0, 
0, 
-1, 0, 1, 1, 0.532061,-99) , 
NN(
0, 
0, 
-1, 0, 1, -1, 0.435976,-99) , 
12, 1.53695, 0, 0, 0.449936,-99) , 
5, 150.04, 1, 0, 0.467747,-99) , 
5, 208.466, 0, 0, 0.492053,-99)    );
  // itree = 125
  fBoostWeights.push_back(0.0313917);
  fForest.push_back( 
NN(
NN(
NN(
0, 
0, 
-1, 182.275, 1, 1, 0.522082,-99) , 
NN(
0, 
0, 
-1, 333.667, 1, -1, 0.487111,-99) , 
10, 1143.87, 0, 0, 0.491733,-99) , 
NN(
0, 
0, 
-1, 0, 1, -1, 0.428978,-99) , 
4, 765.109, 1, 0, 0.489984,-99)    );
  // itree = 126
  fBoostWeights.push_back(0.0300266);
  fForest.push_back( 
NN(
NN(
NN(
0, 
0, 
-1, 2.66628, 0, 1, 0.556144,-99) , 
NN(
0, 
0, 
-1, 0, 1, -1, 0.463283,-99) , 
9, 96.452, 0, 0, 0.531544,-99) , 
NN(
0, 
0, 
-1, 21.0736, 0, -1, 0.489455,-99) , 
12, 1.56413, 0, 0, 0.494099,-99)    );
  // itree = 127
  fBoostWeights.push_back(0.03001);
  fForest.push_back( 
NN(
NN(
NN(
NN(
0, 
0, 
-1, 0, 1, 1, 0.504848,-99) , 
NN(
0, 
0, 
-1, 0, 1, -1, 0.443843,-99) , 
13, 22.5439, 0, 0, 0.500022,-99) , 
NN(
NN(
0, 
0, 
-1, 0, 1, 1, 0.513821,-99) , 
NN(
0, 
0, 
-1, 0, 1, -1, 0.398841,-99) , 
10, 929.587, 0, 0, 0.460069,-99) , 
15, 317.126, 1, 0, 0.496363,-99) , 
NN(
0, 
0, 
-1, 0, 1, -1, 0.416917,-99) , 
7, 553.774, 1, 0, 0.494202,-99)    );
  // itree = 128
  fBoostWeights.push_back(0.0445154);
  fForest.push_back( 
NN(
NN(
NN(
NN(
0, 
0, 
-1, 0, 1, 1, 0.528081,-99) , 
NN(
0, 
0, 
-1, 0, 1, -1, 0.498709,-99) , 
3, 164.262, 0, 0, 0.513671,-99) , 
NN(
NN(
0, 
0, 
-1, 0, 1, 1, 0.566328,-99) , 
NN(
0, 
0, 
-1, 0, 1, -1, 0.476751,-99) , 
14, 124.633, 0, 0, 0.485991,-99) , 
10, 699.229, 0, 0, 0.500787,-99) , 
NN(
0, 
0, 
-1, 0, 1, -1, 0.450391,-99) , 
9, 367.748, 1, 0, 0.498387,-99)    );
  // itree = 129
  fBoostWeights.push_back(0.0302185);
  fForest.push_back( 
NN(
NN(
0, 
0, 
-1, 0, 1, 1, 0.568406,-99) , 
NN(
NN(
NN(
0, 
0, 
-1, 0, 1, 1, 0.505778,-99) , 
NN(
0, 
0, 
-1, 0, 1, -1, 0.463466,-99) , 
4, 508.27, 1, 0, 0.501325,-99) , 
NN(
NN(
0, 
0, 
-1, 0, 1, 1, 0.516978,-99) , 
NN(
0, 
0, 
-1, 0, 1, -1, 0.364883,-99) , 
5, 181.327, 0, 0, 0.457674,-99) , 
10, 457.301, 0, 0, 0.497939,-99) , 
8, 1379.55, 0, 0, 0.500363,-99)    );
  // itree = 130
  fBoostWeights.push_back(0.0223102);
  fForest.push_back( 
NN(
NN(
NN(
0, 
0, 
-1, 0, 1, 1, 0.548612,-99) , 
NN(
0, 
0, 
-1, 448.604, 0, -1, 0.493108,-99) , 
10, 1369.65, 0, 0, 0.496241,-99) , 
NN(
0, 
0, 
-1, 0, 1, -1, 0.418279,-99) , 
9, 436.431, 1, 0, 0.494192,-99)    );
  // itree = 131
  fBoostWeights.push_back(0.0232176);
  fForest.push_back( 
NN(
NN(
0, 
0, 
-1, 0, 1, 1, 0.573038,-99) , 
NN(
NN(
NN(
0, 
0, 
-1, 0, 1, 1, 0.504429,-99) , 
NN(
0, 
0, 
-1, 0, 1, -1, 0.474704,-99) , 
5, 524.615, 1, 0, 0.500399,-99) , 
NN(
0, 
0, 
-1, 0, 1, -1, 0.436193,-99) , 
7, 422.048, 1, 0, 0.497936,-99) , 
8, 1379.55, 0, 0, 0.500511,-99)    );
  // itree = 132
  fBoostWeights.push_back(0.0267925);
  fForest.push_back( 
NN(
NN(
NN(
0, 
0, 
-1, 45.8886, 1, 1, 0.509481,-99) , 
NN(
0, 
0, 
-1, 0.48339, 0, -1, 0.478784,-99) , 
2, 1.17445, 0, 0, 0.50455,-99) , 
NN(
NN(
0, 
0, 
-1, 0, 1, 1, 0.500273,-99) , 
NN(
0, 
0, 
-1, 0, 1, -1, 0.438089,-99) , 
12, 1.0519, 0, 0, 0.461682,-99) , 
16, -2.77197, 0, 0, 0.50135,-99)    );
  // itree = 133
  fBoostWeights.push_back(0.0463002);
  fForest.push_back( 
NN(
NN(
NN(
0, 
0, 
-1, 0, 1, 1, 0.572007,-99) , 
NN(
0, 
0, 
-1, 0, 1, -1, 0.488491,-99) , 
7, 161.276, 1, 0, 0.517687,-99) , 
NN(
NN(
NN(
0, 
0, 
-1, 0, 1, 1, 0.513921,-99) , 
NN(
0, 
0, 
-1, 0, 1, -1, 0.447797,-99) , 
11, 396.121, 1, 0, 0.503473,-99) , 
NN(
NN(
0, 
0, 
-1, 0, 1, 1, 0.508542,-99) , 
NN(
0, 
0, 
-1, 0, 1, -1, 0.472092,-99) , 
9, 181.22, 0, 0, 0.480893,-99) , 
10, 869.527, 0, 0, 0.4883,-99) , 
14, 133.856, 0, 0, 0.491021,-99)    );
  // itree = 134
  fBoostWeights.push_back(0.0195933);
  fForest.push_back( 
NN(
NN(
NN(
NN(
0, 
0, 
-1, 0, 1, 1, 0.546914,-99) , 
NN(
0, 
0, 
-1, 0, 1, -1, 0.496506,-99) , 
13, 174.055, 0, 0, 0.498703,-99) , 
NN(
0, 
0, 
-1, 0, 1, -1, 0.417249,-99) , 
11, 445.859, 1, 0, 0.496259,-99) , 
NN(
0, 
0, 
-1, 0, 1, -1, 0.442734,-99) , 
12, 0.329965, 0, 0, 0.494004,-99)    );
  // itree = 135
  fBoostWeights.push_back(0.0506742);
  fForest.push_back( 
NN(
NN(
NN(
NN(
0, 
0, 
-1, 0, 1, 1, 0.541898,-99) , 
NN(
0, 
0, 
-1, 0, 1, -1, 0.486454,-99) , 
5, 314.52, 1, 0, 0.529754,-99) , 
NN(
NN(
0, 
0, 
-1, 0, 1, 1, 0.518461,-99) , 
NN(
0, 
0, 
-1, 0, 1, -1, 0.480342,-99) , 
11, 155.266, 1, 0, 0.502632,-99) , 
6, 2.10907, 1, 0, 0.510135,-99) , 
NN(
NN(
NN(
0, 
0, 
-1, 0, 1, 1, 0.551818,-99) , 
NN(
0, 
0, 
-1, 0, 1, -1, 0.487989,-99) , 
9, 277.081, 1, 0, 0.525643,-99) , 
NN(
0, 
0, 
-1, 232.495, 0, -1, 0.473099,-99) , 
5, 600.947, 0, 0, 0.487253,-99) , 
7, 238.018, 1, 0, 0.503107,-99)    );
  // itree = 136
  fBoostWeights.push_back(0.0393658);
  fForest.push_back( 
NN(
NN(
NN(
0, 
0, 
-1, 2.52091, 0, 1, 0.525465,-99) , 
NN(
NN(
0, 
0, 
-1, 0, 1, 1, 0.508122,-99) , 
NN(
0, 
0, 
-1, 0, 1, -1, 0.479874,-99) , 
10, 607.982, 0, 0, 0.499789,-99) , 
15, 90.1363, 1, 0, 0.505985,-99) , 
NN(
NN(
0, 
0, 
-1, 0, 1, 1, 0.538069,-99) , 
NN(
NN(
0, 
0, 
-1, 0, 1, 1, 0.504339,-99) , 
NN(
0, 
0, 
-1, 0, 1, -1, 0.411233,-99) , 
12, 1.0617, 0, 0, 0.444105,-99) , 
8, 1141.11, 0, 0, 0.46852,-99) , 
4, 491.217, 1, 0, 0.501436,-99)    );
  // itree = 137
  fBoostWeights.push_back(0.0427554);
  fForest.push_back( 
NN(
NN(
NN(
0, 
0, 
-1, 0, 1, 1, 0.568915,-99) , 
NN(
NN(
0, 
0, 
-1, 0, 1, 1, 0.552589,-99) , 
NN(
0, 
0, 
-1, 0, 1, -1, 0.484292,-99) , 
13, 38.2076, 0, 0, 0.510801,-99) , 
6, 2.10655, 1, 0, 0.529519,-99) , 
NN(
NN(
NN(
0, 
0, 
-1, 0, 1, 1, 0.586923,-99) , 
NN(
0, 
0, 
-1, 0, 1, -1, 0.494987,-99) , 
6, 2.37447, 0, 0, 0.541659,-99) , 
NN(
NN(
0, 
0, 
-1, 0, 1, 1, 0.528862,-99) , 
NN(
0, 
0, 
-1, 0, 1, -1, 0.48383,-99) , 
0, 265.393, 0, 0, 0.48724,-99) , 
9, 71.8217, 1, 0, 0.490598,-99) , 
15, 64.2012, 1, 0, 0.494582,-99)    );
  // itree = 138
  fBoostWeights.push_back(0.0253417);
  fForest.push_back( 
NN(
NN(
NN(
0, 
0, 
-1, 67.6081, 1, 1, 0.561294,-99) , 
NN(
0, 
0, 
-1, 0, 1, -1, 0.432247,-99) , 
9, 75.3493, 0, 0, 0.532786,-99) , 
NN(
NN(
NN(
0, 
0, 
-1, 0, 1, 1, 0.55002,-99) , 
NN(
0, 
0, 
-1, 0, 1, -1, 0.499915,-99) , 
5, 139.614, 1, 0, 0.502371,-99) , 
NN(
0, 
0, 
-1, 0, 1, -1, 0.441891,-99) , 
10, 519.828, 0, 0, 0.49896,-99) , 
8, 351.243, 1, 0, 0.503109,-99)    );
  // itree = 139
  fBoostWeights.push_back(0.0449073);
  fForest.push_back( 
NN(
NN(
NN(
NN(
0, 
0, 
-1, 0, 1, 1, 0.538504,-99) , 
NN(
0, 
0, 
-1, 0, 1, -1, 0.488413,-99) , 
2, 0.84277, 0, 0, 0.524806,-99) , 
NN(
NN(
0, 
0, 
-1, 0, 1, 1, 0.505371,-99) , 
NN(
0, 
0, 
-1, 0, 1, -1, 0.456937,-99) , 
13, 38.9029, 0, 0, 0.496795,-99) , 
12, 0.776679, 1, 0, 0.506754,-99) , 
NN(
NN(
0, 
0, 
-1, 173.911, 1, 1, 0.526544,-99) , 
NN(
0, 
0, 
-1, 0.988506, 0, -1, 0.469595,-99) , 
0, 140.561, 0, 0, 0.489198,-99) , 
2, 2.6816, 1, 0, 0.500577,-99)    );
  // itree = 140
  fBoostWeights.push_back(0.0274711);
  fForest.push_back( 
NN(
NN(
NN(
NN(
0, 
0, 
-1, 0, 1, 1, 0.513312,-99) , 
NN(
0, 
0, 
-1, 0, 1, -1, 0.492354,-99) , 
0, 98.738, 1, 0, 0.501033,-99) , 
NN(
0, 
0, 
-1, 0, 1, -1, 0.439539,-99) , 
11, 435.725, 1, 0, 0.498996,-99) , 
NN(
0, 
0, 
-1, 0, 1, -1, 0.435863,-99) , 
12, 0.330155, 0, 0, 0.496507,-99)    );
  // itree = 141
  fBoostWeights.push_back(0.0540056);
  fForest.push_back( 
NN(
NN(
NN(
0, 
0, 
-1, 402.979, 0, 1, 0.540923,-99) , 
NN(
NN(
0, 
0, 
-1, 0, 1, 1, 0.509311,-99) , 
NN(
0, 
0, 
-1, 0, 1, -1, 0.433488,-99) , 
9, 158.293, 0, 0, 0.485255,-99) , 
2, 1.89955, 0, 0, 0.520149,-99) , 
NN(
NN(
NN(
0, 
0, 
-1, 0, 1, 1, 0.515086,-99) , 
NN(
0, 
0, 
-1, 0, 1, -1, 0.469695,-99) , 
7, 250.712, 1, 0, 0.505161,-99) , 
NN(
0, 
0, 
-1, 544.802, 0, -1, 0.447004,-99) , 
0, 124.735, 1, 0, 0.498516,-99) , 
0, 139.433, 0, 0, 0.505888,-99)    );
  // itree = 142
  fBoostWeights.push_back(0.0226151);
  fForest.push_back( 
NN(
NN(
NN(
0, 
0, 
-1, 0, 1, 1, 0.565786,-99) , 
NN(
NN(
0, 
0, 
-1, 0, 1, 1, 0.504671,-99) , 
NN(
0, 
0, 
-1, 0, 1, -1, 0.454519,-99) , 
7, 360.594, 1, 0, 0.501001,-99) , 
8, 1379.55, 0, 0, 0.503109,-99) , 
NN(
0, 
0, 
-1, 0, 1, -1, 0.452048,-99) , 
6, 1.44576, 0, 0, 0.500774,-99)    );
  // itree = 143
  fBoostWeights.push_back(0.0322935);
  fForest.push_back( 
NN(
NN(
NN(
0, 
0, 
-1, 0, 1, 1, 0.5957,-99) , 
NN(
0, 
0, 
-1, 0, 1, -1, 0.476701,-99) , 
13, 19.392, 0, 0, 0.541552,-99) , 
NN(
NN(
NN(
0, 
0, 
-1, 0, 1, 1, 0.508667,-99) , 
NN(
0, 
0, 
-1, 0, 1, -1, 0.483296,-99) , 
5, 208.466, 0, 0, 0.500652,-99) , 
NN(
0, 
0, 
-1, 0, 1, -1, 0.436223,-99) , 
11, 435.725, 1, 0, 0.498692,-99) , 
12, 0.412243, 1, 0, 0.501554,-99)    );
  // itree = 144
  fBoostWeights.push_back(0.0437321);
  fForest.push_back( 
NN(
NN(
NN(
0, 
0, 
-1, 157.236, 1, 1, 0.523134,-99) , 
NN(
NN(
0, 
0, 
-1, 0, 1, 1, 0.507225,-99) , 
NN(
0, 
0, 
-1, 0, 1, -1, 0.441629,-99) , 
10, 994.968, 0, 0, 0.476678,-99) , 
15, 361.927, 1, 0, 0.513413,-99) , 
NN(
NN(
NN(
0, 
0, 
-1, 0, 1, 1, 0.575131,-99) , 
NN(
0, 
0, 
-1, 0, 1, -1, 0.49432,-99) , 
0, 71.3505, 1, 0, 0.516366,-99) , 
NN(
NN(
0, 
0, 
-1, 0, 1, 1, 0.50512,-99) , 
NN(
0, 
0, 
-1, 0, 1, -1, 0.474921,-99) , 
12, 0.689961, 1, 0, 0.483098,-99) , 
16, -2.03278, 1, 0, 0.488649,-99) , 
15, 187.8, 0, 0, 0.496452,-99)    );
  // itree = 145
  fBoostWeights.push_back(0.0389681);
  fForest.push_back( 
NN(
NN(
NN(
NN(
0, 
0, 
-1, 0, 1, 1, 0.55272,-99) , 
NN(
0, 
0, 
-1, 0, 1, -1, 0.488027,-99) , 
5, 307.944, 1, 0, 0.524902,-99) , 
NN(
NN(
0, 
0, 
-1, 0, 1, 1, 0.504519,-99) , 
NN(
0, 
0, 
-1, 0, 1, -1, 0.476751,-99) , 
10, 670.392, 0, 0, 0.49363,-99) , 
6, 1.98809, 1, 0, 0.499688,-99) , 
NN(
NN(
NN(
0, 
0, 
-1, 0, 1, 1, 0.511526,-99) , 
NN(
0, 
0, 
-1, 0, 1, -1, 0.439615,-99) , 
12, 1.21526, 1, 0, 0.478095,-99) , 
NN(
0, 
0, 
-1, 0, 1, -1, 0.414872,-99) , 
12, 0.778029, 0, 0, 0.458949,-99) , 
3, 68.7309, 0, 0, 0.495903,-99)    );
  // itree = 146
  fBoostWeights.push_back(0.028582);
  fForest.push_back( 
NN(
NN(
0, 
0, 
-1, 0, 1, 1, 0.560724,-99) , 
NN(
NN(
0, 
0, 
-1, 0, 1, 1, 0.548051,-99) , 
NN(
NN(
0, 
0, 
-1, 0, 1, 1, 0.521727,-99) , 
NN(
0, 
0, 
-1, 0, 1, -1, 0.490592,-99) , 
7, 108.516, 1, 0, 0.494556,-99) , 
10, 1516.09, 0, 0, 0.497109,-99) , 
6, 1.29802, 1, 0, 0.499152,-99)    );
  // itree = 147
  fBoostWeights.push_back(0.0364972);
  fForest.push_back( 
NN(
NN(
NN(
0, 
0, 
-1, 565.116, 1, 1, 0.529064,-99) , 
NN(
NN(
0, 
0, 
-1, 0, 1, 1, 0.515717,-99) , 
NN(
0, 
0, 
-1, 0, 1, -1, 0.485767,-99) , 
12, 1.27124, 0, 0, 0.494411,-99) , 
12, 0.557625, 1, 0, 0.499029,-99) , 
NN(
0, 
0, 
-1, 0, 1, -1, 0.423829,-99) , 
12, 0.247882, 0, 0, 0.496935,-99)    );
  // itree = 148
  fBoostWeights.push_back(0.0157535);
  fForest.push_back( 
NN(
NN(
NN(
0, 
0, 
-1, 46.9796, 1, 1, 0.503554,-99) , 
NN(
0, 
0, 
-1, 0, 1, -1, 0.451696,-99) , 
0, 42.2941, 0, 0, 0.501133,-99) , 
NN(
0, 
0, 
-1, 0, 1, -1, 0.406712,-99) , 
7, 553.773, 1, 0, 0.498727,-99)    );
  // itree = 149
  fBoostWeights.push_back(0.0312994);
  fForest.push_back( 
NN(
NN(
NN(
0, 
0, 
-1, 0, 1, 1, 0.571825,-99) , 
NN(
NN(
0, 
0, 
-1, 0, 1, 1, 0.547768,-99) , 
NN(
0, 
0, 
-1, 0, 1, -1, 0.489173,-99) , 
13, 38.8711, 0, 0, 0.514975,-99) , 
15, 38.3228, 1, 0, 0.531576,-99) , 
NN(
NN(
0, 
0, 
-1, 0, 1, 1, 0.537747,-99) , 
NN(
0, 
0, 
-1, 374.095, 1, -1, 0.488339,-99) , 
10, 1450.5, 0, 0, 0.491282,-99) , 
15, 61.2463, 1, 0, 0.494915,-99)    );
   return;
};
 
// Clean up
inline void ReadBDT::Clear() 
{
   for (unsigned int itree=0; itree<fForest.size(); itree++) { 
      delete fForest[itree]; 
   }
}
   inline double ReadBDT::GetMvaValue( const std::vector<double>& inputValues ) const
   {
      // classifier response value
      double retval = 0;

      // classifier response, sanity check first
      if (!IsStatusClean()) {
         std::cout << "Problem in class \"" << fClassName << "\": cannot return classifier response"
                   << " because status is dirty" << std::endl;
         retval = 0;
      }
      else {
         if (IsNormalised()) {
            // normalise variables
            std::vector<double> iV;
            iV.reserve(inputValues.size());
            int ivar = 0;
            for (std::vector<double>::const_iterator varIt = inputValues.begin();
                 varIt != inputValues.end(); varIt++, ivar++) {
               iV.push_back(NormVariable( *varIt, fVmin[ivar], fVmax[ivar] ));
            }
            retval = GetMvaValue__( iV );
         }
         else {
            retval = GetMvaValue__( inputValues );
         }
      }

      return retval;
   }
