// Class: ReadBDT
// Automatically generated by MethodBase::MakeClass
//

/* configuration options =====================================================

#GEN -*-*-*-*-*-*-*-*-*-*-*- general info -*-*-*-*-*-*-*-*-*-*-*-

Method         : BDT::BDT
TMVA Release   : 4.2.0         [262656]
ROOT Release   : 5.34/18       [336402]
Creator        : jlee
Date           : Fri Dec  9 14:15:55 2016
Host           : Linux cmsdev02.cern.ch 2.6.32-431.23.3.el6.x86_64 #1 SMP Wed Jul 30 09:43:11 CEST 2014 x86_64 x86_64 x86_64 GNU/Linux
Dir            : /home/jlee/CMS/ChargedHiggs/CMSSW_7_2_4/src/TMVA/test
Training events: 229147
Analysis type  : [Classification]


#OPT -*-*-*-*-*-*-*-*-*-*-*-*- options -*-*-*-*-*-*-*-*-*-*-*-*-

# Set by User:
V: "False" [Verbose output (short form of "VerbosityLevel" below - overrides the latter one)]
H: "False" [Print method-specific help message]
IgnoreNegWeightsInTraining: "True" [Events with negative weights are ignored in the training (but are included for testing and performance evaluation)]
NTrees: "150" [Number of trees in the forest]
MaxDepth: "3" [Max depth of the decision tree allowed]
MinNodeSize: "2.5%" [Minimum percentage of training events required in a leaf node (default: Classification: 5%, Regression: 0.2%)]
nCuts: "50" [Number of grid points in variable range used in finding optimal cut in node splitting]
BoostType: "AdaBoost" [Boosting type for the trees in the forest (note: AdaCost is still experimental)]
UseBaggedBoost: "True" [Use only a random subsample of all events for growing the trees in each boost iteration.]
AdaBoostBeta: "5.000000e-01" [Learning rate  for AdaBoost algorithm]
BaggedSampleFraction: "5.000000e-01" [Relative size of bagged event sample to original size of the data sample (used whenever bagging is used (i.e. UseBaggedBoost, Bagging,)]
SeparationType: "giniindex" [Separation criterion for node splitting]
# Default:
VerbosityLevel: "Default" [Verbosity level]
VarTransform: "None" [List of variable transformations performed before training, e.g., "D_Background,P_Signal,G,N_AllClasses" for: "Decorrelation, PCA-transformation, Gaussianisation, Normalisation, each for the given class of events ('AllClasses' denotes all events of all classes, if no class indication is given, 'All' is assumed)"]
CreateMVAPdfs: "False" [Create PDFs for classifier outputs (signal and background)]
AdaBoostR2Loss: "quadratic" [Type of Loss function in AdaBoostR2]
Shrinkage: "1.000000e+00" [Learning rate for GradBoost algorithm]
UseRandomisedTrees: "False" [Determine at each node splitting the cut variable only as the best out of a random subset of variables (like in RandomForests)]
UseNvars: "4" [Size of the subset of variables used with RandomisedTree option]
UsePoissonNvars: "True" [Interpret "UseNvars" not as fixed number but as mean of a Possion distribution in each split with RandomisedTree option]
UseYesNoLeaf: "True" [Use Sig or Bkg categories, or the purity=S/(S+B) as classification of the leaf node -> Real-AdaBoost]
NegWeightTreatment: "inverseboostnegweights" [How to treat events with negative weights in the BDT training (particular the boosting) : IgnoreInTraining;  Boost With inverse boostweight; Pair events with negative and positive weights in traning sample and *annihilate* them (experimental!)]
Css: "1.000000e+00" [AdaCost: cost of true signal selected signal]
Cts_sb: "1.000000e+00" [AdaCost: cost of true signal selected bkg]
Ctb_ss: "1.000000e+00" [AdaCost: cost of true bkg    selected signal]
Cbb: "1.000000e+00" [AdaCost: cost of true bkg    selected bkg ]
NodePurityLimit: "5.000000e-01" [In boosting/pruning, nodes with purity > NodePurityLimit are signal; background otherwise.]
DoBoostMonitor: "False" [Create control plot with ROC integral vs tree number]
UseFisherCuts: "False" [Use multivariate splits using the Fisher criterion]
MinLinCorrForFisher: "8.000000e-01" [The minimum linear correlation between two variables demanded for use in Fisher criterion in node splitting]
UseExclusiveVars: "False" [Variables already used in fisher criterion are not anymore analysed individually for node splitting]
DoPreselection: "False" [and and apply automatic pre-selection for 100% efficient signal (bkg) cuts prior to training]
SigToBkgFraction: "1.000000e+00" [Sig to Bkg ratio used in Training (similar to NodePurityLimit, which cannot be used in real adaboost]
PruneMethod: "nopruning" [Note: for BDTs use small trees (e.g.MaxDepth=3) and NoPruning:  Pruning: Method used for pruning (removal) of statistically insignificant branches ]
PruneStrength: "0.000000e+00" [Pruning strength]
PruningValFraction: "5.000000e-01" [Fraction of events to use for optimizing automatic pruning.]
nEventsMin: "0" [deprecated: Use MinNodeSize (in % of training events) instead]
UseBaggedGrad: "False" [deprecated: Use *UseBaggedBoost* instead:  Use only a random subsample of all events for growing the trees in each iteration.]
GradBaggingFraction: "5.000000e-01" [deprecated: Use *BaggedSampleFraction* instead: Defines the fraction of events to be used in each iteration, e.g. when UseBaggedGrad=kTRUE. ]
UseNTrainEvents: "0" [deprecated: Use *BaggedSampleFraction* instead: Number of randomly picked training events used in randomised (and bagged) trees]
NNodesMax: "0" [deprecated: Use MaxDepth instead to limit the tree size]
##


#VAR -*-*-*-*-*-*-*-*-*-*-*-* variables *-*-*-*-*-*-*-*-*-*-*-*-

NVar 19
mass_minBBdr                  mass_minBBdr                  mass_minBBdr                  mass_minBBdr                                                    'F'    [9.21174526215,1696.61083984]
mass_minLLdr                  mass_minLLdr                  mass_minLLdr                  mass_minLLdr                                                    'F'    [0,3965.9609375]
lepDR_minBBdr                 lepDR_minBBdr                 lepDR_minBBdr                 lepDR_minBBdr                                                   'F'    [0.00382891274057,8.16100215912]
mass_maxBBpt                  mass_maxBBpt                  mass_maxBBpt                  mass_maxBBpt                                                    'F'    [12.0210437775,2786.44750977]
mass_maxBBmass                mass_maxBBmass                mass_maxBBmass                mass_maxBBmass                                                  'F'    [30.7496967316,3385.640625]
mass_maxJJJpt                 mass_maxJJJpt                 mass_maxJJJpt                 mass_maxJJJpt                                                   'F'    [35.2640266418,4210.77734375]
aveBBdr                       aveBBdr                       aveBBdr                       aveBBdr                                                         'F'    [0.442296296358,4.35139703751]
theJetLeadPt                  theJetLeadPt                  theJetLeadPt                  theJetLeadPt                                                    'F'    [50.0062789917,2054.625]
AK4HTpMETpLepPt               AK4HTpMETpLepPt               AK4HTpMETpLepPt               AK4HTpMETpLepPt                                                 'F'    [185.797775269,4779.99169922]
topPt                         topPt                         topPt                         topPt                                                           'F'    [0.179473146796,6426.11572266]
minDR_lepJet                  minDR_lepJet                  minDR_lepJet                  minDR_lepJet                                                    'F'    [0.00054070999613,4.23382616043]
ptRel_lepJet                  ptRel_lepJet                  ptRel_lepJet                  ptRel_lepJet                                                    'F'    [0.0746982172132,2739.35083008]
MT_lepMet                     MT_lepMet                     MT_lepMet                     MT_lepMet                                                       'F'    [0.000480508722831,1423.15209961]
mass_lepJets0                 mass_lepJets0                 mass_lepJets0                 mass_lepJets0                                                   'F'    [6.63578987122,3246.00805664]
mass_lepJets1                 mass_lepJets1                 mass_lepJets1                 mass_lepJets1                                                   'F'    [2.84744954109,3042.34667969]
mass_lepJets2                 mass_lepJets2                 mass_lepJets2                 mass_lepJets2                                                   'F'    [3.11589789391,2233.31811523]
deltaPhi_lepJets0             deltaPhi_lepJets0             deltaPhi_lepJets0             deltaPhi_lepJets0                                               'F'    [-3.14157772064,3.14159202576]
deltaPhi_lepJets1             deltaPhi_lepJets1             deltaPhi_lepJets1             deltaPhi_lepJets1                                               'F'    [-3.14157509804,3.14155387878]
deltaPhi_lepJets2             deltaPhi_lepJets2             deltaPhi_lepJets2             deltaPhi_lepJets2                                               'F'    [-3.14157938957,3.14157652855]
NSpec 0


============================================================================ */

#include <vector>
#include <cmath>
#include <string>
#include <iostream>

#define NN new BDTNode
   
#ifndef BDTNode__def
#define BDTNode__def
   
class BDTNode {
   
public:
   
   // constructor of an essentially "empty" node floating in space
   BDTNode ( BDTNode* left,BDTNode* right,
                          int selector, double cutValue, bool cutType, 
                          int nodeType, double purity, double response ) :
   fLeft         ( left         ),
   fRight        ( right        ),
   fSelector     ( selector     ),
   fCutValue     ( cutValue     ),
   fCutType      ( cutType      ),
   fNodeType     ( nodeType     ),
   fPurity       ( purity       ),
   fResponse     ( response     ){
   }

   virtual ~BDTNode();

   // test event if it decends the tree at this node to the right
   virtual bool GoesRight( const std::vector<double>& inputValues ) const;
   BDTNode* GetRight( void )  {return fRight; };

   // test event if it decends the tree at this node to the left 
   virtual bool GoesLeft ( const std::vector<double>& inputValues ) const;
   BDTNode* GetLeft( void ) { return fLeft; };   

   // return  S/(S+B) (purity) at this node (from  training)

   double GetPurity( void ) const { return fPurity; } 
   // return the node type
   int    GetNodeType( void ) const { return fNodeType; }
   double GetResponse(void) const {return fResponse;}

private:

   BDTNode*   fLeft;     // pointer to the left daughter node
   BDTNode*   fRight;    // pointer to the right daughter node
   int                     fSelector; // index of variable used in node selection (decision tree)   
   double                  fCutValue; // cut value appplied on this node to discriminate bkg against sig
   bool                    fCutType;  // true: if event variable > cutValue ==> signal , false otherwise
   int                     fNodeType; // Type of node: -1 == Bkg-leaf, 1 == Signal-leaf, 0 = internal 
   double                  fPurity;   // Purity of node from training
   double                  fResponse; // Regression response value of node
}; 
   
//_______________________________________________________________________
   BDTNode::~BDTNode()
{
   if (fLeft  != NULL) delete fLeft;
   if (fRight != NULL) delete fRight;
}; 
   
//_______________________________________________________________________
bool BDTNode::GoesRight( const std::vector<double>& inputValues ) const
{
   // test event if it decends the tree at this node to the right
   bool result;
     result = (inputValues[fSelector] > fCutValue );
   if (fCutType == true) return result; //the cuts are selecting Signal ;
   else return !result;
}
   
//_______________________________________________________________________
bool BDTNode::GoesLeft( const std::vector<double>& inputValues ) const
{
   // test event if it decends the tree at this node to the left
   if (!this->GoesRight(inputValues)) return true;
   else return false;
}
   
#endif
   
#ifndef IClassifierReader__def
#define IClassifierReader__def

class IClassifierReader {

 public:

   // constructor
   IClassifierReader() : fStatusIsClean( true ) {}
   virtual ~IClassifierReader() {}

   // return classifier response
   virtual double GetMvaValue( const std::vector<double>& inputValues ) const = 0;

   // returns classifier status
   bool IsStatusClean() const { return fStatusIsClean; }

 protected:

   bool fStatusIsClean;
};

#endif

class ReadBDT : public IClassifierReader {

 public:

   // constructor
   ReadBDT( std::vector<std::string>& theInputVars ) 
      : IClassifierReader(),
        fClassName( "ReadBDT" ),
        fNvars( 19 ),
        fIsNormalised( false )
   {      
      // the training input variables
      const char* inputVars[] = { "mass_minBBdr", "mass_minLLdr", "lepDR_minBBdr", "mass_maxBBpt", "mass_maxBBmass", "mass_maxJJJpt", "aveBBdr", "theJetLeadPt", "AK4HTpMETpLepPt", "topPt", "minDR_lepJet", "ptRel_lepJet", "MT_lepMet", "mass_lepJets0", "mass_lepJets1", "mass_lepJets2", "deltaPhi_lepJets0", "deltaPhi_lepJets1", "deltaPhi_lepJets2" };

      // sanity checks
      if (theInputVars.size() <= 0) {
         std::cout << "Problem in class \"" << fClassName << "\": empty input vector" << std::endl;
         fStatusIsClean = false;
      }

      if (theInputVars.size() != fNvars) {
         std::cout << "Problem in class \"" << fClassName << "\": mismatch in number of input values: "
                   << theInputVars.size() << " != " << fNvars << std::endl;
         fStatusIsClean = false;
      }

      // validate input variables
      for (size_t ivar = 0; ivar < theInputVars.size(); ivar++) {
         if (theInputVars[ivar] != inputVars[ivar]) {
            std::cout << "Problem in class \"" << fClassName << "\": mismatch in input variable names" << std::endl
                      << " for variable [" << ivar << "]: " << theInputVars[ivar].c_str() << " != " << inputVars[ivar] << std::endl;
            fStatusIsClean = false;
         }
      }

      // initialize min and max vectors (for normalisation)
      fVmin[0] = 0;
      fVmax[0] = 0;
      fVmin[1] = 0;
      fVmax[1] = 0;
      fVmin[2] = 0;
      fVmax[2] = 0;
      fVmin[3] = 0;
      fVmax[3] = 0;
      fVmin[4] = 0;
      fVmax[4] = 0;
      fVmin[5] = 0;
      fVmax[5] = 0;
      fVmin[6] = 0;
      fVmax[6] = 0;
      fVmin[7] = 0;
      fVmax[7] = 0;
      fVmin[8] = 0;
      fVmax[8] = 0;
      fVmin[9] = 0;
      fVmax[9] = 0;
      fVmin[10] = 0;
      fVmax[10] = 0;
      fVmin[11] = 0;
      fVmax[11] = 0;
      fVmin[12] = 0;
      fVmax[12] = 0;
      fVmin[13] = 0;
      fVmax[13] = 0;
      fVmin[14] = 0;
      fVmax[14] = 0;
      fVmin[15] = 0;
      fVmax[15] = 0;
      fVmin[16] = 0;
      fVmax[16] = 0;
      fVmin[17] = 0;
      fVmax[17] = 0;
      fVmin[18] = 0;
      fVmax[18] = 0;

      // initialize input variable types
      fType[0] = 'F';
      fType[1] = 'F';
      fType[2] = 'F';
      fType[3] = 'F';
      fType[4] = 'F';
      fType[5] = 'F';
      fType[6] = 'F';
      fType[7] = 'F';
      fType[8] = 'F';
      fType[9] = 'F';
      fType[10] = 'F';
      fType[11] = 'F';
      fType[12] = 'F';
      fType[13] = 'F';
      fType[14] = 'F';
      fType[15] = 'F';
      fType[16] = 'F';
      fType[17] = 'F';
      fType[18] = 'F';

      // initialize constants
      Initialize();

   }

   // destructor
   virtual ~ReadBDT() {
      Clear(); // method-specific
   }

   // the classifier response
   // "inputValues" is a vector of input values in the same order as the 
   // variables given to the constructor
   double GetMvaValue( const std::vector<double>& inputValues ) const;

 private:

   // method-specific destructor
   void Clear();

   // common member variables
   const char* fClassName;

   const size_t fNvars;
   size_t GetNvar()           const { return fNvars; }
   char   GetType( int ivar ) const { return fType[ivar]; }

   // normalisation of input variables
   const bool fIsNormalised;
   bool IsNormalised() const { return fIsNormalised; }
   double fVmin[19];
   double fVmax[19];
   double NormVariable( double x, double xmin, double xmax ) const {
      // normalise to output range: [-1, 1]
      return 2*(x - xmin)/(xmax - xmin) - 1.0;
   }

   // type of input variable: 'F' or 'I'
   char   fType[19];

   // initialize internal variables
   void Initialize();
   double GetMvaValue__( const std::vector<double>& inputValues ) const;

   // private members (method specific)
   std::vector<BDTNode*> fForest;       // i.e. root nodes of decision trees
   std::vector<double>                fBoostWeights; // the weights applied in the individual boosts
};

double ReadBDT::GetMvaValue__( const std::vector<double>& inputValues ) const
{
   double myMVA = 0;
   double norm  = 0;
   for (unsigned int itree=0; itree<fForest.size(); itree++){
      BDTNode *current = fForest[itree];
      while (current->GetNodeType() == 0) { //intermediate node
         if (current->GoesRight(inputValues)) current=(BDTNode*)current->GetRight();
         else current=(BDTNode*)current->GetLeft();
      }
      myMVA += fBoostWeights[itree] *  current->GetNodeType();
      norm  += fBoostWeights[itree];
   }
   return myMVA /= norm;
};

void ReadBDT::Initialize()
{
  // itree = 0
  fBoostWeights.push_back(0.569724020411165);
  fForest.push_back( 
NN(
NN(
NN(
0, 
0, 
-1, 172.584, 0, 1, 0.784927,-99) , 
NN(
NN(
0, 
0, 
-1, 0, 1, 1, 0.630997,-99) , 
NN(
0, 
0, 
-1, 0, 1, -1, 0.363639,-99) , 
9, 238.499, 1, 0, 0.589867,-99) , 
8, 758.675, 0, 0, 0.691733,-99) , 
NN(
NN(
NN(
0, 
0, 
-1, 0, 1, 1, 0.512144,-99) , 
NN(
0, 
0, 
-1, 0, 1, -1, 0.329273,-99) , 
5, 216.902, 0, 0, 0.428321,-99) , 
NN(
0, 
0, 
-1, 352.521, 0, -1, 0.0983691,-99) , 
8, 486.451, 0, 0, 0.142905,-99) , 
8, 526.048, 0, 0, 0.474393,-99)    );
  // itree = 1
  fBoostWeights.push_back(0.387525);
  fForest.push_back( 
NN(
NN(
NN(
0, 
0, 
-1, 450.454, 1, 1, 0.706315,-99) , 
NN(
NN(
0, 
0, 
-1, 0, 1, 1, 0.570143,-99) , 
NN(
0, 
0, 
-1, 0, 1, -1, 0.419278,-99) , 
8, 651.445, 0, 0, 0.514885,-99) , 
3, 177.979, 0, 0, 0.600108,-99) , 
NN(
0, 
0, 
-1, 383.946, 0, -1, 0.221022,-99) , 
8, 529.023, 0, 0, 0.471955,-99)    );
  // itree = 2
  fBoostWeights.push_back(0.259958);
  fForest.push_back( 
NN(
NN(
NN(
0, 
0, 
-1, 359.487, 1, 1, 0.607876,-99) , 
NN(
0, 
0, 
-1, 161.254, 0, -1, 0.439059,-99) , 
3, 152.64, 0, 0, 0.522038,-99) , 
NN(
0, 
0, 
-1, 382.504, 0, -1, 0.184072,-99) , 
8, 441.907, 0, 0, 0.459515,-99)    );
  // itree = 3
  fBoostWeights.push_back(0.188294);
  fForest.push_back( 
NN(
NN(
NN(
0, 
0, 
-1, 163.248, 0, 1, 0.559461,-99) , 
NN(
NN(
0, 
0, 
-1, 0, 1, 1, 0.547864,-99) , 
NN(
0, 
0, 
-1, 0, 1, -1, 0.382304,-99) , 
8, 1025.21, 0, 0, 0.447001,-99) , 
13, 326.747, 1, 0, 0.533285,-99) , 
NN(
0, 
0, 
-1, 164.517, 0, -1, 0.153222,-99) , 
8, 410.425, 0, 0, 0.480941,-99)    );
  // itree = 4
  fBoostWeights.push_back(0.179817);
  fForest.push_back( 
NN(
NN(
NN(
NN(
0, 
0, 
-1, 0, 1, 1, 0.553156,-99) , 
NN(
0, 
0, 
-1, 0, 1, -1, 0.360628,-99) , 
4, 169.476, 0, 0, 0.531729,-99) , 
NN(
0, 
0, 
-1, 2.6126, 1, -1, 0.411418,-99) , 
5, 211.314, 0, 0, 0.495407,-99) , 
NN(
0, 
0, 
-1, 173.256, 0, -1, 0.22522,-99) , 
8, 441.907, 0, 0, 0.45139,-99)    );
  // itree = 5
  fBoostWeights.push_back(0.159119);
  fForest.push_back( 
NN(
NN(
NN(
NN(
0, 
0, 
-1, 0, 1, 1, 0.522094,-99) , 
NN(
0, 
0, 
-1, 0, 1, -1, 0.363643,-99) , 
10, 0.348748, 0, 0, 0.504774,-99) , 
NN(
0, 
0, 
-1, 598.91, 1, -1, 0.389812,-99) , 
1, 40.3109, 0, 0, 0.4651,-99) , 
NN(
0, 
0, 
-1, 217.309, 0, -1, 0.0847882,-99) , 
8, 354.224, 0, 0, 0.436723,-99)    );
  // itree = 6
  fBoostWeights.push_back(0.11399);
  fForest.push_back( 
NN(
NN(
NN(
NN(
0, 
0, 
-1, 0, 1, 1, 0.510738,-99) , 
NN(
0, 
0, 
-1, 0, 1, -1, 0.399429,-99) , 
13, 145.804, 0, 0, 0.482887,-99) , 
NN(
0, 
0, 
-1, 0, 1, -1, 0.280151,-99) , 
10, 0.289516, 0, 0, 0.466234,-99) , 
NN(
0, 
0, 
-1, 2.4102, 0, -1, 0.137267,-99) , 
8, 376.612, 0, 0, 0.438807,-99)    );
  // itree = 7
  fBoostWeights.push_back(0.174741);
  fForest.push_back( 
NN(
NN(
NN(
NN(
0, 
0, 
-1, 0, 1, 1, 0.548903,-99) , 
NN(
0, 
0, 
-1, 0, 1, -1, 0.435436,-99) , 
8, 850.046, 0, 0, 0.461557,-99) , 
NN(
0, 
0, 
-1, 0, 1, -1, 0.240368,-99) , 
9, 378.653, 1, 0, 0.450376,-99) , 
NN(
0, 
0, 
-1, 169.272, 0, -1, 0.209442,-99) , 
8, 365.962, 0, 0, 0.435525,-99)    );
  // itree = 8
  fBoostWeights.push_back(0.127473);
  fForest.push_back( 
NN(
NN(
NN(
NN(
0, 
0, 
-1, 0, 1, 1, 0.525121,-99) , 
NN(
0, 
0, 
-1, 0, 1, -1, 0.421368,-99) , 
4, 191.727, 0, 0, 0.496196,-99) , 
NN(
0, 
0, 
-1, 204.558, 1, -1, 0.368917,-99) , 
9, 281.405, 1, 0, 0.478708,-99) , 
NN(
0, 
0, 
-1, 0, 1, -1, 0.119889,-99) , 
8, 345.415, 0, 0, 0.460819,-99)    );
  // itree = 9
  fBoostWeights.push_back(0.138094);
  fForest.push_back( 
NN(
NN(
NN(
NN(
0, 
0, 
-1, 0, 1, 1, 0.581673,-99) , 
NN(
0, 
0, 
-1, 0, 1, -1, 0.459016,-99) , 
12, 116.136, 0, 0, 0.478806,-99) , 
NN(
0, 
0, 
-1, 176.594, 0, -1, 0.368597,-99) , 
4, 425.443, 1, 0, 0.459349,-99) , 
NN(
0, 
0, 
-1, 0, 1, -1, 0.116783,-99) , 
8, 345.415, 0, 0, 0.443906,-99)    );
  // itree = 10
  fBoostWeights.push_back(0.103187);
  fForest.push_back( 
NN(
NN(
NN(
NN(
0, 
0, 
-1, 0, 1, 1, 0.549383,-99) , 
NN(
0, 
0, 
-1, 0, 1, -1, 0.463548,-99) , 
4, 236.886, 0, 0, 0.508511,-99) , 
NN(
0, 
0, 
-1, 2.27891, 1, -1, 0.393452,-99) , 
4, 434.25, 1, 0, 0.489521,-99) , 
NN(
0, 
0, 
-1, 86.0512, 0, -1, 0.138863,-99) , 
8, 369.505, 0, 0, 0.468369,-99)    );
  // itree = 11
  fBoostWeights.push_back(0.106172);
  fForest.push_back( 
NN(
NN(
NN(
NN(
0, 
0, 
-1, 0, 1, 1, 0.558562,-99) , 
NN(
0, 
0, 
-1, 0, 1, -1, 0.470601,-99) , 
5, 339.886, 1, 0, 0.523782,-99) , 
NN(
NN(
0, 
0, 
-1, 0, 1, 1, 0.527174,-99) , 
NN(
0, 
0, 
-1, 0, 1, -1, 0.392596,-99) , 
6, 2.0818, 1, 0, 0.426154,-99) , 
2, 2.97226, 1, 0, 0.501682,-99) , 
NN(
0, 
0, 
-1, 0.584585, 0, -1, 0.324231,-99) , 
8, 488.621, 0, 0, 0.459829,-99)    );
  // itree = 12
  fBoostWeights.push_back(0.0771086);
  fForest.push_back( 
NN(
NN(
NN(
NN(
0, 
0, 
-1, 0, 1, 1, 0.521456,-99) , 
NN(
0, 
0, 
-1, 0, 1, -1, 0.351206,-99) , 
9, 331.393, 1, 0, 0.515365,-99) , 
NN(
NN(
0, 
0, 
-1, 0, 1, 1, 0.518474,-99) , 
NN(
0, 
0, 
-1, 0, 1, -1, 0.371225,-99) , 
8, 1149.59, 0, 0, 0.431017,-99) , 
7, 252.871, 1, 0, 0.496383,-99) , 
NN(
0, 
0, 
-1, 2.32496, 0, -1, 0.171991,-99) , 
8, 348.957, 0, 0, 0.476271,-99)    );
  // itree = 13
  fBoostWeights.push_back(0.0863087);
  fForest.push_back( 
NN(
NN(
NN(
NN(
0, 
0, 
-1, 0, 1, 1, 0.517731,-99) , 
NN(
0, 
0, 
-1, 0, 1, -1, 0.450663,-99) , 
2, 2.75031, 1, 0, 0.495311,-99) , 
NN(
NN(
0, 
0, 
-1, 0, 1, 1, 0.552043,-99) , 
NN(
0, 
0, 
-1, 0, 1, -1, 0.142838,-99) , 
5, 218.569, 0, 0, 0.345089,-99) , 
8, 374.747, 0, 0, 0.484614,-99) , 
NN(
0, 
0, 
-1, 0, 1, -1, 0.30156,-99) , 
10, 0.287559, 0, 0, 0.469118,-99)    );
  // itree = 14
  fBoostWeights.push_back(0.0778978);
  fForest.push_back( 
NN(
NN(
NN(
NN(
0, 
0, 
-1, 0, 1, 1, 0.580113,-99) , 
NN(
0, 
0, 
-1, 0, 1, -1, 0.482826,-99) , 
11, 110.249, 0, 0, 0.494061,-99) , 
NN(
0, 
0, 
-1, 712.634, 0, -1, 0.364388,-99) , 
13, 387.733, 1, 0, 0.47326,-99) , 
NN(
0, 
0, 
-1, 2.68536, 0, -1, 0.248509,-99) , 
8, 365.962, 0, 0, 0.4607,-99)    );
  // itree = 15
  fBoostWeights.push_back(0.0667705);
  fForest.push_back( 
NN(
NN(
NN(
NN(
0, 
0, 
-1, 0, 1, 1, 0.55465,-99) , 
NN(
0, 
0, 
-1, 0, 1, -1, 0.461428,-99) , 
13, 134.068, 0, 0, 0.531456,-99) , 
NN(
NN(
0, 
0, 
-1, 0, 1, 1, 0.500731,-99) , 
NN(
0, 
0, 
-1, 0, 1, -1, 0.361153,-99) , 
14, 147.862, 0, 0, 0.45471,-99) , 
13, 348.7, 1, 0, 0.516529,-99) , 
NN(
0, 
0, 
-1, 0, 1, -1, 0.333944,-99) , 
7, 80.6376, 0, 0, 0.508082,-99)    );
  // itree = 16
  fBoostWeights.push_back(0.0590607);
  fForest.push_back( 
NN(
NN(
NN(
NN(
0, 
0, 
-1, 0, 1, 1, 0.504852,-99) , 
NN(
0, 
0, 
-1, 0, 1, -1, 0.397892,-99) , 
4, 146.664, 0, 0, 0.494355,-99) , 
NN(
0, 
0, 
-1, 0, 1, -1, 0.271792,-99) , 
8, 345.415, 0, 0, 0.485751,-99) , 
NN(
0, 
0, 
-1, 0, 1, -1, 0.291418,-99) , 
10, 0.25012, 0, 0, 0.474317,-99)    );
  // itree = 17
  fBoostWeights.push_back(0.0654206);
  fForest.push_back( 
NN(
NN(
0, 
0, 
-1, 0, 1, 1, 0.591394,-99) , 
NN(
NN(
NN(
0, 
0, 
-1, 0, 1, 1, 0.576718,-99) , 
NN(
0, 
0, 
-1, 0, 1, -1, 0.474277,-99) , 
6, 2.5962, 0, 0, 0.491378,-99) , 
NN(
0, 
0, 
-1, 680.609, 0, -1, 0.392658,-99) , 
4, 391.563, 1, 0, 0.474812,-99) , 
0, 246.619, 0, 0, 0.48272,-99)    );
  // itree = 18
  fBoostWeights.push_back(0.0718311);
  fForest.push_back( 
NN(
NN(
NN(
NN(
0, 
0, 
-1, 0, 1, 1, 0.532174,-99) , 
NN(
0, 
0, 
-1, 0, 1, -1, 0.463189,-99) , 
9, 169.313, 1, 0, 0.503993,-99) , 
NN(
NN(
0, 
0, 
-1, 0, 1, 1, 0.542977,-99) , 
NN(
0, 
0, 
-1, 0, 1, -1, 0.294838,-99) , 
6, 2.52473, 0, 0, 0.38535,-99) , 
7, 89.3339, 0, 0, 0.494411,-99) , 
NN(
0, 
0, 
-1, 0, 1, -1, 0.324818,-99) , 
10, 0.288961, 0, 0, 0.479646,-99)    );
  // itree = 19
  fBoostWeights.push_back(0.0645507);
  fForest.push_back( 
NN(
NN(
NN(
NN(
0, 
0, 
-1, 0, 1, 1, 0.527249,-99) , 
NN(
0, 
0, 
-1, 0, 1, -1, 0.47037,-99) , 
8, 611.213, 0, 0, 0.501369,-99) , 
NN(
0, 
0, 
-1, 907.741, 0, -1, 0.407892,-99) , 
4, 526.035, 1, 0, 0.492851,-99) , 
NN(
0, 
0, 
-1, 0, 1, -1, 0.297077,-99) , 
8, 343.579, 0, 0, 0.484639,-99)    );
  // itree = 20
  fBoostWeights.push_back(0.0306687);
  fForest.push_back( 
NN(
NN(
NN(
0, 
0, 
-1, 2.70831, 0, 1, 0.58709,-99) , 
NN(
0, 
0, 
-1, 1.66315, 1, -1, 0.478781,-99) , 
10, 0.385559, 1, 0, 0.4883,-99) , 
NN(
NN(
NN(
0, 
0, 
-1, 0, 1, 1, 0.526609,-99) , 
NN(
0, 
0, 
-1, 0, 1, -1, 0.39106,-99) , 
17, 1.04662, 0, 0, 0.429129,-99) , 
NN(
0, 
0, 
-1, 0, 1, -1, 0.140105,-99) , 
8, 472.806, 0, 0, 0.366677,-99) , 
16, -2.77195, 0, 0, 0.472839,-99)    );
  // itree = 21
  fBoostWeights.push_back(0.0691276);
  fForest.push_back( 
NN(
NN(
NN(
NN(
0, 
0, 
-1, 0, 1, 1, 0.530101,-99) , 
NN(
0, 
0, 
-1, 0, 1, -1, 0.450639,-99) , 
13, 121.614, 0, 0, 0.512605,-99) , 
NN(
0, 
0, 
-1, 134.304, 0, -1, 0.440811,-99) , 
13, 299.833, 1, 0, 0.493611,-99) , 
NN(
0, 
0, 
-1, 0, 1, -1, 0.258301,-99) , 
8, 339.827, 0, 0, 0.485994,-99)    );
  // itree = 22
  fBoostWeights.push_back(0.0387156);
  fForest.push_back( 
NN(
NN(
NN(
0, 
0, 
-1, 63.1242, 1, 1, 0.511661,-99) , 
NN(
0, 
0, 
-1, 0, 1, -1, 0.357701,-99) , 
8, 365.962, 0, 0, 0.503253,-99) , 
NN(
0, 
0, 
-1, 110.228, 0, -1, 0.374042,-99) , 
2, 0.924886, 0, 0, 0.489992,-99)    );
  // itree = 23
  fBoostWeights.push_back(0.0299811);
  fForest.push_back( 
NN(
NN(
NN(
NN(
0, 
0, 
-1, 0, 1, 1, 0.509323,-99) , 
NN(
0, 
0, 
-1, 0, 1, -1, 0.423796,-99) , 
1, 193.315, 1, 0, 0.499326,-99) , 
NN(
0, 
0, 
-1, 0, 1, -1, 0.361615,-99) , 
6, 3.0516, 1, 0, 0.493743,-99) , 
NN(
NN(
0, 
0, 
-1, 0, 1, 1, 0.555847,-99) , 
NN(
0, 
0, 
-1, 0, 1, -1, 0.109202,-99) , 
5, 205.768, 0, 0, 0.339143,-99) , 
8, 360.868, 0, 0, 0.485225,-99)    );
  // itree = 24
  fBoostWeights.push_back(0.00162467);
  fForest.push_back( 
NN(
NN(
0, 
0, 
-1, 0, 1, 1, 0.771987,-99) , 
NN(
NN(
NN(
0, 
0, 
-1, 0, 1, 1, 0.501886,-99) , 
NN(
0, 
0, 
-1, 0, 1, -1, 0.340595,-99) , 
2, 0.625486, 0, 0, 0.493329,-99) , 
NN(
0, 
0, 
-1, 0, 1, -1, 0.330498,-99) , 
8, 369.505, 0, 0, 0.485638,-99) , 
10, 2.21753, 0, 0, 0.495966,-99)    );
  // itree = 25
  fBoostWeights.push_back(0.0678235);
  fForest.push_back( 
NN(
NN(
NN(
NN(
0, 
0, 
-1, 0, 1, 1, 0.522912,-99) , 
NN(
0, 
0, 
-1, 0, 1, -1, 0.441618,-99) , 
4, 355.726, 1, 0, 0.501553,-99) , 
NN(
0, 
0, 
-1, 711.102, 0, -1, 0.419419,-99) , 
1, 155.528, 1, 0, 0.487648,-99) , 
NN(
NN(
0, 
0, 
-1, 0, 1, 1, 0.518632,-99) , 
NN(
0, 
0, 
-1, 0, 1, -1, 0.19835,-99) , 
16, 1.66309, 0, 0, 0.343125,-99) , 
8, 394.505, 0, 0, 0.476665,-99)    );
  // itree = 26
  fBoostWeights.push_back(0.0762434);
  fForest.push_back( 
NN(
NN(
NN(
0, 
0, 
-1, 0, 1, 1, 0.55395,-99) , 
NN(
0, 
0, 
-1, -3.01838, 0, -1, 0.46706,-99) , 
0, 227.151, 0, 0, 0.474824,-99) , 
NN(
0, 
0, 
-1, 210.1, 0, -1, 0.295674,-99) , 
8, 374.906, 0, 0, 0.462574,-99)    );
  // itree = 27
  fBoostWeights.push_back(0.0423612);
  fForest.push_back( 
NN(
NN(
NN(
NN(
0, 
0, 
-1, 0, 1, 1, 0.632044,-99) , 
NN(
0, 
0, 
-1, 0, 1, -1, 0.495352,-99) , 
4, 207.2, 1, 0, 0.541236,-99) , 
NN(
0, 
0, 
-1, 155.528, 1, -1, 0.478608,-99) , 
12, 111.594, 0, 0, 0.491043,-99) , 
NN(
0, 
0, 
-1, 0, 1, -1, 0.359074,-99) , 
8, 364.62, 0, 0, 0.484862,-99)    );
  // itree = 28
  fBoostWeights.push_back(0.052388);
  fForest.push_back( 
NN(
NN(
NN(
NN(
0, 
0, 
-1, 0, 1, 1, 0.51352,-99) , 
NN(
0, 
0, 
-1, 0, 1, -1, 0.39468,-99) , 
2, 3.4853, 1, 0, 0.507936,-99) , 
NN(
0, 
0, 
-1, 0, 1, -1, 0.264096,-99) , 
8, 345.415, 0, 0, 0.499942,-99) , 
NN(
0, 
0, 
-1, 2.62222, 0, -1, 0.396053,-99) , 
16, 2.52559, 1, 0, 0.477605,-99)    );
  // itree = 29
  fBoostWeights.push_back(0.0352548);
  fForest.push_back( 
NN(
NN(
NN(
NN(
0, 
0, 
-1, 0, 1, 1, 0.630387,-99) , 
NN(
0, 
0, 
-1, 0, 1, -1, 0.497864,-99) , 
10, 0.431173, 1, 0, 0.503333,-99) , 
NN(
0, 
0, 
-1, 352.711, 0, -1, 0.426558,-99) , 
16, -2.64876, 0, 0, 0.491877,-99) , 
NN(
NN(
0, 
0, 
-1, 0, 1, 1, 0.526413,-99) , 
NN(
0, 
0, 
-1, 0, 1, -1, 0.265301,-99) , 
18, 0.0618269, 0, 0, 0.366315,-99) , 
11, 20.3551, 0, 0, 0.478012,-99)    );
  // itree = 30
  fBoostWeights.push_back(0.0473231);
  fForest.push_back( 
NN(
NN(
NN(
NN(
0, 
0, 
-1, 0, 1, 1, 0.524763,-99) , 
NN(
0, 
0, 
-1, 0, 1, -1, 0.37569,-99) , 
6, 3.05242, 1, 0, 0.518154,-99) , 
NN(
0, 
0, 
-1, 102.889, 0, -1, 0.422125,-99) , 
16, -2.64876, 0, 0, 0.503836,-99) , 
NN(
NN(
0, 
0, 
-1, 0, 1, 1, 0.604323,-99) , 
NN(
0, 
0, 
-1, 0, 1, -1, 0.102488,-99) , 
6, 2.49267, 0, 0, 0.338355,-99) , 
8, 360.868, 0, 0, 0.493876,-99)    );
  // itree = 31
  fBoostWeights.push_back(0.0422674);
  fForest.push_back( 
NN(
NN(
NN(
NN(
0, 
0, 
-1, 0, 1, 1, 0.521465,-99) , 
NN(
0, 
0, 
-1, 0, 1, -1, 0.455052,-99) , 
17, 1.78638, 1, 0, 0.506291,-99) , 
NN(
0, 
0, 
-1, 0, 1, -1, 0.289829,-99) , 
8, 348.957, 0, 0, 0.499477,-99) , 
NN(
0, 
0, 
-1, 0, 1, -1, 0.286881,-99) , 
10, 0.252314, 0, 0, 0.484787,-99)    );
  // itree = 32
  fBoostWeights.push_back(0.0297488);
  fForest.push_back( 
NN(
NN(
NN(
0, 
0, 
-1, 15.0877, 1, 1, 0.513132,-99) , 
NN(
0, 
0, 
-1, -0.43123, 0, -1, 0.429247,-99) , 
18, 2.03273, 1, 0, 0.496147,-99) , 
NN(
0, 
0, 
-1, 0, 1, -1, 0.322869,-99) , 
10, 0.249853, 0, 0, 0.484447,-99)    );
  // itree = 33
  fBoostWeights.push_back(0.0532786);
  fForest.push_back( 
NN(
NN(
NN(
NN(
0, 
0, 
-1, 0, 1, 1, 0.521659,-99) , 
NN(
0, 
0, 
-1, 0, 1, -1, 0.47278,-99) , 
5, 288.895, 0, 0, 0.495973,-99) , 
NN(
0, 
0, 
-1, 3.0432, 1, -1, 0.413305,-99) , 
17, -2.52553, 0, 0, 0.485937,-99) , 
NN(
0, 
0, 
-1, 0, 1, -1, 0.346727,-99) , 
10, 0.249853, 0, 0, 0.477727,-99)    );
  // itree = 34
  fBoostWeights.push_back(0.0340113);
  fForest.push_back( 
NN(
NN(
NN(
NN(
0, 
0, 
-1, 0, 1, 1, 0.511663,-99) , 
NN(
0, 
0, 
-1, 0, 1, -1, 0.425903,-99) , 
7, 302.706, 1, 0, 0.503941,-99) , 
NN(
0, 
0, 
-1, 121.069, 0, -1, 0.424416,-99) , 
13, 420.043, 1, 0, 0.494178,-99) , 
NN(
0, 
0, 
-1, -0.184883, 1, -1, 0.370933,-99) , 
8, 374.747, 0, 0, 0.487274,-99)    );
  // itree = 35
  fBoostWeights.push_back(0.0630253);
  fForest.push_back( 
NN(
NN(
0, 
0, 
-1, 0, 1, 1, 0.60418,-99) , 
NN(
NN(
NN(
0, 
0, 
-1, 0, 1, 1, 0.566488,-99) , 
NN(
0, 
0, 
-1, 0, 1, -1, 0.478154,-99) , 
9, 56.8677, 1, 0, 0.489806,-99) , 
NN(
0, 
0, 
-1, 0, 1, -1, 0.35455,-99) , 
4, 119.258, 0, 0, 0.483693,-99) , 
8, 1451.97, 0, 0, 0.488587,-99)    );
  // itree = 36
  fBoostWeights.push_back(0.021821);
  fForest.push_back( 
NN(
NN(
NN(
NN(
0, 
0, 
-1, 0, 1, 1, 0.509134,-99) , 
NN(
0, 
0, 
-1, 0, 1, -1, 0.392754,-99) , 
2, 0.643607, 0, 0, 0.503628,-99) , 
NN(
0, 
0, 
-1, 428.999, 0, -1, 0.398941,-99) , 
4, 142.21, 0, 0, 0.493748,-99) , 
NN(
0, 
0, 
-1, 0, 1, -1, 0.317104,-99) , 
14, 47.3434, 0, 0, 0.486242,-99)    );
  // itree = 37
  fBoostWeights.push_back(0.0379748);
  fForest.push_back( 
NN(
NN(
0, 
0, 
-1, 0, 1, 1, 0.701899,-99) , 
NN(
NN(
0, 
0, 
-1, 5.74818, 1, 1, 0.543106,-99) , 
NN(
0, 
0, 
-1, 36.6288, 0, -1, 0.475285,-99) , 
12, 26.6494, 1, 0, 0.486148,-99) , 
10, 2.18269, 0, 0, 0.492448,-99)    );
  // itree = 38
  fBoostWeights.push_back(0.0337331);
  fForest.push_back( 
NN(
NN(
NN(
NN(
0, 
0, 
-1, 0, 1, 1, 0.528051,-99) , 
NN(
0, 
0, 
-1, 0, 1, -1, 0.470723,-99) , 
18, 2.03281, 1, 0, 0.516493,-99) , 
NN(
NN(
0, 
0, 
-1, 0, 1, 1, 0.501627,-99) , 
NN(
0, 
0, 
-1, 0, 1, -1, 0.398908,-99) , 
8, 686.166, 0, 0, 0.443423,-99) , 
6, 2.74177, 1, 0, 0.50678,-99) , 
NN(
0, 
0, 
-1, 0.0615744, 0, -1, 0.34802,-99) , 
8, 374.906, 0, 0, 0.4983,-99)    );
  // itree = 39
  fBoostWeights.push_back(0.0469567);
  fForest.push_back( 
NN(
NN(
NN(
0, 
0, 
-1, 181.046, 0, 1, 0.599818,-99) , 
NN(
0, 
0, 
-1, 346.379, 0, -1, 0.435068,-99) , 
14, 174.839, 0, 0, 0.541245,-99) , 
NN(
NN(
NN(
0, 
0, 
-1, 0, 1, 1, 0.520179,-99) , 
NN(
0, 
0, 
-1, 0, 1, -1, 0.449243,-99) , 
11, 50.3324, 1, 0, 0.488491,-99) , 
NN(
0, 
0, 
-1, -2.03277, 0, -1, 0.393216,-99) , 
13, 386.865, 1, 0, 0.479067,-99) , 
15, 212.491, 0, 0, 0.491637,-99)    );
  // itree = 40
  fBoostWeights.push_back(0.0273625);
  fForest.push_back( 
NN(
NN(
NN(
0, 
0, 
-1, 0, 1, 1, 0.608693,-99) , 
NN(
0, 
0, 
-1, 443.014, 1, -1, 0.481709,-99) , 
10, 0.305976, 1, 0, 0.488263,-99) , 
NN(
0, 
0, 
-1, 26.1864, 0, -1, 0.386292,-99) , 
15, 61.1549, 0, 0, 0.479215,-99)    );
  // itree = 41
  fBoostWeights.push_back(0.0199889);
  fForest.push_back( 
NN(
NN(
NN(
NN(
0, 
0, 
-1, 0, 1, 1, 0.587026,-99) , 
NN(
0, 
0, 
-1, 0, 1, -1, 0.49471,-99) , 
10, 1.91848, 0, 0, 0.499006,-99) , 
NN(
NN(
0, 
0, 
-1, 0, 1, 1, 0.575026,-99) , 
NN(
0, 
0, 
-1, 0, 1, -1, 0.331288,-99) , 
8, 383.613, 0, 0, 0.419098,-99) , 
8, 404.718, 0, 0, 0.491555,-99) , 
NN(
0, 
0, 
-1, 253.989, 1, -1, 0.396346,-99) , 
2, 0.970829, 0, 0, 0.480709,-99)    );
  // itree = 42
  fBoostWeights.push_back(0.0520209);
  fForest.push_back( 
NN(
NN(
NN(
NN(
0, 
0, 
-1, 0, 1, 1, 0.535477,-99) , 
NN(
0, 
0, 
-1, 0, 1, -1, 0.416636,-99) , 
13, 517.736, 1, 0, 0.52905,-99) , 
NN(
NN(
0, 
0, 
-1, 0, 1, 1, 0.544347,-99) , 
NN(
0, 
0, 
-1, 0, 1, -1, 0.447215,-99) , 
15, 243.279, 0, 0, 0.465311,-99) , 
1, 106.371, 1, 0, 0.510496,-99) , 
NN(
NN(
0, 
0, 
-1, 0, 1, 1, 0.584763,-99) , 
NN(
0, 
0, 
-1, 0, 1, -1, 0.310072,-99) , 
6, 2.53744, 0, 0, 0.41568,-99) , 
8, 403.916, 0, 0, 0.50271,-99)    );
  // itree = 43
  fBoostWeights.push_back(0.0275693);
  fForest.push_back( 
NN(
NN(
NN(
0, 
0, 
-1, 0, 1, 1, 0.607899,-99) , 
NN(
NN(
0, 
0, 
-1, 0, 1, 1, 0.503878,-99) , 
NN(
0, 
0, 
-1, 0, 1, -1, 0.401461,-99) , 
2, 3.36064, 1, 0, 0.495581,-99) , 
10, 1.84964, 0, 0, 0.501808,-99) , 
NN(
0, 
0, 
-1, 396.107, 0, -1, 0.41975,-99) , 
4, 161.972, 0, 0, 0.489218,-99)    );
  // itree = 44
  fBoostWeights.push_back(0.0415526);
  fForest.push_back( 
NN(
NN(
NN(
0, 
0, 
-1, 157.132, 0, 1, 0.572348,-99) , 
NN(
0, 
0, 
-1, 148.661, 0, -1, 0.458157,-99) , 
5, 318.553, 0, 0, 0.539788,-99) , 
NN(
0, 
0, 
-1, 0.312984, 0, -1, 0.474324,-99) , 
8, 906.456, 0, 0, 0.48816,-99)    );
  // itree = 45
  fBoostWeights.push_back(0.043208);
  fForest.push_back( 
NN(
NN(
NN(
0, 
0, 
-1, 35.3725, 1, 1, 0.612092,-99) , 
NN(
NN(
0, 
0, 
-1, 0, 1, 1, 0.519224,-99) , 
NN(
0, 
0, 
-1, 0, 1, -1, 0.451535,-99) , 
5, 194.315, 0, 0, 0.503814,-99) , 
5, 144.636, 1, 0, 0.515781,-99) , 
NN(
0, 
0, 
-1, 175.976, 0, -1, 0.430135,-99) , 
7, 325.188, 1, 0, 0.507034,-99)    );
  // itree = 46
  fBoostWeights.push_back(0.0353758);
  fForest.push_back( 
NN(
NN(
NN(
NN(
0, 
0, 
-1, 0, 1, 1, 0.513178,-99) , 
NN(
0, 
0, 
-1, 0, 1, -1, 0.421107,-99) , 
11, 17.683, 0, 0, 0.506951,-99) , 
NN(
0, 
0, 
-1, 0, 1, -1, 0.40731,-99) , 
9, 393.957, 1, 0, 0.502863,-99) , 
NN(
0, 
0, 
-1, 0, 1, -1, 0.280436,-99) , 
8, 340.154, 0, 0, 0.495614,-99)    );
  // itree = 47
  fBoostWeights.push_back(0.0133056);
  fForest.push_back( 
NN(
NN(
NN(
0, 
0, 
-1, 0.38949, 1, 1, 0.508391,-99) , 
NN(
0, 
0, 
-1, 572.224, 0, -1, 0.414459,-99) , 
17, -2.64878, 0, 0, 0.499027,-99) , 
NN(
NN(
NN(
0, 
0, 
-1, 0, 1, 1, 0.543966,-99) , 
NN(
0, 
0, 
-1, 0, 1, -1, 0.432736,-99) , 
6, 2.20653, 0, 0, 0.479121,-99) , 
NN(
0, 
0, 
-1, 0, 1, -1, 0.314023,-99) , 
6, 2.48735, 1, 0, 0.420482,-99) , 
2, 1.04972, 0, 0, 0.488858,-99)    );
  // itree = 48
  fBoostWeights.push_back(0.00399605);
  fForest.push_back( 
NN(
NN(
NN(
0, 
0, 
-1, 0, 1, 1, 0.602111,-99) , 
NN(
NN(
0, 
0, 
-1, 0, 1, 1, 0.510632,-99) , 
NN(
0, 
0, 
-1, 0, 1, -1, 0.43885,-99) , 
4, 447.227, 1, 0, 0.500928,-99) , 
10, 0.289847, 1, 0, 0.506644,-99) , 
NN(
0, 
0, 
-1, 0, 1, -1, 0.358698,-99) , 
8, 365.962, 0, 0, 0.499557,-99)    );
  // itree = 49
  fBoostWeights.push_back(0.0507089);
  fForest.push_back( 
NN(
NN(
NN(
NN(
0, 
0, 
-1, 0, 1, 1, 0.567048,-99) , 
NN(
0, 
0, 
-1, 0, 1, -1, 0.494008,-99) , 
11, 26.432, 1, 0, 0.501457,-99) , 
NN(
0, 
0, 
-1, 541.705, 0, -1, 0.415223,-99) , 
15, 62.0902, 0, 0, 0.494305,-99) , 
NN(
NN(
NN(
0, 
0, 
-1, 0, 1, 1, 0.644007,-99) , 
NN(
0, 
0, 
-1, 0, 1, -1, 0.4279,-99) , 
2, 1.86951, 1, 0, 0.535892,-99) , 
NN(
0, 
0, 
-1, 27.0598, 0, -1, 0.326597,-99) , 
13, 184.234, 1, 0, 0.413082,-99) , 
14, 75.4099, 0, 0, 0.48409,-99)    );
  // itree = 50
  fBoostWeights.push_back(0.0247126);
  fForest.push_back( 
NN(
NN(
0, 
0, 
-1, 0, 1, 1, 0.703483,-99) , 
NN(
NN(
0, 
0, 
-1, 1.6646, 0, 1, 0.527767,-99) , 
NN(
0, 
0, 
-1, 2.61975, 1, -1, 0.471488,-99) , 
17, -1.29355, 1, 0, 0.489111,-99) , 
10, 2.17581, 0, 0, 0.495833,-99)    );
  // itree = 51
  fBoostWeights.push_back(0.0300249);
  fForest.push_back( 
NN(
NN(
NN(
0, 
0, 
-1, 0, 1, 1, 0.613554,-99) , 
NN(
NN(
0, 
0, 
-1, 0, 1, 1, 0.523145,-99) , 
NN(
0, 
0, 
-1, 0, 1, -1, 0.478662,-99) , 
1, 52.9715, 0, 0, 0.505171,-99) , 
5, 118.592, 1, 0, 0.509338,-99) , 
NN(
0, 
0, 
-1, 0, 1, -1, 0.368432,-99) , 
15, 47.834, 0, 0, 0.500951,-99)    );
  // itree = 52
  fBoostWeights.push_back(0.0247546);
  fForest.push_back( 
NN(
NN(
NN(
NN(
0, 
0, 
-1, 0, 1, 1, 0.515101,-99) , 
NN(
0, 
0, 
-1, 0, 1, -1, 0.460337,-99) , 
16, 2.27919, 1, 0, 0.501779,-99) , 
NN(
0, 
0, 
-1, 0, 1, -1, 0.385496,-99) , 
8, 374.747, 0, 0, 0.495739,-99) , 
NN(
0, 
0, 
-1, 0, 1, -1, 0.293196,-99) , 
14, 48.53, 0, 0, 0.484792,-99)    );
  // itree = 53
  fBoostWeights.push_back(0.0259907);
  fForest.push_back( 
NN(
NN(
0, 
0, 
-1, 0, 1, 1, 0.703639,-99) , 
NN(
NN(
NN(
0, 
0, 
-1, 0, 1, 1, 0.508277,-99) , 
NN(
0, 
0, 
-1, 0, 1, -1, 0.446143,-99) , 
17, 2.52557, 1, 0, 0.500716,-99) , 
NN(
0, 
0, 
-1, 61.1655, 0, -1, 0.404592,-99) , 
2, 0.987568, 0, 0, 0.489548,-99) , 
10, 2.22514, 0, 0, 0.494883,-99)    );
  // itree = 54
  fBoostWeights.push_back(0.0203823);
  fForest.push_back( 
NN(
NN(
NN(
NN(
0, 
0, 
-1, 0, 1, 1, 0.520995,-99) , 
NN(
0, 
0, 
-1, 0, 1, -1, 0.456802,-99) , 
13, 104.793, 0, 0, 0.511804,-99) , 
NN(
0, 
0, 
-1, 381.947, 1, -1, 0.453112,-99) , 
16, -2.40237, 0, 0, 0.499055,-99) , 
NN(
0, 
0, 
-1, 0, 1, -1, 0.28846,-99) , 
8, 354.224, 0, 0, 0.492215,-99)    );
  // itree = 55
  fBoostWeights.push_back(0.03098);
  fForest.push_back( 
NN(
NN(
NN(
NN(
0, 
0, 
-1, 0, 1, 1, 0.53918,-99) , 
NN(
0, 
0, 
-1, 0, 1, -1, 0.479813,-99) , 
6, 2.34015, 0, 0, 0.502323,-99) , 
NN(
0, 
0, 
-1, 2.4023, 1, -1, 0.442357,-99) , 
4, 376.733, 1, 0, 0.489446,-99) , 
NN(
0, 
0, 
-1, 0, 1, -1, 0.265422,-99) , 
14, 43.0501, 0, 0, 0.477903,-99)    );
  // itree = 56
  fBoostWeights.push_back(0.0527323);
  fForest.push_back( 
NN(
NN(
NN(
NN(
0, 
0, 
-1, 0, 1, 1, 0.612435,-99) , 
NN(
0, 
0, 
-1, 0, 1, -1, 0.445194,-99) , 
17, 2.27908, 1, 0, 0.575213,-99) , 
NN(
NN(
0, 
0, 
-1, 0, 1, 1, 0.507089,-99) , 
NN(
0, 
0, 
-1, 0, 1, -1, 0.373552,-99) , 
8, 463.821, 0, 0, 0.483843,-99) , 
2, 3.01534, 0, 0, 0.504381,-99) , 
NN(
NN(
NN(
0, 
0, 
-1, 0, 1, 1, 0.514124,-99) , 
NN(
0, 
0, 
-1, 0, 1, -1, 0.426216,-99) , 
0, 147.035, 0, 0, 0.472344,-99) , 
NN(
0, 
0, 
-1, 0, 1, -1, 0.291121,-99) , 
14, 90.52, 0, 0, 0.440182,-99) , 
4, 363.212, 1, 0, 0.488907,-99)    );
  // itree = 57
  fBoostWeights.push_back(0.0176983);
  fForest.push_back( 
NN(
NN(
NN(
NN(
0, 
0, 
-1, 0, 1, 1, 0.610772,-99) , 
NN(
0, 
0, 
-1, 0, 1, -1, 0.480605,-99) , 
8, 539.116, 1, 0, 0.537141,-99) , 
NN(
NN(
0, 
0, 
-1, 0, 1, 1, 0.500575,-99) , 
NN(
0, 
0, 
-1, 0, 1, -1, 0.427178,-99) , 
18, 2.15598, 1, 0, 0.488117,-99) , 
0, 73.5804, 1, 0, 0.500534,-99) , 
NN(
NN(
0, 
0, 
-1, 0, 1, 1, 0.553934,-99) , 
NN(
0, 
0, 
-1, 149.052, 0, -1, 0.406055,-99) , 
3, 87.9999, 1, 0, 0.442327,-99) , 
17, -2.03276, 0, 0, 0.488898,-99)    );
  // itree = 58
  fBoostWeights.push_back(0.0493238);
  fForest.push_back( 
NN(
NN(
NN(
0, 
0, 
-1, 0, 1, 1, 0.618109,-99) , 
NN(
NN(
0, 
0, 
-1, 0, 1, 1, 0.559378,-99) , 
NN(
0, 
0, 
-1, 0, 1, -1, 0.445216,-99) , 
2, 1.94084, 0, 0, 0.499874,-99) , 
7, 341.609, 1, 0, 0.555561,-99) , 
NN(
NN(
NN(
0, 
0, 
-1, 0, 1, 1, 0.519315,-99) , 
NN(
0, 
0, 
-1, 0, 1, -1, 0.375011,-99) , 
4, 410.365, 1, 0, 0.511217,-99) , 
NN(
NN(
0, 
0, 
-1, 0, 1, 1, 0.551183,-99) , 
NN(
0, 
0, 
-1, 0, 1, -1, 0.426631,-99) , 
8, 492.782, 1, 0, 0.446528,-99) , 
3, 169.296, 1, 0, 0.488679,-99) , 
8, 1035.28, 0, 0, 0.49826,-99)    );
  // itree = 59
  fBoostWeights.push_back(0.0304683);
  fForest.push_back( 
NN(
NN(
NN(
NN(
0, 
0, 
-1, 0, 1, 1, 0.513599,-99) , 
NN(
0, 
0, 
-1, 0, 1, -1, 0.369506,-99) , 
6, 1.41747, 0, 0, 0.507941,-99) , 
NN(
0, 
0, 
-1, 0, 1, -1, 0.3535,-99) , 
8, 372.607, 0, 0, 0.501637,-99) , 
NN(
NN(
NN(
0, 
0, 
-1, 0, 1, 1, 0.528777,-99) , 
NN(
0, 
0, 
-1, 0, 1, -1, 0.414429,-99) , 
8, 519.714, 1, 0, 0.452511,-99) , 
NN(
0, 
0, 
-1, 0, 1, -1, 0.265573,-99) , 
2, 1.20234, 0, 0, 0.412011,-99) , 
6, 2.59284, 1, 0, 0.481102,-99)    );
  // itree = 60
  fBoostWeights.push_back(0.0424807);
  fForest.push_back( 
NN(
NN(
NN(
NN(
0, 
0, 
-1, 0, 1, 1, 0.590031,-99) , 
NN(
0, 
0, 
-1, 0, 1, -1, 0.484655,-99) , 
2, 3.46924, 0, 0, 0.48987,-99) , 
NN(
0, 
0, 
-1, 154.129, 0, -1, 0.420624,-99) , 
6, 2.76219, 1, 0, 0.480884,-99) , 
NN(
0, 
0, 
-1, 0, 1, -1, 0.296547,-99) , 
8, 369.505, 0, 0, 0.472915,-99)    );
  // itree = 61
  fBoostWeights.push_back(0.0365436);
  fForest.push_back( 
NN(
NN(
NN(
NN(
0, 
0, 
-1, 0, 1, 1, 0.540765,-99) , 
NN(
0, 
0, 
-1, 0, 1, -1, 0.496148,-99) , 
5, 212.05, 1, 0, 0.510444,-99) , 
NN(
0, 
0, 
-1, 100.03, 0, -1, 0.44185,-99) , 
17, -2.40239, 0, 0, 0.501026,-99) , 
NN(
0, 
0, 
-1, 80.1455, 0, -1, 0.383736,-99) , 
8, 400.026, 0, 0, 0.492566,-99)    );
  // itree = 62
  fBoostWeights.push_back(0.0448654);
  fForest.push_back( 
NN(
NN(
NN(
NN(
0, 
0, 
-1, 0, 1, 1, 0.567666,-99) , 
NN(
0, 
0, 
-1, 0, 1, -1, 0.492957,-99) , 
18, -0.677632, 0, 0, 0.539368,-99) , 
NN(
NN(
0, 
0, 
-1, 0, 1, 1, 0.504072,-99) , 
NN(
0, 
0, 
-1, 0, 1, -1, 0.350688,-99) , 
8, 732.899, 0, 0, 0.462458,-99) , 
14, 284.682, 1, 0, 0.521422,-99) , 
NN(
NN(
NN(
0, 
0, 
-1, 0, 1, 1, 0.533772,-99) , 
NN(
0, 
0, 
-1, 0, 1, -1, 0.441717,-99) , 
13, 189.44, 1, 0, 0.485204,-99) , 
NN(
0, 
0, 
-1, 0, 1, -1, 0.279205,-99) , 
4, 137.207, 0, 0, 0.467965,-99) , 
14, 129.46, 0, 0, 0.500807,-99)    );
  // itree = 63
  fBoostWeights.push_back(0.013591);
  fForest.push_back( 
NN(
NN(
NN(
NN(
0, 
0, 
-1, 0, 1, 1, 0.512533,-99) , 
NN(
0, 
0, 
-1, 0, 1, -1, 0.423715,-99) , 
2, 0.871424, 0, 0, 0.50493,-99) , 
NN(
0, 
0, 
-1, 736.146, 0, -1, 0.427424,-99) , 
13, 390.209, 1, 0, 0.494006,-99) , 
NN(
0, 
0, 
-1, 60.6217, 1, -1, 0.34944,-99) , 
8, 400.026, 0, 0, 0.484632,-99)    );
  // itree = 64
  fBoostWeights.push_back(0.0332098);
  fForest.push_back( 
NN(
NN(
NN(
NN(
0, 
0, 
-1, 0, 1, 1, 0.568293,-99) , 
NN(
0, 
0, 
-1, 0, 1, -1, 0.486218,-99) , 
10, 0.444167, 1, 0, 0.493665,-99) , 
NN(
0, 
0, 
-1, 0, 1, -1, 0.396225,-99) , 
1, 265.928, 1, 0, 0.487937,-99) , 
NN(
NN(
NN(
0, 
0, 
-1, 0, 1, 1, 0.554049,-99) , 
NN(
0, 
0, 
-1, 0, 1, -1, 0.433823,-99) , 
6, 2.21648, 1, 0, 0.494349,-99) , 
NN(
0, 
0, 
-1, 0, 1, -1, 0.206613,-99) , 
15, 38.9642, 0, 0, 0.375447,-99) , 
15, 62.0922, 0, 0, 0.476535,-99)    );
  // itree = 65
  fBoostWeights.push_back(0.0199361);
  fForest.push_back( 
NN(
NN(
NN(
0, 
0, 
-1, 1.56124, 1, 1, 0.510137,-99) , 
NN(
0, 
0, 
-1, -0.554353, 0, -1, 0.459406,-99) , 
17, -2.40229, 0, 0, 0.503277,-99) , 
NN(
0, 
0, 
-1, 0, 1, -1, 0.384641,-99) , 
15, 47.7997, 0, 0, 0.496882,-99)    );
  // itree = 66
  fBoostWeights.push_back(0);
  fForest.push_back( 
NN(
NN(
0, 
0, 
-1, 0, 1, 1, 0.639386,-99) , 
NN(
NN(
NN(
0, 
0, 
-1, 0, 1, 1, 0.503705,-99) , 
NN(
0, 
0, 
-1, 0, 1, -1, 0.432675,-99) , 
14, 63.045, 0, 0, 0.498032,-99) , 
NN(
0, 
0, 
-1, 0, 1, -1, 0.400522,-99) , 
2, 3.64107, 1, 0, 0.494792,-99) , 
10, 2.15884, 0, 0, 0.49906,-99)    );
  // itree = 67
  fBoostWeights.push_back(0.0200235);
  fForest.push_back( 
NN(
NN(
NN(
NN(
0, 
0, 
-1, 0, 1, 1, 0.574623,-99) , 
NN(
0, 
0, 
-1, 0, 1, -1, 0.494028,-99) , 
10, 0.313782, 1, 0, 0.498478,-99) , 
NN(
0, 
0, 
-1, 0, 1, -1, 0.41089,-99) , 
13, 70.1529, 0, 0, 0.494597,-99) , 
NN(
0, 
0, 
-1, 0, 1, -1, 0.413609,-99) , 
15, 49.0188, 0, 0, 0.490596,-99)    );
  // itree = 68
  fBoostWeights.push_back(0.0172225);
  fForest.push_back( 
NN(
NN(
NN(
0, 
0, 
-1, 897.787, 0, 1, 0.514262,-99) , 
NN(
NN(
0, 
0, 
-1, 0, 1, 1, 0.540502,-99) , 
NN(
0, 
0, 
-1, 0, 1, -1, 0.432832,-99) , 
8, 1395.53, 0, 0, 0.462476,-99) , 
7, 289.534, 1, 0, 0.506336,-99) , 
NN(
0, 
0, 
-1, 0, 1, -1, 0.398429,-99) , 
8, 357.766, 0, 0, 0.501827,-99)    );
  // itree = 69
  fBoostWeights.push_back(0.0214079);
  fForest.push_back( 
NN(
NN(
NN(
NN(
0, 
0, 
-1, 0, 1, 1, 0.558682,-99) , 
NN(
0, 
0, 
-1, 0, 1, -1, 0.492324,-99) , 
10, 1.61202, 0, 0, 0.500998,-99) , 
NN(
NN(
0, 
0, 
-1, 0, 1, 1, 0.507672,-99) , 
NN(
0, 
0, 
-1, 0, 1, -1, 0.256045,-99) , 
14, 110.228, 0, 0, 0.38564,-99) , 
2, 0.919373, 0, 0, 0.48821,-99) , 
NN(
0, 
0, 
-1, 0, 1, -1, 0.270949,-99) , 
8, 360.868, 0, 0, 0.478419,-99)    );
  // itree = 70
  fBoostWeights.push_back(0.00735024);
  fForest.push_back( 
NN(
NN(
NN(
0, 
0, 
-1, 251.68, 0, 1, 0.512317,-99) , 
NN(
0, 
0, 
-1, 0, 1, -1, 0.307919,-99) , 
7, 79.7916, 0, 0, 0.505716,-99) , 
NN(
NN(
NN(
0, 
0, 
-1, 0, 1, 1, 0.564631,-99) , 
NN(
0, 
0, 
-1, 0, 1, -1, 0.451419,-99) , 
15, 188.958, 0, 0, 0.482328,-99) , 
NN(
0, 
0, 
-1, 0, 1, -1, 0.285433,-99) , 
10, 0.533167, 0, 0, 0.425177,-99) , 
16, 2.52555, 1, 0, 0.489093,-99)    );
  // itree = 71
  fBoostWeights.push_back(0.0317318);
  fForest.push_back( 
NN(
NN(
NN(
NN(
0, 
0, 
-1, 0, 1, 1, 0.527635,-99) , 
NN(
0, 
0, 
-1, 0, 1, -1, 0.430681,-99) , 
9, 56.9534, 0, 0, 0.518404,-99) , 
NN(
NN(
0, 
0, 
-1, 0, 1, 1, 0.504811,-99) , 
NN(
0, 
0, 
-1, 0, 1, -1, 0.396356,-99) , 
1, 23.2863, 0, 0, 0.47445,-99) , 
5, 199.01, 0, 0, 0.505435,-99) , 
NN(
0, 
0, 
-1, 0, 1, -1, 0.376634,-99) , 
10, 0.25042, 0, 0, 0.498884,-99)    );
  // itree = 72
  fBoostWeights.push_back(0.0223006);
  fForest.push_back( 
NN(
NN(
NN(
0, 
0, 
-1, 0, 1, 1, 0.633682,-99) , 
NN(
NN(
0, 
0, 
-1, 0, 1, 1, 0.509765,-99) , 
NN(
0, 
0, 
-1, 0, 1, -1, 0.469658,-99) , 
4, 298.948, 0, 0, 0.484925,-99) , 
11, 201.139, 0, 0, 0.489329,-99) , 
NN(
0, 
0, 
-1, 0, 1, -1, 0.347672,-99) , 
10, 0.307907, 0, 0, 0.477239,-99)    );
  // itree = 73
  fBoostWeights.push_back(0.00913334);
  fForest.push_back( 
NN(
NN(
NN(
NN(
0, 
0, 
-1, 0, 1, 1, 0.658039,-99) , 
NN(
0, 
0, 
-1, 0, 1, -1, 0.444489,-99) , 
2, 2.40557, 1, 0, 0.572648,-99) , 
NN(
NN(
0, 
0, 
-1, 0, 1, 1, 0.502352,-99) , 
NN(
0, 
0, 
-1, 0, 1, -1, 0.440669,-99) , 
6, 1.80775, 0, 0, 0.49518,-99) , 
10, 0.416102, 1, 0, 0.501879,-99) , 
NN(
0, 
0, 
-1, 0, 1, -1, 0.384059,-99) , 
14, 46.9992, 0, 0, 0.497072,-99)    );
  // itree = 74
  fBoostWeights.push_back(0.0178876);
  fForest.push_back( 
NN(
NN(
NN(
NN(
0, 
0, 
-1, 0, 1, 1, 0.53231,-99) , 
NN(
0, 
0, 
-1, 0, 1, -1, 0.485542,-99) , 
18, -1.18497, 0, 0, 0.514144,-99) , 
NN(
NN(
0, 
0, 
-1, 0, 1, 1, 0.506828,-99) , 
NN(
0, 
0, 
-1, 0, 1, -1, 0.353775,-99) , 
12, 61.6314, 0, 0, 0.444828,-99) , 
18, 2.4023, 1, 0, 0.504082,-99) , 
NN(
0, 
0, 
-1, 624.715, 0, -1, 0.397499,-99) , 
2, 0.919322, 0, 0, 0.491994,-99)    );
  // itree = 75
  fBoostWeights.push_back(0.0400146);
  fForest.push_back( 
NN(
NN(
NN(
0, 
0, 
-1, 684.844, 0, 1, 0.578795,-99) , 
NN(
NN(
0, 
0, 
-1, 0, 1, 1, 0.576859,-99) , 
NN(
0, 
0, 
-1, 0, 1, -1, 0.475894,-99) , 
2, 1.54727, 1, 0, 0.498917,-99) , 
4, 213.999, 1, 0, 0.520343,-99) , 
NN(
0, 
0, 
-1, 265.166, 1, -1, 0.458711,-99) , 
15, 150.557, 0, 0, 0.483649,-99)    );
  // itree = 76
  fBoostWeights.push_back(0.0272662);
  fForest.push_back( 
NN(
NN(
NN(
NN(
0, 
0, 
-1, 0, 1, 1, 0.542194,-99) , 
NN(
0, 
0, 
-1, 0, 1, -1, 0.434609,-99) , 
1, 204.499, 1, 0, 0.528541,-99) , 
NN(
NN(
0, 
0, 
-1, 0, 1, 1, 0.517556,-99) , 
NN(
0, 
0, 
-1, 0, 1, -1, 0.393097,-99) , 
8, 692.009, 0, 0, 0.455153,-99) , 
18, 2.15598, 1, 0, 0.509696,-99) , 
NN(
0, 
0, 
-1, 305.046, 1, -1, 0.458777,-99) , 
15, 123.176, 0, 0, 0.487191,-99)    );
  // itree = 77
  fBoostWeights.push_back(0.0237525);
  fForest.push_back( 
NN(
NN(
0, 
0, 
-1, 2.17581, 0, 1, 0.527737,-99) , 
NN(
NN(
NN(
0, 
0, 
-1, 0, 1, 1, 0.533837,-99) , 
NN(
0, 
0, 
-1, 0, 1, -1, 0.380302,-99) , 
13, 165.945, 0, 0, 0.492727,-99) , 
NN(
0, 
0, 
-1, 0, 1, -1, 0.179836,-99) , 
14, 74.9057, 0, 0, 0.440359,-99) , 
4, 364.31, 1, 0, 0.505567,-99)    );
  // itree = 78
  fBoostWeights.push_back(0.0161536);
  fForest.push_back( 
NN(
NN(
NN(
NN(
0, 
0, 
-1, 0, 1, 1, 0.577719,-99) , 
NN(
0, 
0, 
-1, 0, 1, -1, 0.459653,-99) , 
13, 361.812, 1, 0, 0.553225,-99) , 
NN(
0, 
0, 
-1, 293.701, 1, -1, 0.488081,-99) , 
12, 26.6494, 1, 0, 0.49897,-99) , 
NN(
0, 
0, 
-1, 0, 1, -1, 0.278745,-99) , 
7, 79.8166, 0, 0, 0.492514,-99)    );
  // itree = 79
  fBoostWeights.push_back(0.0225654);
  fForest.push_back( 
NN(
NN(
0, 
0, 
-1, 0, 1, 1, 0.795375,-99) , 
NN(
NN(
NN(
0, 
0, 
-1, 0, 1, 1, 0.542321,-99) , 
NN(
0, 
0, 
-1, 0, 1, -1, 0.486587,-99) , 
8, 519.449, 1, 0, 0.499943,-99) , 
NN(
0, 
0, 
-1, 0, 1, -1, 0.356929,-99) , 
8, 357.766, 0, 0, 0.49489,-99) , 
10, 2.24184, 0, 0, 0.506326,-99)    );
  // itree = 80
  fBoostWeights.push_back(0.0299261);
  fForest.push_back( 
NN(
NN(
NN(
NN(
0, 
0, 
-1, 0, 1, 1, 0.55266,-99) , 
NN(
0, 
0, 
-1, 0, 1, -1, 0.46946,-99) , 
2, 1.61921, 0, 0, 0.524689,-99) , 
NN(
0, 
0, 
-1, 0, 1, -1, 0.41998,-99) , 
9, 394.234, 1, 0, 0.512755,-99) , 
NN(
0, 
0, 
-1, 430.115, 1, -1, 0.466978,-99) , 
8, 781.256, 0, 0, 0.48166,-99)    );
  // itree = 81
  fBoostWeights.push_back(0.0359621);
  fForest.push_back( 
NN(
NN(
NN(
NN(
0, 
0, 
-1, 0, 1, 1, 0.538481,-99) , 
NN(
0, 
0, 
-1, 0, 1, -1, 0.435154,-99) , 
9, 310.95, 1, 0, 0.526665,-99) , 
NN(
NN(
0, 
0, 
-1, 0, 1, 1, 0.506789,-99) , 
NN(
0, 
0, 
-1, 0, 1, -1, 0.440982,-99) , 
18, -0.800773, 0, 0, 0.482039,-99) , 
12, 76.4461, 1, 0, 0.506135,-99) , 
NN(
0, 
0, 
-1, 0, 1, -1, 0.399107,-99) , 
10, 0.25042, 0, 0, 0.500327,-99)    );
  // itree = 82
  fBoostWeights.push_back(0.0232706);
  fForest.push_back( 
NN(
NN(
NN(
0, 
0, 
-1, 486.838, 1, 1, 0.527527,-99) , 
NN(
NN(
0, 
0, 
-1, 0, 1, 1, 0.516409,-99) , 
NN(
0, 
0, 
-1, 0, 1, -1, 0.374794,-99) , 
1, 21.0457, 0, 0, 0.47414,-99) , 
5, 222.479, 0, 0, 0.507738,-99) , 
NN(
0, 
0, 
-1, 0, 1, -1, 0.35254,-99) , 
1, 357.874, 1, 0, 0.502264,-99)    );
  // itree = 83
  fBoostWeights.push_back(0.0179067);
  fForest.push_back( 
NN(
NN(
NN(
NN(
0, 
0, 
-1, 0, 1, 1, 0.633842,-99) , 
NN(
0, 
0, 
-1, 0, 1, -1, 0.471159,-99) , 
13, 192.893, 0, 0, 0.575133,-99) , 
NN(
NN(
0, 
0, 
-1, 0, 1, 1, 0.504885,-99) , 
NN(
0, 
0, 
-1, 0, 1, -1, 0.377613,-99) , 
8, 360.868, 0, 0, 0.500905,-99) , 
12, 136.182, 0, 0, 0.508157,-99) , 
NN(
0, 
0, 
-1, 0, 1, -1, 0.388875,-99) , 
3, 50.8447, 0, 0, 0.503263,-99)    );
  // itree = 84
  fBoostWeights.push_back(0.0117523);
  fForest.push_back( 
NN(
NN(
NN(
NN(
0, 
0, 
-1, 0, 1, 1, 0.568379,-99) , 
NN(
0, 
0, 
-1, 0, 1, -1, 0.490754,-99) , 
10, 0.334681, 1, 0, 0.496609,-99) , 
NN(
0, 
0, 
-1, 0, 1, -1, 0.396759,-99) , 
8, 360.868, 0, 0, 0.492507,-99) , 
NN(
0, 
0, 
-1, 0, 1, -1, 0.367606,-99) , 
2, 3.6658, 1, 0, 0.488321,-99)    );
  // itree = 85
  fBoostWeights.push_back(0.020183);
  fForest.push_back( 
NN(
NN(
NN(
0, 
0, 
-1, 0, 1, 1, 0.612216,-99) , 
NN(
0, 
0, 
-1, 0, 1, -1, 0.442331,-99) , 
13, 182.773, 0, 0, 0.561504,-99) , 
NN(
NN(
NN(
0, 
0, 
-1, 0, 1, 1, 0.509117,-99) , 
NN(
0, 
0, 
-1, 0, 1, -1, 0.447368,-99) , 
6, 2.69313, 1, 0, 0.497753,-99) , 
NN(
0, 
0, 
-1, 130.294, 0, -1, 0.442099,-99) , 
6, 1.82532, 0, 0, 0.490997,-99) , 
12, 133.252, 0, 0, 0.498031,-99)    );
  // itree = 86
  fBoostWeights.push_back(0.0258329);
  fForest.push_back( 
NN(
NN(
NN(
NN(
0, 
0, 
-1, 0, 1, 1, 0.507568,-99) , 
NN(
0, 
0, 
-1, 0, 1, -1, 0.401326,-99) , 
7, 426.108, 1, 0, 0.502365,-99) , 
NN(
0, 
0, 
-1, 555.933, 0, -1, 0.452414,-99) , 
17, -2.03276, 0, 0, 0.492739,-99) , 
NN(
0, 
0, 
-1, 0, 1, -1, 0.370825,-99) , 
10, 0.249853, 0, 0, 0.485607,-99)    );
  // itree = 87
  fBoostWeights.push_back(0.0133827);
  fForest.push_back( 
NN(
NN(
NN(
0, 
0, 
-1, 0, 1, 1, 0.62167,-99) , 
NN(
NN(
0, 
0, 
-1, 0, 1, 1, 0.504126,-99) , 
NN(
0, 
0, 
-1, 0, 1, -1, 0.445935,-99) , 
5, 199.01, 0, 0, 0.488099,-99) , 
10, 2.13499, 0, 0, 0.492046,-99) , 
NN(
0, 
0, 
-1, 0, 1, -1, 0.355273,-99) , 
10, 0.296658, 0, 0, 0.481154,-99)    );
  // itree = 88
  fBoostWeights.push_back(0.0312683);
  fForest.push_back( 
NN(
NN(
NN(
NN(
0, 
0, 
-1, 0, 1, 1, 0.594834,-99) , 
NN(
0, 
0, 
-1, 0, 1, -1, 0.459163,-99) , 
7, 232.122, 1, 0, 0.53464,-99) , 
NN(
0, 
0, 
-1, 2.15588, 1, -1, 0.480074,-99) , 
9, 243.977, 0, 0, 0.490566,-99) , 
NN(
0, 
0, 
-1, 61.2385, 0, -1, 0.377573,-99) , 
2, 0.919373, 0, 0, 0.47928,-99)    );
  // itree = 89
  fBoostWeights.push_back(0.0181939);
  fForest.push_back( 
NN(
NN(
NN(
NN(
0, 
0, 
-1, 0, 1, 1, 0.577359,-99) , 
NN(
0, 
0, 
-1, 0, 1, -1, 0.453773,-99) , 
17, -1.53996, 0, 0, 0.548316,-99) , 
NN(
NN(
0, 
0, 
-1, 0, 1, 1, 0.508586,-99) , 
NN(
0, 
0, 
-1, 0, 1, -1, 0.47015,-99) , 
13, 188.893, 1, 0, 0.487768,-99) , 
15, 266.352, 0, 0, 0.494643,-99) , 
NN(
0, 
0, 
-1, 0, 1, -1, 0.322341,-99) , 
14, 42.2025, 0, 0, 0.488805,-99)    );
  // itree = 90
  fBoostWeights.push_back(0.0532979);
  fForest.push_back( 
NN(
NN(
NN(
NN(
0, 
0, 
-1, 0, 1, 1, 0.54166,-99) , 
NN(
0, 
0, 
-1, 0, 1, -1, 0.480619,-99) , 
1, 41.7094, 1, 0, 0.509095,-99) , 
NN(
NN(
0, 
0, 
-1, 0, 1, 1, 0.511637,-99) , 
NN(
0, 
0, 
-1, 0, 1, -1, 0.348858,-99) , 
1, 16.6851, 0, 0, 0.463693,-99) , 
10, 0.76367, 0, 0, 0.494415,-99) , 
NN(
NN(
0, 
0, 
-1, 0, 1, 1, 0.50681,-99) , 
NN(
0, 
0, 
-1, 0, 1, -1, 0.326619,-99) , 
11, 66.9081, 0, 0, 0.396246,-99) , 
1, 212.742, 1, 0, 0.485308,-99)    );
  // itree = 91
  fBoostWeights.push_back(0.012833);
  fForest.push_back( 
NN(
NN(
NN(
0, 
0, 
-1, 0, 1, 1, 0.736941,-99) , 
NN(
NN(
0, 
0, 
-1, 0, 1, 1, 0.650408,-99) , 
NN(
0, 
0, 
-1, 0, 1, -1, 0.447252,-99) , 
7, 72.3675, 1, 0, 0.53228,-99) , 
2, 3.07059, 0, 0, 0.596895,-99) , 
NN(
NN(
0, 
0, 
-1, 0.476253, 1, 1, 0.529793,-99) , 
NN(
0, 
0, 
-1, 2.64867, 1, -1, 0.474404,-99) , 
13, 292.38, 0, 0, 0.491836,-99) , 
7, 89.3125, 1, 0, 0.501104,-99)    );
  // itree = 92
  fBoostWeights.push_back(0.0284922);
  fForest.push_back( 
NN(
NN(
NN(
0, 
0, 
-1, 246.558, 1, 1, 0.597029,-99) , 
NN(
NN(
0, 
0, 
-1, 0, 1, 1, 0.54023,-99) , 
NN(
0, 
0, 
-1, 0, 1, -1, 0.417537,-99) , 
7, 154.894, 0, 0, 0.494151,-99) , 
16, -1.29304, 1, 0, 0.533042,-99) , 
NN(
NN(
NN(
0, 
0, 
-1, 0, 1, 1, 0.575622,-99) , 
NN(
0, 
0, 
-1, 0, 1, -1, 0.495546,-99) , 
2, 2.96461, 0, 0, 0.514577,-99) , 
NN(
0, 
0, 
-1, 199.569, 0, -1, 0.458601,-99) , 
6, 2.12317, 1, 0, 0.476903,-99) , 
12, 106.596, 0, 0, 0.488969,-99)    );
  // itree = 93
  fBoostWeights.push_back(0.0469646);
  fForest.push_back( 
NN(
NN(
NN(
NN(
0, 
0, 
-1, 0, 1, 1, 0.554377,-99) , 
NN(
0, 
0, 
-1, 0, 1, -1, 0.486221,-99) , 
18, 1.04718, 1, 0, 0.531321,-99) , 
NN(
NN(
0, 
0, 
-1, 0, 1, 1, 0.524004,-99) , 
NN(
0, 
0, 
-1, 0, 1, -1, 0.421765,-99) , 
15, 147.708, 0, 0, 0.479329,-99) , 
13, 258.518, 1, 0, 0.507712,-99) , 
NN(
NN(
NN(
0, 
0, 
-1, 0, 1, 1, 0.612002,-99) , 
NN(
0, 
0, 
-1, 0, 1, -1, 0.456616,-99) , 
3, 77.5184, 1, 0, 0.490627,-99) , 
NN(
0, 
0, 
-1, 140.793, 0, -1, 0.389906,-99) , 
11, 43.4968, 1, 0, 0.449857,-99) , 
13, 136.579, 0, 0, 0.494789,-99)    );
  // itree = 94
  fBoostWeights.push_back(0.0242197);
  fForest.push_back( 
NN(
NN(
0, 
0, 
-1, 0, 1, 1, 0.722259,-99) , 
NN(
NN(
NN(
0, 
0, 
-1, 0, 1, 1, 0.515935,-99) , 
NN(
0, 
0, 
-1, 0, 1, -1, 0.405265,-99) , 
2, 3.36266, 1, 0, 0.507292,-99) , 
NN(
0, 
0, 
-1, 2.26206, 1, -1, 0.436706,-99) , 
4, 165.453, 0, 0, 0.4961,-99) , 
10, 2.2254, 0, 0, 0.502974,-99)    );
  // itree = 95
  fBoostWeights.push_back(0.0100891);
  fForest.push_back( 
NN(
NN(
NN(
0, 
0, 
-1, 69.7002, 1, 1, 0.592783,-99) , 
NN(
NN(
0, 
0, 
-1, 0, 1, 1, 0.588176,-99) , 
NN(
0, 
0, 
-1, 0, 1, -1, 0.493951,-99) , 
10, 0.362904, 1, 0, 0.502279,-99) , 
9, 49.1234, 1, 0, 0.512337,-99) , 
NN(
0, 
0, 
-1, 303.893, 0, -1, 0.448292,-99) , 
1, 202, 1, 0, 0.505798,-99)    );
  // itree = 96
  fBoostWeights.push_back(0.0216664);
  fForest.push_back( 
NN(
NN(
NN(
NN(
0, 
0, 
-1, 0, 1, 1, 0.527649,-99) , 
NN(
0, 
0, 
-1, 0, 1, -1, 0.435765,-99) , 
1, 212.742, 1, 0, 0.51935,-99) , 
NN(
NN(
0, 
0, 
-1, 0, 1, 1, 0.502687,-99) , 
NN(
0, 
0, 
-1, 0, 1, -1, 0.444509,-99) , 
2, 2.58433, 1, 0, 0.475432,-99) , 
11, 61.0841, 1, 0, 0.500614,-99) , 
NN(
0, 
0, 
-1, 0, 1, -1, 0.272906,-99) , 
14, 46.7034, 0, 0, 0.493178,-99)    );
  // itree = 97
  fBoostWeights.push_back(0.0125587);
  fForest.push_back( 
NN(
NN(
NN(
NN(
0, 
0, 
-1, 0, 1, 1, 0.635746,-99) , 
NN(
0, 
0, 
-1, 0, 1, -1, 0.484083,-99) , 
9, 119.533, 1, 0, 0.559806,-99) , 
NN(
NN(
0, 
0, 
-1, 0, 1, 1, 0.505229,-99) , 
NN(
0, 
0, 
-1, 0, 1, -1, 0.471148,-99) , 
1, 52.9715, 1, 0, 0.485308,-99) , 
11, 22.6413, 1, 0, 0.494041,-99) , 
NN(
0, 
0, 
-1, 0, 1, -1, 0.329563,-99) , 
8, 348.957, 0, 0, 0.488337,-99)    );
  // itree = 98
  fBoostWeights.push_back(0.0174991);
  fForest.push_back( 
NN(
NN(
NN(
0, 
0, 
-1, 0, 1, 1, 0.588661,-99) , 
NN(
NN(
0, 
0, 
-1, 0, 1, 1, 0.583979,-99) , 
NN(
0, 
0, 
-1, 0, 1, -1, 0.491771,-99) , 
10, 0.406104, 1, 0, 0.496912,-99) , 
8, 357.766, 1, 0, 0.501521,-99) , 
NN(
0, 
0, 
-1, 0, 1, -1, 0.411876,-99) , 
10, 0.249853, 0, 0, 0.497119,-99)    );
  // itree = 99
  fBoostWeights.push_back(0.0200022);
  fForest.push_back( 
NN(
NN(
NN(
NN(
0, 
0, 
-1, 0, 1, 1, 0.600911,-99) , 
NN(
0, 
0, 
-1, 0, 1, -1, 0.497098,-99) , 
14, 332.465, 1, 0, 0.574819,-99) , 
NN(
0, 
0, 
-1, 0, 1, -1, 0.476731,-99) , 
7, 473.331, 1, 0, 0.552157,-99) , 
NN(
NN(
NN(
0, 
0, 
-1, 0, 1, 1, 0.501441,-99) , 
NN(
0, 
0, 
-1, 0, 1, -1, 0.377486,-99) , 
10, 1.95474, 1, 0, 0.496331,-99) , 
NN(
0, 
0, 
-1, 0, 1, -1, 0.404969,-99) , 
11, 19.1476, 0, 0, 0.488271,-99) , 
8, 1032.77, 0, 0, 0.497678,-99)    );
  // itree = 100
  fBoostWeights.push_back(0.00553953);
  fForest.push_back( 
NN(
NN(
0, 
0, 
-1, 0, 1, 1, 0.719629,-99) , 
NN(
NN(
0, 
0, 
-1, 0.300737, 1, 1, 0.51117,-99) , 
NN(
NN(
0, 
0, 
-1, 0, 1, 1, 0.514678,-99) , 
NN(
0, 
0, 
-1, 0, 1, -1, 0.385446,-99) , 
6, 2.23905, 1, 0, 0.453498,-99) , 
15, 63.6327, 0, 0, 0.505451,-99) , 
10, 2.17624, 0, 0, 0.512328,-99)    );
  // itree = 101
  fBoostWeights.push_back(0.0226754);
  fForest.push_back( 
NN(
NN(
0, 
0, 
-1, 0, 1, 1, 0.735953,-99) , 
NN(
NN(
NN(
0, 
0, 
-1, 0, 1, 1, 0.521785,-99) , 
NN(
0, 
0, 
-1, 0, 1, -1, 0.453731,-99) , 
13, 115.14, 0, 0, 0.512692,-99) , 
NN(
0, 
0, 
-1, 87.341, 1, -1, 0.462472,-99) , 
3, 123.206, 0, 0, 0.493697,-99) , 
10, 2.18257, 0, 0, 0.502138,-99)    );
  // itree = 102
  fBoostWeights.push_back(0.029247);
  fForest.push_back( 
NN(
NN(
NN(
NN(
0, 
0, 
-1, 0, 1, 1, 0.5437,-99) , 
NN(
0, 
0, 
-1, 0, 1, -1, 0.464809,-99) , 
18, 2.27903, 1, 0, 0.531813,-99) , 
NN(
NN(
0, 
0, 
-1, 0, 1, 1, 0.526059,-99) , 
NN(
0, 
0, 
-1, 0, 1, -1, 0.468811,-99) , 
0, 138.543, 0, 0, 0.485964,-99) , 
14, 151.695, 0, 0, 0.505346,-99) , 
NN(
NN(
NN(
0, 
0, 
-1, 0, 1, 1, 0.532071,-99) , 
NN(
0, 
0, 
-1, 0, 1, -1, 0.45369,-99) , 
2, 2.2049, 1, 0, 0.483516,-99) , 
NN(
0, 
0, 
-1, 91.4323, 0, -1, 0.369391,-99) , 
9, 98.0684, 0, 0, 0.451924,-99) , 
17, -2.03279, 0, 0, 0.494982,-99)    );
  // itree = 103
  fBoostWeights.push_back(0.0492936);
  fForest.push_back( 
NN(
NN(
NN(
0, 
0, 
-1, 225.554, 0, 1, 0.534777,-99) , 
NN(
NN(
0, 
0, 
-1, 0, 1, 1, 0.665662,-99) , 
NN(
0, 
0, 
-1, 0, 1, -1, 0.482046,-99) , 
17, -2.67046, 1, 0, 0.493031,-99) , 
14, 149.644, 0, 0, 0.51037,-99) , 
NN(
NN(
NN(
0, 
0, 
-1, 0, 1, 1, 0.529773,-99) , 
NN(
0, 
0, 
-1, 0, 1, -1, 0.434822,-99) , 
14, 152.168, 0, 0, 0.502861,-99) , 
NN(
NN(
0, 
0, 
-1, 0, 1, 1, 0.51221,-99) , 
NN(
0, 
0, 
-1, 0, 1, -1, 0.392598,-99) , 
14, 154.708, 1, 0, 0.428837,-99) , 
2, 2.25108, 1, 0, 0.459535,-99) , 
17, 1.66317, 1, 0, 0.49781,-99)    );
  // itree = 104
  fBoostWeights.push_back(0.0307489);
  fForest.push_back( 
NN(
NN(
NN(
0, 
0, 
-1, 17.4778, 1, 1, 0.596078,-99) , 
NN(
NN(
0, 
0, 
-1, 0, 1, 1, 0.523153,-99) , 
NN(
0, 
0, 
-1, 0, 1, -1, 0.428447,-99) , 
1, 161.026, 1, 0, 0.512331,-99) , 
11, 22.2498, 1, 0, 0.522063,-99) , 
NN(
NN(
NN(
0, 
0, 
-1, 0, 1, 1, 0.553367,-99) , 
NN(
0, 
0, 
-1, 0, 1, -1, 0.47322,-99) , 
13, 381.23, 1, 0, 0.518497,-99) , 
NN(
0, 
0, 
-1, 743.578, 0, -1, 0.408941,-99) , 
11, 52.7016, 0, 0, 0.483096,-99) , 
13, 264.271, 1, 0, 0.508316,-99)    );
  // itree = 105
  fBoostWeights.push_back(0.0618451);
  fForest.push_back( 
NN(
NN(
NN(
NN(
0, 
0, 
-1, 0, 1, 1, 0.5427,-99) , 
NN(
0, 
0, 
-1, 0, 1, -1, 0.483717,-99) , 
9, 126.775, 1, 0, 0.512338,-99) , 
NN(
0, 
0, 
-1, 2.59724, 1, -1, 0.407659,-99) , 
4, 385.198, 1, 0, 0.502361,-99) , 
NN(
NN(
NN(
0, 
0, 
-1, 0, 1, 1, 0.541325,-99) , 
NN(
0, 
0, 
-1, 0, 1, -1, 0.445803,-99) , 
5, 276.75, 0, 0, 0.518933,-99) , 
NN(
0, 
0, 
-1, 478.799, 1, -1, 0.376375,-99) , 
8, 646.207, 0, 0, 0.467235,-99) , 
3, 175.223, 1, 0, 0.489128,-99)    );
  // itree = 106
  fBoostWeights.push_back(0.0177922);
  fForest.push_back( 
NN(
NN(
NN(
0, 
0, 
-1, 0, 1, 1, 0.60341,-99) , 
NN(
NN(
0, 
0, 
-1, 0, 1, 1, 0.546392,-99) , 
NN(
0, 
0, 
-1, 0, 1, -1, 0.484193,-99) , 
10, 1.65617, 0, 0, 0.491835,-99) , 
14, 48.9057, 1, 0, 0.495828,-99) , 
NN(
0, 
0, 
-1, 0, 1, -1, 0.407164,-99) , 
10, 0.25012, 0, 0, 0.491372,-99)    );
  // itree = 107
  fBoostWeights.push_back(0.0208007);
  fForest.push_back( 
NN(
NN(
NN(
NN(
0, 
0, 
-1, 0, 1, 1, 0.619195,-99) , 
NN(
0, 
0, 
-1, 0, 1, -1, 0.497859,-99) , 
10, 1.01264, 1, 0, 0.549359,-99) , 
NN(
NN(
0, 
0, 
-1, 0, 1, 1, 0.541238,-99) , 
NN(
0, 
0, 
-1, 0, 1, -1, 0.481382,-99) , 
9, 224.945, 0, 0, 0.497191,-99) , 
7, 107.955, 1, 0, 0.506429,-99) , 
NN(
0, 
0, 
-1, 0, 1, -1, 0.386237,-99) , 
16, -3.01835, 0, 0, 0.502434,-99)    );
  // itree = 108
  fBoostWeights.push_back(0.0151005);
  fForest.push_back( 
NN(
NN(
NN(
NN(
0, 
0, 
-1, 0, 1, 1, 0.614979,-99) , 
NN(
0, 
0, 
-1, 0, 1, -1, 0.488457,-99) , 
15, 121.966, 1, 0, 0.544741,-99) , 
NN(
NN(
0, 
0, 
-1, 0, 1, 1, 0.51219,-99) , 
NN(
0, 
0, 
-1, 0, 1, -1, 0.414454,-99) , 
10, 1.75899, 1, 0, 0.506983,-99) , 
2, 2.88691, 0, 0, 0.517602,-99) , 
NN(
0, 
0, 
-1, 0, 1, -1, 0.429877,-99) , 
18, -2.89518, 0, 0, 0.513487,-99)    );
  // itree = 109
  fBoostWeights.push_back(0.013867);
  fForest.push_back( 
NN(
NN(
NN(
0, 
0, 
-1, 316.554, 1, 1, 0.616134,-99) , 
NN(
NN(
0, 
0, 
-1, 0, 1, 1, 0.504456,-99) , 
NN(
0, 
0, 
-1, 0, 1, -1, 0.392444,-99) , 
1, 309.304, 1, 0, 0.499699,-99) , 
8, 369.505, 1, 0, 0.5069,-99) , 
NN(
0, 
0, 
-1, 0, 1, -1, 0.395577,-99) , 
10, 0.249853, 0, 0, 0.500988,-99)    );
  // itree = 110
  fBoostWeights.push_back(0.0232058);
  fForest.push_back( 
NN(
NN(
0, 
0, 
-1, 0, 1, 1, 0.603729,-99) , 
NN(
NN(
NN(
0, 
0, 
-1, 0, 1, 1, 0.533336,-99) , 
NN(
0, 
0, 
-1, 0, 1, -1, 0.485619,-99) , 
0, 80.5669, 1, 0, 0.499926,-99) , 
NN(
0, 
0, 
-1, 168.01, 0, -1, 0.41317,-99) , 
14, 293.097, 1, 0, 0.489721,-99) , 
2, 3.53764, 0, 0, 0.495443,-99)    );
  // itree = 111
  fBoostWeights.push_back(0.0119318);
  fForest.push_back( 
NN(
NN(
NN(
0, 
0, 
-1, 0, 1, 1, 0.623598,-99) , 
NN(
NN(
0, 
0, 
-1, 0, 1, 1, 0.583554,-99) , 
NN(
0, 
0, 
-1, 0, 1, -1, 0.485077,-99) , 
14, 56.1328, 1, 0, 0.489822,-99) , 
10, 0.311563, 1, 0, 0.49813,-99) , 
NN(
0, 
0, 
-1, 188.059, 1, -1, 0.40088,-99) , 
2, 0.924886, 0, 0, 0.48768,-99)    );
  // itree = 112
  fBoostWeights.push_back(0.0159658);
  fForest.push_back( 
NN(
NN(
0, 
0, 
-1, 0.289216, 1, 1, 0.522544,-99) , 
NN(
NN(
NN(
0, 
0, 
-1, 0, 1, 1, 0.627068,-99) , 
NN(
0, 
0, 
-1, 0, 1, -1, 0.496788,-99) , 
4, 219.416, 1, 0, 0.56077,-99) , 
NN(
0, 
0, 
-1, 453.078, 0, -1, 0.433407,-99) , 
12, 39.6414, 1, 0, 0.466394,-99) , 
17, 1.53997, 1, 0, 0.50758,-99)    );
  // itree = 113
  fBoostWeights.push_back(0.0221006);
  fForest.push_back( 
NN(
NN(
NN(
NN(
0, 
0, 
-1, 0, 1, 1, 0.51967,-99) , 
NN(
0, 
0, 
-1, 0, 1, -1, 0.445663,-99) , 
14, 294.382, 1, 0, 0.510231,-99) , 
NN(
0, 
0, 
-1, 0, 1, -1, 0.38236,-99) , 
3, 54.9915, 0, 0, 0.504289,-99) , 
NN(
0, 
0, 
-1, 0, 1, -1, 0.340957,-99) , 
8, 374.747, 0, 0, 0.496537,-99)    );
  // itree = 114
  fBoostWeights.push_back(0.016731);
  fForest.push_back( 
NN(
NN(
NN(
0, 
0, 
-1, 0, 1, 1, 0.636042,-99) , 
NN(
NN(
0, 
0, 
-1, 0, 1, 1, 0.51708,-99) , 
NN(
0, 
0, 
-1, 0, 1, -1, 0.476441,-99) , 
18, 1.17035, 1, 0, 0.503648,-99) , 
10, 2.12467, 0, 0, 0.507606,-99) , 
NN(
0, 
0, 
-1, 0, 1, -1, 0.402486,-99) , 
10, 0.249853, 0, 0, 0.501644,-99)    );
  // itree = 115
  fBoostWeights.push_back(0.0158809);
  fForest.push_back( 
NN(
NN(
NN(
0, 
0, 
-1, 563.695, 1, 1, 0.582938,-99) , 
NN(
NN(
0, 
0, 
-1, 0, 1, 1, 0.578653,-99) , 
NN(
0, 
0, 
-1, 0, 1, -1, 0.493601,-99) , 
10, 0.311818, 1, 0, 0.498731,-99) , 
6, 2.9938, 0, 0, 0.504481,-99) , 
NN(
0, 
0, 
-1, 0, 1, -1, 0.34946,-99) , 
15, 46.8454, 0, 0, 0.496129,-99)    );
  // itree = 116
  fBoostWeights.push_back(0.0145091);
  fForest.push_back( 
NN(
NN(
NN(
0, 
0, 
-1, 0, 1, 1, 0.612338,-99) , 
NN(
NN(
0, 
0, 
-1, 0, 1, 1, 0.552146,-99) , 
NN(
0, 
0, 
-1, 0, 1, -1, 0.484041,-99) , 
2, 1.90188, 1, 0, 0.508249,-99) , 
2, 3.33553, 0, 0, 0.517994,-99) , 
NN(
0, 
0, 
-1, 0.302667, 0, -1, 0.472114,-99) , 
18, -1.41678, 1, 0, 0.486395,-99)    );
  // itree = 117
  fBoostWeights.push_back(0);
  fForest.push_back( 
NN(
NN(
NN(
0, 
0, 
-1, 1.36831, 0, 1, 0.569681,-99) , 
NN(
NN(
0, 
0, 
-1, 0, 1, 1, 0.593964,-99) , 
NN(
0, 
0, 
-1, 0, 1, -1, 0.494107,-99) , 
8, 384.465, 1, 0, 0.498838,-99) , 
11, 138.459, 0, 0, 0.505081,-99) , 
NN(
0, 
0, 
-1, 0, 1, -1, 0.399513,-99) , 
7, 80.6162, 0, 0, 0.501192,-99)    );
  // itree = 118
  fBoostWeights.push_back(0.0075119);
  fForest.push_back( 
NN(
NN(
0, 
0, 
-1, 0, 1, 1, 0.679073,-99) , 
NN(
NN(
0, 
0, 
-1, 0, 1, 1, 0.575336,-99) , 
NN(
NN(
0, 
0, 
-1, 0, 1, 1, 0.526179,-99) , 
NN(
0, 
0, 
-1, 0, 1, -1, 0.47333,-99) , 
2, 1.92316, 1, 0, 0.493163,-99) , 
6, 1.55506, 1, 0, 0.498751,-99) , 
10, 2.15898, 0, 0, 0.504479,-99)    );
  // itree = 119
  fBoostWeights.push_back(0);
  fForest.push_back( 
NN(
NN(
NN(
NN(
0, 
0, 
-1, 0, 1, 1, 0.670001,-99) , 
NN(
0, 
0, 
-1, 0, 1, -1, 0.472778,-99) , 
4, 263.788, 1, 0, 0.606922,-99) , 
NN(
NN(
0, 
0, 
-1, 0, 1, 1, 0.516272,-99) , 
NN(
0, 
0, 
-1, 0, 1, -1, 0.417662,-99) , 
4, 433.605, 1, 0, 0.498363,-99) , 
13, 174.565, 1, 0, 0.534746,-99) , 
NN(
NN(
0, 
0, 
-1, 0, 1, 1, 0.559405,-99) , 
NN(
0, 
0, 
-1, 671.726, 1, -1, 0.480906,-99) , 
10, 0.298919, 1, 0, 0.485901,-99) , 
12, 44.1618, 1, 0, 0.499317,-99)    );
  // itree = 120
  fBoostWeights.push_back(0.000278403);
  fForest.push_back( 
NN(
NN(
NN(
0, 
0, 
-1, 896.088, 0, 1, 0.559584,-99) , 
NN(
NN(
0, 
0, 
-1, 0, 1, 1, 0.539702,-99) , 
NN(
0, 
0, 
-1, 0, 1, -1, 0.493451,-99) , 
15, 72.3748, 1, 0, 0.498947,-99) , 
10, 0.415852, 1, 0, 0.504905,-99) , 
NN(
0, 
0, 
-1, 0, 1, -1, 0.32848,-99) , 
8, 337.855, 0, 0, 0.49988,-99)    );
  // itree = 121
  fBoostWeights.push_back(0.0218116);
  fForest.push_back( 
NN(
NN(
NN(
NN(
0, 
0, 
-1, 0, 1, 1, 0.590236,-99) , 
NN(
0, 
0, 
-1, 0, 1, -1, 0.455995,-99) , 
9, 117.796, 1, 0, 0.546809,-99) , 
NN(
0, 
0, 
-1, 2.55415, 1, -1, 0.486345,-99) , 
8, 505.032, 1, 0, 0.502037,-99) , 
NN(
0, 
0, 
-1, 0, 1, -1, 0.291612,-99) , 
10, 0.250114, 0, 0, 0.487841,-99)    );
  // itree = 122
  fBoostWeights.push_back(0.00708331);
  fForest.push_back( 
NN(
NN(
0, 
0, 
-1, 136.089, 1, 1, 0.577896,-99) , 
NN(
NN(
0, 
0, 
-1, 116.539, 1, 1, 0.511278,-99) , 
NN(
0, 
0, 
-1, 139.627, 0, -1, 0.431161,-99) , 
6, 1.75612, 0, 0, 0.503797,-99) , 
10, 0.333407, 1, 0, 0.509347,-99)    );
  // itree = 123
  fBoostWeights.push_back(0.0114583);
  fForest.push_back( 
NN(
NN(
NN(
NN(
0, 
0, 
-1, 0, 1, 1, 0.544137,-99) , 
NN(
0, 
0, 
-1, 0, 1, -1, 0.488179,-99) , 
12, 79.9531, 1, 0, 0.518987,-99) , 
NN(
0, 
0, 
-1, 40.4, 0, -1, 0.440144,-99) , 
18, 2.40239, 1, 0, 0.507088,-99) , 
NN(
NN(
NN(
0, 
0, 
-1, 0, 1, 1, 0.509938,-99) , 
NN(
0, 
0, 
-1, 0, 1, -1, 0.430649,-99) , 
9, 197.911, 1, 0, 0.478879,-99) , 
NN(
0, 
0, 
-1, 0, 1, -1, 0.327934,-99) , 
8, 400.026, 0, 0, 0.46372,-99) , 
16, 1.9096, 1, 0, 0.493687,-99)    );
  // itree = 124
  fBoostWeights.push_back(0.0190544);
  fForest.push_back( 
NN(
NN(
NN(
0, 
0, 
-1, 182.75, 0, 1, 0.520714,-99) , 
NN(
NN(
0, 
0, 
-1, 0, 1, 1, 0.614888,-99) , 
NN(
0, 
0, 
-1, 0, 1, -1, 0.46873,-99) , 
16, 2.03258, 0, 0, 0.485642,-99) , 
13, 153.235, 0, 0, 0.510613,-99) , 
NN(
0, 
0, 
-1, 0, 1, -1, 0.370387,-99) , 
14, 44.1353, 0, 0, 0.5064,-99)    );
  // itree = 125
  fBoostWeights.push_back(0.0273356);
  fForest.push_back( 
NN(
NN(
NN(
0, 
0, 
-1, 436.762, 1, 1, 0.610547,-99) , 
NN(
NN(
0, 
0, 
-1, 0, 1, 1, 0.60387,-99) , 
NN(
0, 
0, 
-1, 0, 1, -1, 0.465303,-99) , 
5, 159.648, 1, 0, 0.50835,-99) , 
6, 2.51489, 0, 0, 0.543073,-99) , 
NN(
NN(
0, 
0, 
-1, 0, 1, 1, 0.603106,-99) , 
NN(
NN(
0, 
0, 
-1, 0, 1, 1, 0.543996,-99) , 
NN(
0, 
0, 
-1, 0, 1, -1, 0.483861,-99) , 
8, 1143.52, 0, 0, 0.491852,-99) , 
11, 184.307, 0, 0, 0.496511,-99) , 
8, 522.65, 1, 0, 0.50945,-99)    );
  // itree = 126
  fBoostWeights.push_back(0.0406365);
  fForest.push_back( 
NN(
NN(
NN(
0, 
0, 
-1, 3.33512, 0, 1, 0.533719,-99) , 
NN(
NN(
0, 
0, 
-1, 0, 1, 1, 0.507685,-99) , 
NN(
0, 
0, 
-1, 0, 1, -1, 0.439784,-99) , 
6, 2.58235, 1, 0, 0.485493,-99) , 
3, 128.435, 1, 0, 0.506019,-99) , 
NN(
0, 
0, 
-1, 0, 1, -1, 0.406389,-99) , 
15, 47.7997, 0, 0, 0.500396,-99)    );
  // itree = 127
  fBoostWeights.push_back(0.0174587);
  fForest.push_back( 
NN(
NN(
NN(
0, 
0, 
-1, 3.18266, 0, 1, 0.516273,-99) , 
NN(
0, 
0, 
-1, 1237.26, 0, -1, 0.442848,-99) , 
7, 325.169, 1, 0, 0.508707,-99) , 
NN(
NN(
0, 
0, 
-1, 0, 1, 1, 0.526496,-99) , 
NN(
0, 
0, 
-1, 0, 1, -1, 0.12225,-99) , 
17, 1.78566, 1, 0, 0.342705,-99) , 
2, 3.52733, 1, 0, 0.499054,-99)    );
  // itree = 128
  fBoostWeights.push_back(0.0274581);
  fForest.push_back( 
NN(
NN(
NN(
NN(
0, 
0, 
-1, 0, 1, 1, 0.534774,-99) , 
NN(
0, 
0, 
-1, 0, 1, -1, 0.487175,-99) , 
13, 199.54, 1, 0, 0.508654,-99) , 
NN(
0, 
0, 
-1, 0, 1, -1, 0.367416,-99) , 
7, 84.2207, 0, 0, 0.502796,-99) , 
NN(
NN(
NN(
0, 
0, 
-1, 0, 1, 1, 0.566934,-99) , 
NN(
0, 
0, 
-1, 0, 1, -1, 0.457535,-99) , 
8, 524.274, 1, 0, 0.494232,-99) , 
NN(
0, 
0, 
-1, 0.695648, 0, -1, 0.401575,-99) , 
17, 0.0616361, 0, 0, 0.4473,-99) , 
6, 2.53516, 1, 0, 0.488657,-99)    );
  // itree = 129
  fBoostWeights.push_back(0.0192898);
  fForest.push_back( 
NN(
NN(
0, 
0, 
-1, 680.814, 1, 1, 0.599412,-99) , 
NN(
NN(
0, 
0, 
-1, 0, 1, 1, 0.603991,-99) , 
NN(
NN(
0, 
0, 
-1, 0, 1, 1, 0.54026,-99) , 
NN(
0, 
0, 
-1, 0, 1, -1, 0.479014,-99) , 
6, 2.65205, 0, 0, 0.491876,-99) , 
8, 1362.02, 0, 0, 0.497678,-99) , 
11, 166.139, 0, 0, 0.503401,-99)    );
  // itree = 130
  fBoostWeights.push_back(0.0242562);
  fForest.push_back( 
NN(
NN(
0, 
0, 
-1, 0, 1, 1, 0.696068,-99) , 
NN(
NN(
0, 
0, 
-1, 2.03269, 0, 1, 0.528826,-99) , 
NN(
NN(
0, 
0, 
-1, 0, 1, 1, 0.543868,-99) , 
NN(
0, 
0, 
-1, 0, 1, -1, 0.475154,-99) , 
3, 276.901, 0, 0, 0.486754,-99) , 
18, 0.307906, 0, 0, 0.506493,-99) , 
10, 2.24197, 0, 0, 0.511418,-99)    );
  // itree = 131
  fBoostWeights.push_back(0.0329546);
  fForest.push_back( 
NN(
NN(
NN(
NN(
0, 
0, 
-1, 0, 1, 1, 0.521084,-99) , 
NN(
0, 
0, 
-1, 0, 1, -1, 0.470074,-99) , 
5, 430.781, 1, 0, 0.509183,-99) , 
NN(
NN(
0, 
0, 
-1, 0, 1, 1, 0.579522,-99) , 
NN(
0, 
0, 
-1, 0, 1, -1, 0.347616,-99) , 
12, 68.8947, 1, 0, 0.437856,-99) , 
8, 438.437, 0, 0, 0.499656,-99) , 
NN(
NN(
NN(
0, 
0, 
-1, 0, 1, 1, 0.536776,-99) , 
NN(
0, 
0, 
-1, 0, 1, -1, 0.426762,-99) , 
16, -1.29359, 0, 0, 0.489371,-99) , 
NN(
NN(
0, 
0, 
-1, 0, 1, 1, 0.506962,-99) , 
NN(
0, 
0, 
-1, 0, 1, -1, 0.150894,-99) , 
1, 25.4062, 0, 0, 0.35259,-99) , 
6, 2.52359, 1, 0, 0.450063,-99) , 
12, 44.1605, 0, 0, 0.486105,-99)    );
  // itree = 132
  fBoostWeights.push_back(0.00404995);
  fForest.push_back( 
NN(
NN(
0, 
0, 
-1, 0, 1, 1, 0.687599,-99) , 
NN(
NN(
NN(
0, 
0, 
-1, 0, 1, 1, 0.510646,-99) , 
NN(
0, 
0, 
-1, 0, 1, -1, 0.416683,-99) , 
0, 274.429, 1, 0, 0.505767,-99) , 
NN(
0, 
0, 
-1, 0, 1, -1, 0.367905,-99) , 
8, 365.962, 0, 0, 0.500719,-99) , 
10, 2.22462, 0, 0, 0.505801,-99)    );
  // itree = 133
  fBoostWeights.push_back(0.0107534);
  fForest.push_back( 
NN(
NN(
NN(
NN(
0, 
0, 
-1, 0, 1, 1, 0.510957,-99) , 
NN(
0, 
0, 
-1, 0, 1, -1, 0.450427,-99) , 
14, 293.818, 1, 0, 0.503366,-99) , 
NN(
0, 
0, 
-1, 0, 1, -1, 0.398058,-99) , 
10, 1.89032, 1, 0, 0.498681,-99) , 
NN(
0, 
0, 
-1, 0, 1, -1, 0.384542,-99) , 
10, 0.249853, 0, 0, 0.492487,-99)    );
  // itree = 134
  fBoostWeights.push_back(0.00945218);
  fForest.push_back( 
NN(
NN(
NN(
0, 
0, 
-1, 358.355, 1, 1, 0.622471,-99) , 
NN(
NN(
0, 
0, 
-1, 0, 1, 1, 0.582745,-99) , 
NN(
0, 
0, 
-1, 0, 1, -1, 0.496842,-99) , 
10, 0.312118, 1, 0, 0.502254,-99) , 
8, 394.331, 1, 0, 0.50889,-99) , 
NN(
0, 
0, 
-1, 0, 1, -1, 0.332418,-99) , 
7, 84.2252, 0, 0, 0.501663,-99)    );
  // itree = 135
  fBoostWeights.push_back(0.0273542);
  fForest.push_back( 
NN(
NN(
NN(
0, 
0, 
-1, 1.01753, 0, 1, 0.584486,-99) , 
NN(
0, 
0, 
-1, 0, 1, -1, 0.462105,-99) , 
17, -1.66296, 0, 0, 0.555694,-99) , 
NN(
NN(
NN(
0, 
0, 
-1, 0, 1, 1, 0.594686,-99) , 
NN(
0, 
0, 
-1, 0, 1, -1, 0.495353,-99) , 
7, 248.152, 1, 0, 0.523541,-99) , 
NN(
0, 
0, 
-1, 244.59, 1, -1, 0.47807,-99) , 
8, 906.928, 0, 0, 0.487761,-99) , 
12, 18.5994, 1, 0, 0.495427,-99)    );
  // itree = 136
  fBoostWeights.push_back(0.0196695);
  fForest.push_back( 
NN(
NN(
NN(
0, 
0, 
-1, 0, 1, 1, 0.617911,-99) , 
NN(
0, 
0, 
-1, 0, 1, -1, 0.469461,-99) , 
13, 187.171, 0, 0, 0.569035,-99) , 
NN(
NN(
0, 
0, 
-1, 0, 1, 1, 0.558457,-99) , 
NN(
0, 
0, 
-1, 126.68, 0, -1, 0.487203,-99) , 
6, 1.5531, 1, 0, 0.491936,-99) , 
12, 130.193, 0, 0, 0.500405,-99)    );
  // itree = 137
  fBoostWeights.push_back(0.0333817);
  fForest.push_back( 
NN(
NN(
NN(
0, 
0, 
-1, 76.1873, 1, 1, 0.740599,-99) , 
NN(
0, 
0, 
-1, 0, 1, -1, 0.444521,-99) , 
2, 2.86372, 0, 0, 0.593793,-99) , 
NN(
NN(
0, 
0, 
-1, 94.1783, 1, 1, 0.522894,-99) , 
NN(
NN(
0, 
0, 
-1, 0, 1, 1, 0.522924,-99) , 
NN(
0, 
0, 
-1, 0, 1, -1, 0.42734,-99) , 
15, 139.057, 0, 0, 0.483096,-99) , 
7, 232.744, 1, 0, 0.512079,-99) , 
8, 403.916, 1, 0, 0.520068,-99)    );
  // itree = 138
  fBoostWeights.push_back(0.0241162);
  fForest.push_back( 
NN(
NN(
NN(
0, 
0, 
-1, 1.6631, 0, 1, 0.575101,-99) , 
NN(
0, 
0, 
-1, 393.509, 1, -1, 0.470056,-99) , 
15, 139.057, 0, 0, 0.54204,-99) , 
NN(
NN(
NN(
0, 
0, 
-1, 0, 1, 1, 0.50197,-99) , 
NN(
0, 
0, 
-1, 0, 1, -1, 0.410891,-99) , 
5, 448.195, 1, 0, 0.492512,-99) , 
NN(
0, 
0, 
-1, 0, 1, -1, 0.307749,-99) , 
4, 521.343, 1, 0, 0.484703,-99) , 
8, 906.456, 0, 0, 0.497249,-99)    );
  // itree = 139
  fBoostWeights.push_back(0.0216415);
  fForest.push_back( 
NN(
NN(
NN(
0, 
0, 
-1, 0.382926, 1, 1, 0.530671,-99) , 
NN(
0, 
0, 
-1, 19.1476, 0, -1, 0.488168,-99) , 
8, 735.993, 0, 0, 0.503911,-99) , 
NN(
NN(
NN(
0, 
0, 
-1, 0, 1, 1, 0.506747,-99) , 
NN(
0, 
0, 
-1, 0, 1, -1, 0.430881,-99) , 
4, 265.39, 0, 0, 0.466943,-99) , 
NN(
0, 
0, 
-1, 0, 1, -1, 0.329223,-99) , 
12, 13.6783, 0, 0, 0.451661,-99) , 
16, 2.27919, 1, 0, 0.490702,-99)    );
  // itree = 140
  fBoostWeights.push_back(0.0283723);
  fForest.push_back( 
NN(
NN(
NN(
0, 
0, 
-1, 0, 1, 1, 0.644902,-99) , 
NN(
NN(
0, 
0, 
-1, 0, 1, 1, 0.519749,-99) , 
NN(
0, 
0, 
-1, 0, 1, -1, 0.471563,-99) , 
18, 1.29345, 1, 0, 0.505513,-99) , 
7, 80.6455, 1, 0, 0.510672,-99) , 
NN(
NN(
0, 
0, 
-1, 138.52, 1, 1, 0.565408,-99) , 
NN(
0, 
0, 
-1, 182.502, 0, -1, 0.408347,-99) , 
6, 2.05934, 1, 0, 0.460176,-99) , 
5, 182.43, 0, 0, 0.499266,-99)    );
  // itree = 141
  fBoostWeights.push_back(0.0470305);
  fForest.push_back( 
NN(
NN(
NN(
0, 
0, 
-1, 0.860177, 1, 1, 0.55752,-99) , 
NN(
NN(
0, 
0, 
-1, 0, 1, 1, 0.52309,-99) , 
NN(
0, 
0, 
-1, 0, 1, -1, 0.442745,-99) , 
0, 101.8, 1, 0, 0.495656,-99) , 
6, 2.31388, 0, 0, 0.518252,-99) , 
NN(
NN(
NN(
0, 
0, 
-1, 0, 1, 1, 0.535526,-99) , 
NN(
0, 
0, 
-1, 0, 1, -1, 0.454218,-99) , 
4, 301.204, 0, 0, 0.512849,-99) , 
NN(
0, 
0, 
-1, 371.031, 1, -1, 0.400387,-99) , 
8, 644.76, 0, 0, 0.473995,-99) , 
3, 175.223, 1, 0, 0.501951,-99)    );
  // itree = 142
  fBoostWeights.push_back(0.0313492);
  fForest.push_back( 
NN(
NN(
NN(
0, 
0, 
-1, 3.0863, 0, 1, 0.528448,-99) , 
NN(
NN(
0, 
0, 
-1, 0, 1, 1, 0.55006,-99) , 
NN(
0, 
0, 
-1, 0, 1, -1, 0.453499,-99) , 
9, 244.774, 0, 0, 0.475052,-99) , 
18, 1.86614, 1, 0, 0.50266,-99) , 
NN(
0, 
0, 
-1, -0.141401, 1, -1, 0.464948,-99) , 
18, 0.184819, 0, 0, 0.482791,-99)    );
  // itree = 143
  fBoostWeights.push_back(0.0136116);
  fForest.push_back( 
NN(
NN(
NN(
0, 
0, 
-1, 0, 1, 1, 0.798495,-99) , 
NN(
0, 
0, 
-1, 0, 1, -1, 0.455566,-99) , 
9, 54.2104, 1, 0, 0.636243,-99) , 
NN(
NN(
NN(
0, 
0, 
-1, 0, 1, 1, 0.510633,-99) , 
NN(
0, 
0, 
-1, 0, 1, -1, 0.476018,-99) , 
11, 61.954, 1, 0, 0.496522,-99) , 
NN(
0, 
0, 
-1, 0, 1, -1, 0.402353,-99) , 
3, 50.1656, 0, 0, 0.492967,-99) , 
8, 365.962, 1, 0, 0.501352,-99)    );
  // itree = 144
  fBoostWeights.push_back(0.0214122);
  fForest.push_back( 
NN(
NN(
NN(
NN(
0, 
0, 
-1, 0, 1, 1, 0.509449,-99) , 
NN(
0, 
0, 
-1, 0, 1, -1, 0.445291,-99) , 
17, 2.54973, 1, 0, 0.501435,-99) , 
NN(
0, 
0, 
-1, 0, 1, -1, 0.380382,-99) , 
17, -2.89509, 0, 0, 0.496662,-99) , 
NN(
NN(
NN(
0, 
0, 
-1, 0, 1, 1, 0.508415,-99) , 
NN(
0, 
0, 
-1, 0, 1, -1, 0.370546,-99) , 
6, 2.01449, 0, 0, 0.471497,-99) , 
NN(
0, 
0, 
-1, 0, 1, -1, 0.333178,-99) , 
6, 2.53798, 1, 0, 0.431175,-99) , 
2, 1.28339, 0, 0, 0.484322,-99)    );
  // itree = 145
  fBoostWeights.push_back(0.0391178);
  fForest.push_back( 
NN(
NN(
NN(
0, 
0, 
-1, 1.66187, 0, 1, 0.610302,-99) , 
NN(
NN(
0, 
0, 
-1, 0, 1, 1, 0.536069,-99) , 
NN(
0, 
0, 
-1, 0, 1, -1, 0.4331,-99) , 
18, 1.41671, 1, 0, 0.505091,-99) , 
0, 80.621, 1, 0, 0.537018,-99) , 
NN(
NN(
NN(
0, 
0, 
-1, 0, 1, 1, 0.518874,-99) , 
NN(
0, 
0, 
-1, 0, 1, -1, 0.447665,-99) , 
6, 1.74984, 0, 0, 0.511069,-99) , 
NN(
0, 
0, 
-1, 186.524, 0, -1, 0.444088,-99) , 
14, 125.935, 0, 0, 0.485482,-99) , 
2, 2.72289, 0, 0, 0.504509,-99)    );
  // itree = 146
  fBoostWeights.push_back(0.0213085);
  fForest.push_back( 
NN(
NN(
NN(
NN(
0, 
0, 
-1, 0, 1, 1, 0.520057,-99) , 
NN(
0, 
0, 
-1, 0, 1, -1, 0.41824,-99) , 
16, -2.89516, 0, 0, 0.514222,-99) , 
NN(
0, 
0, 
-1, 2.89519, 1, -1, 0.465636,-99) , 
10, 0.763243, 0, 0, 0.498365,-99) , 
NN(
NN(
NN(
0, 
0, 
-1, 0, 1, 1, 0.536597,-99) , 
NN(
0, 
0, 
-1, 0, 1, -1, 0.452115,-99) , 
6, 1.65885, 1, 0, 0.49268,-99) , 
NN(
0, 
0, 
-1, 178.449, 0, -1, 0.400691,-99) , 
2, 2.67892, 0, 0, 0.43221,-99) , 
6, 1.90401, 0, 0, 0.488059,-99)    );
  // itree = 147
  fBoostWeights.push_back(0.0260798);
  fForest.push_back( 
NN(
NN(
NN(
NN(
0, 
0, 
-1, 0, 1, 1, 0.569602,-99) , 
NN(
0, 
0, 
-1, 0, 1, -1, 0.495036,-99) , 
2, 3.27604, 0, 0, 0.502493,-99) , 
NN(
0, 
0, 
-1, 0, 1, -1, 0.403136,-99) , 
5, 129.8, 0, 0, 0.49769,-99) , 
NN(
0, 
0, 
-1, 0, 1, -1, 0.352802,-99) , 
16, -3.01835, 0, 0, 0.492569,-99)    );
  // itree = 148
  fBoostWeights.push_back(0.0102219);
  fForest.push_back( 
NN(
NN(
0, 
0, 
-1, 0, 1, 1, 0.63265,-99) , 
NN(
NN(
0, 
0, 
-1, 0, 1, 1, 0.612644,-99) , 
NN(
0, 
0, 
-1, 333.15, 1, -1, 0.481561,-99) , 
5, 116.305, 1, 0, 0.486771,-99) , 
8, 339.013, 1, 0, 0.492154,-99)    );
  // itree = 149
  fBoostWeights.push_back(0.0343937);
  fForest.push_back( 
NN(
NN(
NN(
0, 
0, 
-1, 2.73452, 0, 1, 0.556513,-99) , 
NN(
NN(
0, 
0, 
-1, 0, 1, 1, 0.525891,-99) , 
NN(
0, 
0, 
-1, 0, 1, -1, 0.468501,-99) , 
14, 149.366, 1, 0, 0.496635,-99) , 
16, 1.11, 0, 0, 0.50947,-99) , 
NN(
NN(
NN(
0, 
0, 
-1, 0, 1, 1, 0.557106,-99) , 
NN(
0, 
0, 
-1, 0, 1, -1, 0.441988,-99) , 
16, 2.73583, 0, 0, 0.506407,-99) , 
NN(
NN(
0, 
0, 
-1, 0, 1, 1, 0.5241,-99) , 
NN(
0, 
0, 
-1, 0, 1, -1, 0.315738,-99) , 
3, 140.626, 1, 0, 0.409351,-99) , 
12, 41.0136, 0, 0, 0.473637,-99) , 
16, 2.27919, 1, 0, 0.500465,-99)    );
   return;
};
 
// Clean up
inline void ReadBDT::Clear() 
{
   for (unsigned int itree=0; itree<fForest.size(); itree++) { 
      delete fForest[itree]; 
   }
}
   inline double ReadBDT::GetMvaValue( const std::vector<double>& inputValues ) const
   {
      // classifier response value
      double retval = 0;

      // classifier response, sanity check first
      if (!IsStatusClean()) {
         std::cout << "Problem in class \"" << fClassName << "\": cannot return classifier response"
                   << " because status is dirty" << std::endl;
         retval = 0;
      }
      else {
         if (IsNormalised()) {
            // normalise variables
            std::vector<double> iV;
            iV.reserve(inputValues.size());
            int ivar = 0;
            for (std::vector<double>::const_iterator varIt = inputValues.begin();
                 varIt != inputValues.end(); varIt++, ivar++) {
               iV.push_back(NormVariable( *varIt, fVmin[ivar], fVmax[ivar] ));
            }
            retval = GetMvaValue__( iV );
         }
         else {
            retval = GetMvaValue__( inputValues );
         }
      }

      return retval;
   }
