// Class: ReadBDT
// Automatically generated by MethodBase::MakeClass
//

/* configuration options =====================================================

#GEN -*-*-*-*-*-*-*-*-*-*-*- general info -*-*-*-*-*-*-*-*-*-*-*-

Method         : BDT::BDT
TMVA Release   : 4.2.0         [262656]
ROOT Release   : 5.34/18       [336402]
Creator        : jlee
Date           : Mon Dec 12 14:14:32 2016
Host           : Linux cmsdev02.cern.ch 2.6.32-431.23.3.el6.x86_64 #1 SMP Wed Jul 30 09:43:11 CEST 2014 x86_64 x86_64 x86_64 GNU/Linux
Dir            : /home/jlee/CMS/ChargedHiggs/CMSSW_7_2_4/src/TMVA/test
Training events: 292684
Analysis type  : [Classification]


#OPT -*-*-*-*-*-*-*-*-*-*-*-*- options -*-*-*-*-*-*-*-*-*-*-*-*-

# Set by User:
V: "False" [Verbose output (short form of "VerbosityLevel" below - overrides the latter one)]
H: "False" [Print method-specific help message]
IgnoreNegWeightsInTraining: "True" [Events with negative weights are ignored in the training (but are included for testing and performance evaluation)]
NTrees: "150" [Number of trees in the forest]
MaxDepth: "3" [Max depth of the decision tree allowed]
MinNodeSize: "2.5%" [Minimum percentage of training events required in a leaf node (default: Classification: 5%, Regression: 0.2%)]
nCuts: "50" [Number of grid points in variable range used in finding optimal cut in node splitting]
BoostType: "AdaBoost" [Boosting type for the trees in the forest (note: AdaCost is still experimental)]
UseBaggedBoost: "True" [Use only a random subsample of all events for growing the trees in each boost iteration.]
AdaBoostBeta: "5.000000e-01" [Learning rate  for AdaBoost algorithm]
BaggedSampleFraction: "5.000000e-01" [Relative size of bagged event sample to original size of the data sample (used whenever bagging is used (i.e. UseBaggedBoost, Bagging,)]
SeparationType: "giniindex" [Separation criterion for node splitting]
# Default:
VerbosityLevel: "Default" [Verbosity level]
VarTransform: "None" [List of variable transformations performed before training, e.g., "D_Background,P_Signal,G,N_AllClasses" for: "Decorrelation, PCA-transformation, Gaussianisation, Normalisation, each for the given class of events ('AllClasses' denotes all events of all classes, if no class indication is given, 'All' is assumed)"]
CreateMVAPdfs: "False" [Create PDFs for classifier outputs (signal and background)]
AdaBoostR2Loss: "quadratic" [Type of Loss function in AdaBoostR2]
Shrinkage: "1.000000e+00" [Learning rate for GradBoost algorithm]
UseRandomisedTrees: "False" [Determine at each node splitting the cut variable only as the best out of a random subset of variables (like in RandomForests)]
UseNvars: "4" [Size of the subset of variables used with RandomisedTree option]
UsePoissonNvars: "True" [Interpret "UseNvars" not as fixed number but as mean of a Possion distribution in each split with RandomisedTree option]
UseYesNoLeaf: "True" [Use Sig or Bkg categories, or the purity=S/(S+B) as classification of the leaf node -> Real-AdaBoost]
NegWeightTreatment: "inverseboostnegweights" [How to treat events with negative weights in the BDT training (particular the boosting) : IgnoreInTraining;  Boost With inverse boostweight; Pair events with negative and positive weights in traning sample and *annihilate* them (experimental!)]
Css: "1.000000e+00" [AdaCost: cost of true signal selected signal]
Cts_sb: "1.000000e+00" [AdaCost: cost of true signal selected bkg]
Ctb_ss: "1.000000e+00" [AdaCost: cost of true bkg    selected signal]
Cbb: "1.000000e+00" [AdaCost: cost of true bkg    selected bkg ]
NodePurityLimit: "5.000000e-01" [In boosting/pruning, nodes with purity > NodePurityLimit are signal; background otherwise.]
DoBoostMonitor: "False" [Create control plot with ROC integral vs tree number]
UseFisherCuts: "False" [Use multivariate splits using the Fisher criterion]
MinLinCorrForFisher: "8.000000e-01" [The minimum linear correlation between two variables demanded for use in Fisher criterion in node splitting]
UseExclusiveVars: "False" [Variables already used in fisher criterion are not anymore analysed individually for node splitting]
DoPreselection: "False" [and and apply automatic pre-selection for 100% efficient signal (bkg) cuts prior to training]
SigToBkgFraction: "1.000000e+00" [Sig to Bkg ratio used in Training (similar to NodePurityLimit, which cannot be used in real adaboost]
PruneMethod: "nopruning" [Note: for BDTs use small trees (e.g.MaxDepth=3) and NoPruning:  Pruning: Method used for pruning (removal) of statistically insignificant branches ]
PruneStrength: "0.000000e+00" [Pruning strength]
PruningValFraction: "5.000000e-01" [Fraction of events to use for optimizing automatic pruning.]
nEventsMin: "0" [deprecated: Use MinNodeSize (in % of training events) instead]
UseBaggedGrad: "False" [deprecated: Use *UseBaggedBoost* instead:  Use only a random subsample of all events for growing the trees in each iteration.]
GradBaggingFraction: "5.000000e-01" [deprecated: Use *BaggedSampleFraction* instead: Defines the fraction of events to be used in each iteration, e.g. when UseBaggedGrad=kTRUE. ]
UseNTrainEvents: "0" [deprecated: Use *BaggedSampleFraction* instead: Number of randomly picked training events used in randomised (and bagged) trees]
NNodesMax: "0" [deprecated: Use MaxDepth instead to limit the tree size]
##


#VAR -*-*-*-*-*-*-*-*-*-*-*-* variables *-*-*-*-*-*-*-*-*-*-*-*-

NVar 15
mass_minBBdr                  mass_minBBdr                  mass_minBBdr                  mass_minBBdr                                                    'F'    [13.0974168777,1564.70178223]
lepDR_minBBdr                 lepDR_minBBdr                 lepDR_minBBdr                 lepDR_minBBdr                                                   'F'    [0.00337071181275,7.15712928772]
mass_maxBBpt                  mass_maxBBpt                  mass_maxBBpt                  mass_maxBBpt                                                    'F'    [14.5025548935,2982.28515625]
mass_maxBBmass                mass_maxBBmass                mass_maxBBmass                mass_maxBBmass                                                  'F'    [21.6002540588,3443.09277344]
mass_maxJJJpt                 mass_maxJJJpt                 mass_maxJJJpt                 mass_maxJJJpt                                                   'F'    [33.1896476746,4595.3671875]
aveBBdr                       aveBBdr                       aveBBdr                       aveBBdr                                                         'F'    [0.413950562477,4.35139703751]
AK4HTpMETpLepPt               AK4HTpMETpLepPt               AK4HTpMETpLepPt               AK4HTpMETpLepPt                                                 'F'    [183.69519043,5436.75683594]
minDR_lepJet                  minDR_lepJet                  minDR_lepJet                  minDR_lepJet                                                    'F'    [0.00083785620518,4.25620555878]
ptRel_lepJet                  ptRel_lepJet                  ptRel_lepJet                  ptRel_lepJet                                                    'F'    [0.0297780092806,2739.35083008]
deltaR_lepJets0               deltaR_lepJets0               deltaR_lepJets0               deltaR_lepJets0                                                 'F'    [0.00277139362879,5.58855867386]
deltaR_lepJets1               deltaR_lepJets1               deltaR_lepJets1               deltaR_lepJets1                                                 'F'    [0.00083785620518,5.58612394333]
deltaR_lepJets2               deltaR_lepJets2               deltaR_lepJets2               deltaR_lepJets2                                                 'F'    [0.00135830021463,5.65290594101]
mass_lepJJ_minJJdr            mass_lepJJ_minJJdr            mass_lepJJ_minJJdr            mass_lepJJ_minJJdr                                              'F'    [30.1947402954,4247.84912109]
NJets_JetSubCalc              NJets_JetSubCalc              NJets_JetSubCalc              NJets_JetSubCalc                                                'F'    [3,17]
minMleppBjet                  minMleppBjet                  minMleppBjet                  minMleppBjet                                                    'F'    [3.44846081734,1057.24353027]
NSpec 0


============================================================================ */

#include <vector>
#include <cmath>
#include <string>
#include <iostream>

#define NN new BDTNode
   
#ifndef BDTNode__def
#define BDTNode__def
   
class BDTNode {
   
public:
   
   // constructor of an essentially "empty" node floating in space
   BDTNode ( BDTNode* left,BDTNode* right,
                          int selector, double cutValue, bool cutType, 
                          int nodeType, double purity, double response ) :
   fLeft         ( left         ),
   fRight        ( right        ),
   fSelector     ( selector     ),
   fCutValue     ( cutValue     ),
   fCutType      ( cutType      ),
   fNodeType     ( nodeType     ),
   fPurity       ( purity       ),
   fResponse     ( response     ){
   }

   virtual ~BDTNode();

   // test event if it decends the tree at this node to the right
   virtual bool GoesRight( const std::vector<double>& inputValues ) const;
   BDTNode* GetRight( void )  {return fRight; };

   // test event if it decends the tree at this node to the left 
   virtual bool GoesLeft ( const std::vector<double>& inputValues ) const;
   BDTNode* GetLeft( void ) { return fLeft; };   

   // return  S/(S+B) (purity) at this node (from  training)

   double GetPurity( void ) const { return fPurity; } 
   // return the node type
   int    GetNodeType( void ) const { return fNodeType; }
   double GetResponse(void) const {return fResponse;}

private:

   BDTNode*   fLeft;     // pointer to the left daughter node
   BDTNode*   fRight;    // pointer to the right daughter node
   int                     fSelector; // index of variable used in node selection (decision tree)   
   double                  fCutValue; // cut value appplied on this node to discriminate bkg against sig
   bool                    fCutType;  // true: if event variable > cutValue ==> signal , false otherwise
   int                     fNodeType; // Type of node: -1 == Bkg-leaf, 1 == Signal-leaf, 0 = internal 
   double                  fPurity;   // Purity of node from training
   double                  fResponse; // Regression response value of node
}; 
   
//_______________________________________________________________________
   BDTNode::~BDTNode()
{
   if (fLeft  != NULL) delete fLeft;
   if (fRight != NULL) delete fRight;
}; 
   
//_______________________________________________________________________
bool BDTNode::GoesRight( const std::vector<double>& inputValues ) const
{
   // test event if it decends the tree at this node to the right
   bool result;
     result = (inputValues[fSelector] > fCutValue );
   if (fCutType == true) return result; //the cuts are selecting Signal ;
   else return !result;
}
   
//_______________________________________________________________________
bool BDTNode::GoesLeft( const std::vector<double>& inputValues ) const
{
   // test event if it decends the tree at this node to the left
   if (!this->GoesRight(inputValues)) return true;
   else return false;
}
   
#endif
   
#ifndef IClassifierReader__def
#define IClassifierReader__def

class IClassifierReader {

 public:

   // constructor
   IClassifierReader() : fStatusIsClean( true ) {}
   virtual ~IClassifierReader() {}

   // return classifier response
   virtual double GetMvaValue( const std::vector<double>& inputValues ) const = 0;

   // returns classifier status
   bool IsStatusClean() const { return fStatusIsClean; }

 protected:

   bool fStatusIsClean;
};

#endif

class ReadBDT : public IClassifierReader {

 public:

   // constructor
   ReadBDT( std::vector<std::string>& theInputVars ) 
      : IClassifierReader(),
        fClassName( "ReadBDT" ),
        fNvars( 15 ),
        fIsNormalised( false )
   {      
      // the training input variables
      const char* inputVars[] = { "mass_minBBdr", "lepDR_minBBdr", "mass_maxBBpt", "mass_maxBBmass", "mass_maxJJJpt", "aveBBdr", "AK4HTpMETpLepPt", "minDR_lepJet", "ptRel_lepJet", "deltaR_lepJets0", "deltaR_lepJets1", "deltaR_lepJets2", "mass_lepJJ_minJJdr", "NJets_JetSubCalc", "minMleppBjet" };

      // sanity checks
      if (theInputVars.size() <= 0) {
         std::cout << "Problem in class \"" << fClassName << "\": empty input vector" << std::endl;
         fStatusIsClean = false;
      }

      if (theInputVars.size() != fNvars) {
         std::cout << "Problem in class \"" << fClassName << "\": mismatch in number of input values: "
                   << theInputVars.size() << " != " << fNvars << std::endl;
         fStatusIsClean = false;
      }

      // validate input variables
      for (size_t ivar = 0; ivar < theInputVars.size(); ivar++) {
         if (theInputVars[ivar] != inputVars[ivar]) {
            std::cout << "Problem in class \"" << fClassName << "\": mismatch in input variable names" << std::endl
                      << " for variable [" << ivar << "]: " << theInputVars[ivar].c_str() << " != " << inputVars[ivar] << std::endl;
            fStatusIsClean = false;
         }
      }

      // initialize min and max vectors (for normalisation)
      fVmin[0] = 0;
      fVmax[0] = 0;
      fVmin[1] = 0;
      fVmax[1] = 0;
      fVmin[2] = 0;
      fVmax[2] = 0;
      fVmin[3] = 0;
      fVmax[3] = 0;
      fVmin[4] = 0;
      fVmax[4] = 0;
      fVmin[5] = 0;
      fVmax[5] = 0;
      fVmin[6] = 0;
      fVmax[6] = 0;
      fVmin[7] = 0;
      fVmax[7] = 0;
      fVmin[8] = 0;
      fVmax[8] = 0;
      fVmin[9] = 0;
      fVmax[9] = 0;
      fVmin[10] = 0;
      fVmax[10] = 0;
      fVmin[11] = 0;
      fVmax[11] = 0;
      fVmin[12] = 0;
      fVmax[12] = 0;
      fVmin[13] = 0;
      fVmax[13] = 0;
      fVmin[14] = 0;
      fVmax[14] = 0;

      // initialize input variable types
      fType[0] = 'F';
      fType[1] = 'F';
      fType[2] = 'F';
      fType[3] = 'F';
      fType[4] = 'F';
      fType[5] = 'F';
      fType[6] = 'F';
      fType[7] = 'F';
      fType[8] = 'F';
      fType[9] = 'F';
      fType[10] = 'F';
      fType[11] = 'F';
      fType[12] = 'F';
      fType[13] = 'F';
      fType[14] = 'F';

      // initialize constants
      Initialize();

   }

   // destructor
   virtual ~ReadBDT() {
      Clear(); // method-specific
   }

   // the classifier response
   // "inputValues" is a vector of input values in the same order as the 
   // variables given to the constructor
   double GetMvaValue( const std::vector<double>& inputValues ) const;

 private:

   // method-specific destructor
   void Clear();

   // common member variables
   const char* fClassName;

   const size_t fNvars;
   size_t GetNvar()           const { return fNvars; }
   char   GetType( int ivar ) const { return fType[ivar]; }

   // normalisation of input variables
   const bool fIsNormalised;
   bool IsNormalised() const { return fIsNormalised; }
   double fVmin[15];
   double fVmax[15];
   double NormVariable( double x, double xmin, double xmax ) const {
      // normalise to output range: [-1, 1]
      return 2*(x - xmin)/(xmax - xmin) - 1.0;
   }

   // type of input variable: 'F' or 'I'
   char   fType[15];

   // initialize internal variables
   void Initialize();
   double GetMvaValue__( const std::vector<double>& inputValues ) const;

   // private members (method specific)
   std::vector<BDTNode*> fForest;       // i.e. root nodes of decision trees
   std::vector<double>                fBoostWeights; // the weights applied in the individual boosts
};

double ReadBDT::GetMvaValue__( const std::vector<double>& inputValues ) const
{
   double myMVA = 0;
   double norm  = 0;
   for (unsigned int itree=0; itree<fForest.size(); itree++){
      BDTNode *current = fForest[itree];
      while (current->GetNodeType() == 0) { //intermediate node
         if (current->GoesRight(inputValues)) current=(BDTNode*)current->GetRight();
         else current=(BDTNode*)current->GetLeft();
      }
      myMVA += fBoostWeights[itree] *  current->GetNodeType();
      norm  += fBoostWeights[itree];
   }
   return myMVA /= norm;
};

void ReadBDT::Initialize()
{
  // itree = 0
  fBoostWeights.push_back(0.336550922936566);
  fForest.push_back( 
NN(
NN(
0, 
0, 
-1, 6.17647, 0, 1, 0.631237,-99) , 
NN(
NN(
NN(
0, 
0, 
-1, 0, 1, 1, 0.561995,-99) , 
NN(
0, 
0, 
-1, 0, 1, -1, 0.424448,-99) , 
6, 492.808, 0, 0, 0.496148,-99) , 
NN(
0, 
0, 
-1, 2.51578, 1, -1, 0.29601,-99) , 
2, 201.572, 0, 0, 0.324004,-99) , 
13, 4.09804, 0, 0, 0.509755,-99)    );
  // itree = 1
  fBoostWeights.push_back(0.230818);
  fForest.push_back( 
NN(
NN(
0, 
0, 
-1, 6.17647, 0, 1, 0.633689,-99) , 
NN(
0, 
0, 
-1, 0.405514, 0, -1, 0.398468,-99) , 
13, 5.11765, 0, 0, 0.480454,-99)    );
  // itree = 2
  fBoostWeights.push_back(0.208165);
  fForest.push_back( 
NN(
NN(
NN(
NN(
0, 
0, 
-1, 0, 1, 1, 0.651075,-99) , 
NN(
0, 
0, 
-1, 0, 1, -1, 0.467178,-99) , 
9, 3.2461, 1, 0, 0.627573,-99) , 
NN(
NN(
0, 
0, 
-1, 0, 1, 1, 0.561046,-99) , 
NN(
0, 
0, 
-1, 0, 1, -1, 0.439171,-99) , 
4, 272.056, 0, 0, 0.491447,-99) , 
0, 68.7357, 1, 0, 0.539551,-99) , 
NN(
0, 
0, 
-1, 0.743989, 0, -1, 0.275427,-99) , 
13, 3.23529, 0, 0, 0.505365,-99)    );
  // itree = 3
  fBoostWeights.push_back(0.146825);
  fForest.push_back( 
NN(
NN(
NN(
0, 
0, 
-1, 230.694, 0, 1, 0.641873,-99) , 
NN(
NN(
0, 
0, 
-1, 0, 1, 1, 0.580677,-99) , 
NN(
0, 
0, 
-1, 0, 1, -1, 0.479478,-99) , 
0, 56.4019, 1, 0, 0.524261,-99) , 
1, 2.28139, 1, 0, 0.588526,-99) , 
NN(
0, 
0, 
-1, 390.822, 0, -1, 0.433935,-99) , 
0, 84.133, 1, 0, 0.506278,-99)    );
  // itree = 4
  fBoostWeights.push_back(0.108447);
  fForest.push_back( 
NN(
NN(
NN(
NN(
0, 
0, 
-1, 0, 1, 1, 0.63382,-99) , 
NN(
0, 
0, 
-1, 0, 1, -1, 0.407417,-99) , 
9, 3.34043, 1, 0, 0.605102,-99) , 
NN(
NN(
0, 
0, 
-1, 0, 1, 1, 0.51263,-99) , 
NN(
0, 
0, 
-1, 0, 1, -1, 0.282077,-99) , 
11, 0.749725, 0, 0, 0.495242,-99) , 
1, 1.80261, 1, 0, 0.534146,-99) , 
NN(
NN(
NN(
0, 
0, 
-1, 0, 1, 1, 0.542769,-99) , 
NN(
0, 
0, 
-1, 0, 1, -1, 0.35022,-99) , 
9, 1.91713, 1, 0, 0.415316,-99) , 
NN(
0, 
0, 
-1, 0, 1, -1, 0.033258,-99) , 
7, 0.811028, 0, 0, 0.303876,-99) , 
13, 3.23529, 0, 0, 0.507688,-99)    );
  // itree = 5
  fBoostWeights.push_back(0.12982);
  fForest.push_back( 
NN(
NN(
NN(
0, 
0, 
-1, 67.8432, 1, 1, 0.615493,-99) , 
NN(
NN(
0, 
0, 
-1, 0, 1, 1, 0.560647,-99) , 
NN(
0, 
0, 
-1, 0, 1, -1, 0.470756,-99) , 
1, 1.8768, 1, 0, 0.499784,-99) , 
13, 6.05882, 0, 0, 0.519259,-99) , 
NN(
0, 
0, 
-1, 0, 1, -1, 0.244448,-99) , 
7, 0.323899, 0, 0, 0.489515,-99)    );
  // itree = 6
  fBoostWeights.push_back(0.096073);
  fForest.push_back( 
NN(
NN(
NN(
0, 
0, 
-1, 46.5653, 1, 1, 0.554157,-99) , 
NN(
0, 
0, 
-1, 286.285, 0, -1, 0.460387,-99) , 
6, 508.149, 0, 0, 0.512532,-99) , 
NN(
0, 
0, 
-1, 0, 1, -1, 0.258841,-99) , 
11, 0.646631, 0, 0, 0.492678,-99)    );
  // itree = 7
  fBoostWeights.push_back(0.111337);
  fForest.push_back( 
NN(
NN(
NN(
NN(
0, 
0, 
-1, 0, 1, 1, 0.548895,-99) , 
NN(
0, 
0, 
-1, 0, 1, -1, 0.481454,-99) , 
0, 98.5057, 1, 0, 0.520826,-99) , 
NN(
0, 
0, 
-1, 0, 1, -1, 0.353069,-99) , 
7, 0.251154, 0, 0, 0.512347,-99) , 
NN(
0, 
0, 
-1, 0, 1, -1, 0.193181,-99) , 
6, 288.758, 0, 0, 0.498795,-99)    );
  // itree = 8
  fBoostWeights.push_back(0.0784885);
  fForest.push_back( 
NN(
NN(
NN(
0, 
0, 
-1, 634.289, 0, 1, 0.62026,-99) , 
NN(
NN(
0, 
0, 
-1, 0, 1, 1, 0.542001,-99) , 
NN(
0, 
0, 
-1, 0, 1, -1, 0.462388,-99) , 
2, 133.915, 0, 0, 0.495712,-99) , 
14, 47.9642, 1, 0, 0.513023,-99) , 
NN(
0, 
0, 
-1, 0, 1, -1, 0.362971,-99) , 
14, 33.7304, 0, 0, 0.496673,-99)    );
  // itree = 9
  fBoostWeights.push_back(0.0847043);
  fForest.push_back( 
NN(
NN(
NN(
0, 
0, 
-1, 0.53811, 1, 1, 0.592899,-99) , 
NN(
NN(
0, 
0, 
-1, 0, 1, 1, 0.505023,-99) , 
NN(
0, 
0, 
-1, 0, 1, -1, 0.378618,-99) , 
13, 3.27451, 0, 0, 0.489844,-99) , 
1, 1.44736, 1, 0, 0.514778,-99) , 
NN(
0, 
0, 
-1, 0, 1, -1, 0.261465,-99) , 
7, 0.251154, 0, 0, 0.493047,-99)    );
  // itree = 10
  fBoostWeights.push_back(0.066367);
  fForest.push_back( 
NN(
NN(
NN(
0, 
0, 
-1, 63.0531, 1, 1, 0.562435,-99) , 
NN(
NN(
0, 
0, 
-1, 0, 1, 1, 0.504906,-99) , 
NN(
0, 
0, 
-1, 0, 1, -1, 0.427774,-99) , 
1, 2.88358, 1, 0, 0.483818,-99) , 
6, 786.323, 0, 0, 0.50056,-99) , 
NN(
0, 
0, 
-1, 0, 1, -1, 0.273512,-99) , 
7, 0.251643, 0, 0, 0.481896,-99)    );
  // itree = 11
  fBoostWeights.push_back(0.0632733);
  fForest.push_back( 
NN(
NN(
NN(
NN(
0, 
0, 
-1, 0, 1, 1, 0.608547,-99) , 
NN(
0, 
0, 
-1, 0, 1, -1, 0.477619,-99) , 
5, 2.31169, 1, 0, 0.564673,-99) , 
NN(
0, 
0, 
-1, 3.10417, 1, -1, 0.46591,-99) , 
14, 128.079, 0, 0, 0.475232,-99) , 
NN(
0, 
0, 
-1, 0, 1, -1, 0.223565,-99) , 
1, 3.85799, 1, 0, 0.466966,-99)    );
  // itree = 12
  fBoostWeights.push_back(0.0405108);
  fForest.push_back( 
NN(
NN(
NN(
NN(
0, 
0, 
-1, 0, 1, 1, 0.697206,-99) , 
NN(
0, 
0, 
-1, 0, 1, -1, 0.494383,-99) , 
7, 0.388272, 1, 0, 0.504665,-99) , 
NN(
0, 
0, 
-1, 0, 1, -1, 0.342887,-99) , 
7, 0.265985, 0, 0, 0.494962,-99) , 
NN(
NN(
NN(
0, 
0, 
-1, 0, 1, 1, 0.556192,-99) , 
NN(
0, 
0, 
-1, 0, 1, -1, 0.345229,-99) , 
11, 1.99916, 0, 0, 0.459715,-99) , 
NN(
0, 
0, 
-1, 0, 1, -1, 0.0749082,-99) , 
10, 1.07483, 0, 0, 0.327323,-99) , 
9, 3.45076, 1, 0, 0.479892,-99)    );
  // itree = 13
  fBoostWeights.push_back(0.0392988);
  fForest.push_back( 
NN(
NN(
0, 
0, 
-1, 57.9914, 0, 1, 0.546367,-99) , 
NN(
NN(
NN(
0, 
0, 
-1, 0, 1, 1, 0.627553,-99) , 
NN(
0, 
0, 
-1, 0, 1, -1, 0.496145,-99) , 
7, 1.27789, 0, 0, 0.546358,-99) , 
NN(
NN(
0, 
0, 
-1, 0, 1, 1, 0.510113,-99) , 
NN(
0, 
0, 
-1, 0, 1, -1, 0.442181,-99) , 
0, 82.753, 1, 0, 0.476808,-99) , 
2, 194.531, 0, 0, 0.4929,-99) , 
14, 62.7584, 1, 0, 0.511746,-99)    );
  // itree = 14
  fBoostWeights.push_back(0.0309797);
  fForest.push_back( 
NN(
NN(
NN(
NN(
0, 
0, 
-1, 0, 1, 1, 0.55683,-99) , 
NN(
0, 
0, 
-1, 0, 1, -1, 0.494453,-99) , 
4, 360.844, 0, 0, 0.509591,-99) , 
NN(
0, 
0, 
-1, 0, 1, -1, 0.307858,-99) , 
9, 0.541416, 0, 0, 0.503954,-99) , 
NN(
0, 
0, 
-1, 0, 1, -1, 0.236782,-99) , 
11, 0.555854, 0, 0, 0.487454,-99)    );
  // itree = 15
  fBoostWeights.push_back(0.0517528);
  fForest.push_back( 
NN(
NN(
NN(
NN(
0, 
0, 
-1, 0, 1, 1, 0.598033,-99) , 
NN(
0, 
0, 
-1, 0, 1, -1, 0.498148,-99) , 
3, 199.95, 0, 0, 0.53204,-99) , 
NN(
NN(
0, 
0, 
-1, 0, 1, 1, 0.634902,-99) , 
NN(
0, 
0, 
-1, 0, 1, -1, 0.462514,-99) , 
14, 139.061, 0, 0, 0.473268,-99) , 
0, 76.4463, 1, 0, 0.497766,-99) , 
NN(
0, 
0, 
-1, 0, 1, -1, 0.331679,-99) , 
7, 0.251154, 0, 0, 0.48757,-99)    );
  // itree = 16
  fBoostWeights.push_back(0.0555953);
  fForest.push_back( 
NN(
NN(
NN(
0, 
0, 
-1, 139.669, 0, 1, 0.529311,-99) , 
NN(
NN(
0, 
0, 
-1, 0, 1, 1, 0.507171,-99) , 
NN(
0, 
0, 
-1, 0, 1, -1, 0.332807,-99) , 
13, 4.17647, 0, 0, 0.442098,-99) , 
10, 2.97157, 1, 0, 0.512144,-99) , 
NN(
0, 
0, 
-1, 0, 1, -1, 0.228403,-99) , 
1, 3.7953, 1, 0, 0.499232,-99)    );
  // itree = 17
  fBoostWeights.push_back(0.0676988);
  fForest.push_back( 
NN(
NN(
NN(
NN(
0, 
0, 
-1, 0, 1, 1, 0.667669,-99) , 
NN(
0, 
0, 
-1, 0, 1, -1, 0.486092,-99) , 
5, 2.12606, 1, 0, 0.574889,-99) , 
NN(
NN(
0, 
0, 
-1, 0, 1, 1, 0.519084,-99) , 
NN(
0, 
0, 
-1, 0, 1, -1, 0.403835,-99) , 
8, 26.2567, 0, 0, 0.504874,-99) , 
13, 6.01961, 0, 0, 0.517428,-99) , 
NN(
0, 
0, 
-1, 3.0898, 1, -1, 0.368278,-99) , 
9, 1.08149, 0, 0, 0.502298,-99)    );
  // itree = 18
  fBoostWeights.push_back(0.0385238);
  fForest.push_back( 
NN(
NN(
NN(
0, 
0, 
-1, 479.378, 0, 1, 0.532511,-99) , 
NN(
0, 
0, 
-1, 0.35902, 0, -1, 0.47126,-99) , 
0, 85.4717, 1, 0, 0.501532,-99) , 
NN(
0, 
0, 
-1, 0, 1, -1, 0.19064,-99) , 
1, 3.93537, 1, 0, 0.490801,-99)    );
  // itree = 19
  fBoostWeights.push_back(0.0855275);
  fForest.push_back( 
NN(
NN(
NN(
NN(
0, 
0, 
-1, 0, 1, 1, 0.545846,-99) , 
NN(
0, 
0, 
-1, 0, 1, -1, 0.416932,-99) , 
10, 0.879002, 0, 0, 0.531369,-99) , 
NN(
NN(
0, 
0, 
-1, 0, 1, 1, 0.534948,-99) , 
NN(
0, 
0, 
-1, 0, 1, -1, 0.45541,-99) , 
14, 59.0882, 1, 0, 0.482512,-99) , 
3, 227.492, 0, 0, 0.503592,-99) , 
NN(
0, 
0, 
-1, 0, 1, -1, 0.289057,-99) , 
7, 0.251288, 0, 0, 0.488105,-99)    );
  // itree = 20
  fBoostWeights.push_back(0.0558607);
  fForest.push_back( 
NN(
NN(
NN(
0, 
0, 
-1, 0, 1, 1, 0.691855,-99) , 
NN(
NN(
0, 
0, 
-1, 0, 1, 1, 0.591424,-99) , 
NN(
0, 
0, 
-1, 0, 1, -1, 0.481729,-99) , 
14, 139.26, 0, 0, 0.488237,-99) , 
7, 0.405659, 1, 0, 0.501138,-99) , 
NN(
NN(
0, 
0, 
-1, 0, 1, 1, 0.536998,-99) , 
NN(
0, 
0, 
-1, 0, 1, -1, 0.189199,-99) , 
6, 429.85, 0, 0, 0.381684,-99) , 
14, 38.4297, 0, 0, 0.485211,-99)    );
  // itree = 21
  fBoostWeights.push_back(0.0315209);
  fForest.push_back( 
NN(
NN(
0, 
0, 
-1, 4.09804, 1, 1, 0.58955,-99) , 
NN(
NN(
NN(
0, 
0, 
-1, 0, 1, 1, 0.535984,-99) , 
NN(
0, 
0, 
-1, 0, 1, -1, 0.444273,-99) , 
9, 1.18585, 0, 0, 0.522921,-99) , 
NN(
0, 
0, 
-1, 2.77354, 1, -1, 0.460213,-99) , 
3, 241.787, 0, 0, 0.488313,-99) , 
5, 1.67151, 1, 0, 0.501106,-99)    );
  // itree = 22
  fBoostWeights.push_back(0.0655418);
  fForest.push_back( 
NN(
NN(
NN(
NN(
0, 
0, 
-1, 0, 1, 1, 0.552761,-99) , 
NN(
0, 
0, 
-1, 0, 1, -1, 0.452462,-99) , 
11, 1.56808, 0, 0, 0.529832,-99) , 
NN(
NN(
0, 
0, 
-1, 0, 1, 1, 0.542838,-99) , 
NN(
0, 
0, 
-1, 0, 1, -1, 0.442718,-99) , 
7, 0.874594, 1, 0, 0.472956,-99) , 
12, 211.421, 0, 0, 0.507207,-99) , 
NN(
NN(
NN(
0, 
0, 
-1, 0, 1, 1, 0.574292,-99) , 
NN(
0, 
0, 
-1, 0, 1, -1, 0.441947,-99) , 
10, 1.94206, 0, 0, 0.510809,-99) , 
NN(
0, 
0, 
-1, 0, 1, -1, 0.226288,-99) , 
8, 15.0021, 0, 0, 0.384538,-99) , 
8, 23.158, 0, 0, 0.491946,-99)    );
  // itree = 23
  fBoostWeights.push_back(0.0417662);
  fForest.push_back( 
NN(
NN(
NN(
0, 
0, 
-1, 46.5653, 1, 1, 0.536882,-99) , 
NN(
0, 
0, 
-1, 0.751222, 0, -1, 0.479189,-99) , 
5, 2.10854, 1, 0, 0.499108,-99) , 
NN(
0, 
0, 
-1, 0, 1, -1, 0.305514,-99) , 
1, 3.79065, 1, 0, 0.492281,-99)    );
  // itree = 24
  fBoostWeights.push_back(0.0527564);
  fForest.push_back( 
NN(
NN(
NN(
0, 
0, 
-1, 1.88997, 1, 1, 0.537827,-99) , 
NN(
NN(
0, 
0, 
-1, 0, 1, 1, 0.505202,-99) , 
NN(
0, 
0, 
-1, 0, 1, -1, 0.386614,-99) , 
1, 1.75494, 0, 0, 0.486056,-99) , 
14, 84.3651, 1, 0, 0.517922,-99) , 
NN(
NN(
NN(
0, 
0, 
-1, 0, 1, 1, 0.579108,-99) , 
NN(
0, 
0, 
-1, 0, 1, -1, 0.415855,-99) , 
10, 2.88225, 0, 0, 0.49396,-99) , 
NN(
0, 
0, 
-1, 0, 1, -1, 0.219973,-99) , 
14, 67.3556, 0, 0, 0.399749,-99) , 
1, 3.29201, 1, 0, 0.5056,-99)    );
  // itree = 25
  fBoostWeights.push_back(0.0548266);
  fForest.push_back( 
NN(
NN(
0, 
0, 
-1, 0, 1, 1, 0.577138,-99) , 
NN(
NN(
NN(
0, 
0, 
-1, 0, 1, 1, 0.530109,-99) , 
NN(
0, 
0, 
-1, 0, 1, -1, 0.426563,-99) , 
10, 0.804564, 0, 0, 0.506749,-99) , 
NN(
NN(
0, 
0, 
-1, 0, 1, 1, 0.598814,-99) , 
NN(
0, 
0, 
-1, 0, 1, -1, 0.458259,-99) , 
12, 608.238, 0, 0, 0.465169,-99) , 
10, 1.70837, 1, 0, 0.479813,-99) , 
13, 7.09804, 0, 0, 0.486787,-99)    );
  // itree = 26
  fBoostWeights.push_back(0.0157017);
  fForest.push_back( 
NN(
NN(
0, 
0, 
-1, 0, 1, 1, 0.712594,-99) , 
NN(
NN(
NN(
0, 
0, 
-1, 0, 1, 1, 0.511469,-99) , 
NN(
0, 
0, 
-1, 0, 1, -1, 0.392834,-99) , 
10, 3.5248, 1, 0, 0.506262,-99) , 
NN(
0, 
0, 
-1, 0, 1, -1, 0.330215,-99) , 
9, 0.659923, 0, 0, 0.497744,-99) , 
10, 0.551653, 1, 0, 0.509427,-99)    );
  // itree = 27
  fBoostWeights.push_back(0.0310688);
  fForest.push_back( 
NN(
NN(
NN(
0, 
0, 
-1, 3.65522, 0, 1, 0.512237,-99) , 
NN(
0, 
0, 
-1, 0.729188, 0, -1, 0.360363,-99) , 
9, 3.46316, 1, 0, 0.497883,-99) , 
NN(
0, 
0, 
-1, 0, 1, -1, 0.304528,-99) , 
9, 0.661494, 0, 0, 0.489685,-99)    );
  // itree = 28
  fBoostWeights.push_back(0.0448417);
  fForest.push_back( 
NN(
NN(
NN(
0, 
0, 
-1, 0.533345, 1, 1, 0.567222,-99) , 
NN(
NN(
0, 
0, 
-1, 0, 1, 1, 0.626666,-99) , 
NN(
0, 
0, 
-1, 0, 1, -1, 0.479895,-99) , 
1, 3.46575, 0, 0, 0.48676,-99) , 
1, 1.27392, 1, 0, 0.501829,-99) , 
NN(
NN(
NN(
0, 
0, 
-1, 0, 1, 1, 0.562341,-99) , 
NN(
0, 
0, 
-1, 0, 1, -1, 0.408279,-99) , 
13, 5.15686, 1, 0, 0.483735,-99) , 
NN(
0, 
0, 
-1, 0, 1, -1, 0.296756,-99) , 
6, 484.182, 0, 0, 0.42343,-99) , 
9, 3.30963, 1, 0, 0.493467,-99)    );
  // itree = 29
  fBoostWeights.push_back(0.034309);
  fForest.push_back( 
NN(
NN(
NN(
0, 
0, 
-1, 0, 1, 1, 0.649985,-99) , 
NN(
NN(
0, 
0, 
-1, 0, 1, 1, 0.525639,-99) , 
NN(
0, 
0, 
-1, 0, 1, -1, 0.437825,-99) , 
5, 2.43831, 0, 0, 0.466653,-99) , 
14, 69.1758, 1, 0, 0.56091,-99) , 
NN(
NN(
NN(
0, 
0, 
-1, 0, 1, 1, 0.511008,-99) , 
NN(
0, 
0, 
-1, 0, 1, -1, 0.459743,-99) , 
9, 1.84604, 0, 0, 0.497958,-99) , 
NN(
0, 
0, 
-1, 0, 1, -1, 0.328388,-99) , 
7, 0.324817, 0, 0, 0.485178,-99) , 
13, 6.01961, 0, 0, 0.499125,-99)    );
  // itree = 30
  fBoostWeights.push_back(0.0185251);
  fForest.push_back( 
NN(
NN(
NN(
0, 
0, 
-1, 0, 1, 1, 0.612798,-99) , 
NN(
NN(
0, 
0, 
-1, 0, 1, 1, 0.501883,-99) , 
NN(
0, 
0, 
-1, 0, 1, -1, 0.435537,-99) , 
11, 0.937361, 0, 0, 0.495018,-99) , 
9, 3.77459, 0, 0, 0.498202,-99) , 
NN(
0, 
0, 
-1, 0, 1, -1, 0.334647,-99) , 
1, 3.82723, 1, 0, 0.491761,-99)    );
  // itree = 31
  fBoostWeights.push_back(0);
  fForest.push_back( 
NN(
NN(
NN(
0, 
0, 
-1, 0, 1, 1, 0.608069,-99) , 
NN(
NN(
0, 
0, 
-1, 0, 1, 1, 0.502929,-99) , 
NN(
0, 
0, 
-1, 0, 1, -1, 0.408689,-99) , 
10, 3.31198, 1, 0, 0.496851,-99) , 
10, 0.532202, 1, 0, 0.501749,-99) , 
NN(
0, 
0, 
-1, 0, 1, -1, 0.295635,-99) , 
1, 3.84044, 1, 0, 0.495234,-99)    );
  // itree = 32
  fBoostWeights.push_back(0.0528365);
  fForest.push_back( 
NN(
NN(
NN(
NN(
0, 
0, 
-1, 0, 1, 1, 0.539121,-99) , 
NN(
0, 
0, 
-1, 0, 1, -1, 0.49838,-99) , 
14, 75.8615, 1, 0, 0.51712,-99) , 
NN(
NN(
0, 
0, 
-1, 0, 1, 1, 0.529803,-99) , 
NN(
0, 
0, 
-1, 0, 1, -1, 0.396006,-99) , 
9, 2.99014, 0, 0, 0.436546,-99) , 
11, 3.10601, 1, 0, 0.506467,-99) , 
NN(
0, 
0, 
-1, 0, 1, -1, 0.364134,-99) , 
14, 33.1035, 0, 0, 0.494216,-99)    );
  // itree = 33
  fBoostWeights.push_back(0.0440391);
  fForest.push_back( 
NN(
NN(
NN(
NN(
0, 
0, 
-1, 0, 1, 1, 0.52455,-99) , 
NN(
0, 
0, 
-1, 0, 1, -1, 0.463665,-99) , 
4, 219.213, 0, 0, 0.495058,-99) , 
NN(
0, 
0, 
-1, 0, 1, -1, 0.378719,-99) , 
11, 0.644565, 0, 0, 0.488359,-99) , 
NN(
NN(
NN(
0, 
0, 
-1, 0, 1, 1, 0.561384,-99) , 
NN(
0, 
0, 
-1, 0, 1, -1, 0.319651,-99) , 
14, 86.0106, 1, 0, 0.443354,-99) , 
NN(
0, 
0, 
-1, 0, 1, -1, 0.146369,-99) , 
0, 133.48, 1, 0, 0.34083,-99) , 
9, 3.45076, 1, 0, 0.475043,-99)    );
  // itree = 34
  fBoostWeights.push_back(0.0212801);
  fForest.push_back( 
NN(
NN(
NN(
0, 
0, 
-1, 0, 1, 1, 0.616074,-99) , 
NN(
0, 
0, 
-1, 551.514, 1, -1, 0.493712,-99) , 
7, 0.334592, 1, 0, 0.504658,-99) , 
NN(
NN(
NN(
0, 
0, 
-1, 0, 1, 1, 0.552311,-99) , 
NN(
0, 
0, 
-1, 0, 1, -1, 0.422344,-99) , 
1, 2.50337, 0, 0, 0.494841,-99) , 
NN(
0, 
0, 
-1, 0, 1, -1, 0.205253,-99) , 
14, 49.0878, 0, 0, 0.402651,-99) , 
6, 353.328, 0, 0, 0.491003,-99)    );
  // itree = 35
  fBoostWeights.push_back(0);
  fForest.push_back( 
NN(
NN(
NN(
0, 
0, 
-1, 2.49158, 0, 1, 0.515645,-99) , 
NN(
NN(
0, 
0, 
-1, 0, 1, 1, 0.522814,-99) , 
NN(
0, 
0, 
-1, 0, 1, -1, 0.418257,-99) , 
7, 1.62117, 0, 0, 0.454053,-99) , 
14, 107.431, 1, 0, 0.503931,-99) , 
NN(
0, 
0, 
-1, 0, 1, -1, 0.329069,-99) , 
10, 0.548415, 0, 0, 0.49539,-99)    );
  // itree = 36
  fBoostWeights.push_back(0.0282258);
  fForest.push_back( 
NN(
NN(
NN(
NN(
0, 
0, 
-1, 0, 1, 1, 0.615083,-99) , 
NN(
0, 
0, 
-1, 0, 1, -1, 0.487312,-99) , 
7, 0.444392, 1, 0, 0.492522,-99) , 
NN(
NN(
0, 
0, 
-1, 0, 1, 1, 0.58344,-99) , 
NN(
0, 
0, 
-1, 0, 1, -1, 0.316347,-99) , 
12, 192.356, 1, 0, 0.421555,-99) , 
8, 21.4905, 0, 0, 0.484211,-99) , 
NN(
0, 
0, 
-1, 0, 1, -1, 0.272754,-99) , 
6, 287.844, 0, 0, 0.477881,-99)    );
  // itree = 37
  fBoostWeights.push_back(0.0317035);
  fForest.push_back( 
NN(
NN(
NN(
0, 
0, 
-1, 2.55467, 0, 1, 0.519735,-99) , 
NN(
0, 
0, 
-1, 0.962245, 0, -1, 0.447626,-99) , 
9, 2.95995, 1, 0, 0.498996,-99) , 
NN(
0, 
0, 
-1, 0, 1, -1, 0.264125,-99) , 
6, 287.844, 0, 0, 0.491287,-99)    );
  // itree = 38
  fBoostWeights.push_back(0.0375715);
  fForest.push_back( 
NN(
NN(
NN(
NN(
0, 
0, 
-1, 0, 1, 1, 0.518614,-99) , 
NN(
0, 
0, 
-1, 0, 1, -1, 0.366391,-99) , 
10, 3.5088, 1, 0, 0.513225,-99) , 
NN(
NN(
0, 
0, 
-1, 0, 1, 1, 0.512443,-99) , 
NN(
0, 
0, 
-1, 0, 1, -1, 0.336525,-99) , 
9, 3.60969, 0, 0, 0.422591,-99) , 
9, 3.31532, 1, 0, 0.504388,-99) , 
NN(
0, 
0, 
-1, 0, 1, -1, 0.280912,-99) , 
7, 0.25148, 0, 0, 0.486834,-99)    );
  // itree = 39
  fBoostWeights.push_back(0.0523766);
  fForest.push_back( 
NN(
NN(
NN(
0, 
0, 
-1, 0, 1, 1, 0.670332,-99) , 
NN(
NN(
0, 
0, 
-1, 0, 1, 1, 0.555006,-99) , 
NN(
0, 
0, 
-1, 0, 1, -1, 0.473191,-99) , 
11, 2.48012, 1, 0, 0.524292,-99) , 
7, 0.572292, 1, 0, 0.569778,-99) , 
NN(
NN(
NN(
0, 
0, 
-1, 0, 1, 1, 0.554963,-99) , 
NN(
0, 
0, 
-1, 0, 1, -1, 0.473034,-99) , 
5, 1.92272, 1, 0, 0.494068,-99) , 
NN(
0, 
0, 
-1, 3.51045, 1, -1, 0.420095,-99) , 
4, 296.098, 1, 0, 0.471427,-99) , 
13, 6.01961, 0, 0, 0.489122,-99)    );
  // itree = 40
  fBoostWeights.push_back(0.0229308);
  fForest.push_back( 
NN(
NN(
NN(
NN(
0, 
0, 
-1, 0, 1, 1, 0.509339,-99) , 
NN(
0, 
0, 
-1, 0, 1, -1, 0.458866,-99) , 
5, 1.99341, 0, 0, 0.496443,-99) , 
NN(
0, 
0, 
-1, 104.649, 1, -1, 0.392249,-99) , 
10, 0.876961, 0, 0, 0.486808,-99) , 
NN(
0, 
0, 
-1, 0, 1, -1, 0.279434,-99) , 
9, 0.550398, 0, 0, 0.481017,-99)    );
  // itree = 41
  fBoostWeights.push_back(0);
  fForest.push_back( 
NN(
NN(
0, 
0, 
-1, 1.60243, 1, 1, 0.512904,-99) , 
NN(
0, 
0, 
-1, 0, 1, -1, 0.235827,-99) , 
1, 3.92981, 1, 0, 0.504923,-99)    );
  // itree = 42
  fBoostWeights.push_back(0.0502234);
  fForest.push_back( 
NN(
NN(
NN(
0, 
0, 
-1, 0, 1, 1, 0.662437,-99) , 
NN(
NN(
0, 
0, 
-1, 0, 1, 1, 0.519899,-99) , 
NN(
0, 
0, 
-1, 0, 1, -1, 0.473638,-99) , 
13, 5.19608, 1, 0, 0.504173,-99) , 
7, 0.324695, 1, 0, 0.510763,-99) , 
NN(
NN(
0, 
0, 
-1, 0, 1, 1, 0.580402,-99) , 
NN(
0, 
0, 
-1, 0, 1, -1, 0.273957,-99) , 
8, 19.4213, 0, 0, 0.403022,-99) , 
14, 35.7376, 0, 0, 0.498952,-99)    );
  // itree = 43
  fBoostWeights.push_back(0.0368519);
  fForest.push_back( 
NN(
NN(
NN(
NN(
0, 
0, 
-1, 0, 1, 1, 0.617959,-99) , 
NN(
0, 
0, 
-1, 0, 1, -1, 0.49926,-99) , 
1, 2.10904, 0, 0, 0.573733,-99) , 
NN(
NN(
0, 
0, 
-1, 0, 1, 1, 0.538093,-99) , 
NN(
0, 
0, 
-1, 0, 1, -1, 0.474945,-99) , 
2, 194.575, 0, 0, 0.487424,-99) , 
12, 472.271, 0, 0, 0.496464,-99) , 
NN(
0, 
0, 
-1, 0, 1, -1, 0.37023,-99) , 
7, 0.324497, 0, 0, 0.486336,-99)    );
  // itree = 44
  fBoostWeights.push_back(0.0148933);
  fForest.push_back( 
NN(
NN(
NN(
NN(
0, 
0, 
-1, 0, 1, 1, 0.580394,-99) , 
NN(
0, 
0, 
-1, 0, 1, -1, 0.499428,-99) , 
6, 366.018, 1, 0, 0.512388,-99) , 
NN(
0, 
0, 
-1, 3.07895, 1, -1, 0.460992,-99) , 
14, 56.5345, 0, 0, 0.499317,-99) , 
NN(
0, 
0, 
-1, 0, 1, -1, 0.257423,-99) , 
11, 0.555432, 0, 0, 0.486286,-99)    );
  // itree = 45
  fBoostWeights.push_back(0.0180631);
  fForest.push_back( 
NN(
NN(
NN(
NN(
0, 
0, 
-1, 0, 1, 1, 0.519544,-99) , 
NN(
0, 
0, 
-1, 0, 1, -1, 0.4596,-99) , 
11, 1.33317, 0, 0, 0.506827,-99) , 
NN(
0, 
0, 
-1, 0, 1, -1, 0.356155,-99) , 
7, 2.08687, 1, 0, 0.50229,-99) , 
NN(
0, 
0, 
-1, 0, 1, -1, 0.352078,-99) , 
5, 3.19419, 1, 0, 0.498028,-99)    );
  // itree = 46
  fBoostWeights.push_back(0.0233814);
  fForest.push_back( 
NN(
NN(
NN(
0, 
0, 
-1, 0, 1, 1, 0.616356,-99) , 
NN(
NN(
0, 
0, 
-1, 0, 1, 1, 0.512529,-99) , 
NN(
0, 
0, 
-1, 0, 1, -1, 0.444267,-99) , 
6, 346.507, 0, 0, 0.505102,-99) , 
14, 32.782, 1, 0, 0.51095,-99) , 
NN(
0, 
0, 
-1, 0, 1, -1, 0.371793,-99) , 
7, 0.324695, 0, 0, 0.500447,-99)    );
  // itree = 47
  fBoostWeights.push_back(0.0232242);
  fForest.push_back( 
NN(
NN(
NN(
0, 
0, 
-1, 443.336, 1, 1, 0.57861,-99) , 
NN(
0, 
0, 
-1, 120.209, 0, -1, 0.430919,-99) , 
3, 351.286, 1, 0, 0.543875,-99) , 
NN(
NN(
0, 
0, 
-1, 0, 1, 1, 0.625268,-99) , 
NN(
NN(
0, 
0, 
-1, 0, 1, 1, 0.525407,-99) , 
NN(
0, 
0, 
-1, 0, 1, -1, 0.464517,-99) , 
2, 69.5689, 1, 0, 0.478897,-99) , 
7, 2.10262, 0, 0, 0.484394,-99) , 
12, 332.238, 0, 0, 0.500595,-99)    );
  // itree = 48
  fBoostWeights.push_back(0.0258961);
  fForest.push_back( 
NN(
NN(
NN(
0, 
0, 
-1, 70.338, 0, 1, 0.534985,-99) , 
NN(
NN(
0, 
0, 
-1, 0, 1, 1, 0.621352,-99) , 
NN(
0, 
0, 
-1, 0, 1, -1, 0.475436,-99) , 
2, 347.142, 0, 0, 0.485169,-99) , 
0, 75.2104, 1, 0, 0.506678,-99) , 
NN(
0, 
0, 
-1, 5.11765, 0, -1, 0.379609,-99) , 
0, 199.438, 1, 0, 0.498338,-99)    );
  // itree = 49
  fBoostWeights.push_back(0.0405951);
  fForest.push_back( 
NN(
NN(
NN(
0, 
0, 
-1, 2.9157, 0, 1, 0.588622,-99) , 
NN(
NN(
0, 
0, 
-1, 0, 1, 1, 0.516187,-99) , 
NN(
0, 
0, 
-1, 0, 1, -1, 0.452617,-99) , 
9, 2.69709, 1, 0, 0.48904,-99) , 
13, 6.01961, 0, 0, 0.50812,-99) , 
NN(
0, 
0, 
-1, 0, 1, -1, 0.230565,-99) , 
6, 286.696, 0, 0, 0.500152,-99)    );
  // itree = 50
  fBoostWeights.push_back(0.0532507);
  fForest.push_back( 
NN(
NN(
NN(
0, 
0, 
-1, 272.124, 1, 1, 0.544502,-99) , 
NN(
NN(
0, 
0, 
-1, 0, 1, 1, 0.505706,-99) , 
NN(
0, 
0, 
-1, 0, 1, -1, 0.423172,-99) , 
14, 105.731, 0, 0, 0.4747,-99) , 
14, 86.7004, 1, 0, 0.514775,-99) , 
NN(
NN(
0, 
0, 
-1, 255.172, 0, 1, 0.537678,-99) , 
NN(
NN(
0, 
0, 
-1, 0, 1, 1, 0.588533,-99) , 
NN(
0, 
0, 
-1, 0, 1, -1, 0.426915,-99) , 
12, 398.182, 0, 0, 0.442727,-99) , 
8, 66.4839, 0, 0, 0.476699,-99) , 
6, 529.133, 0, 0, 0.496702,-99)    );
  // itree = 51
  fBoostWeights.push_back(0.0154444);
  fForest.push_back( 
NN(
NN(
0, 
0, 
-1, 0, 1, 1, 0.603673,-99) , 
NN(
NN(
NN(
0, 
0, 
-1, 0, 1, 1, 0.505017,-99) , 
NN(
0, 
0, 
-1, 0, 1, -1, 0.403958,-99) , 
10, 0.882613, 0, 0, 0.491858,-99) , 
NN(
NN(
0, 
0, 
-1, 0, 1, 1, 0.511185,-99) , 
NN(
0, 
0, 
-1, 0, 1, -1, 0.35763,-99) , 
6, 599.233, 0, 0, 0.419504,-99) , 
10, 2.99706, 1, 0, 0.478987,-99) , 
12, 629.858, 0, 0, 0.484381,-99)    );
  // itree = 52
  fBoostWeights.push_back(0.0362638);
  fForest.push_back( 
NN(
NN(
NN(
0, 
0, 
-1, 0, 1, 1, 0.661188,-99) , 
NN(
NN(
0, 
0, 
-1, 0, 1, 1, 0.548884,-99) , 
NN(
0, 
0, 
-1, 0, 1, -1, 0.481574,-99) , 
9, 3.25876, 0, 0, 0.490459,-99) , 
7, 0.324817, 1, 0, 0.497276,-99) , 
NN(
0, 
0, 
-1, 0, 1, -1, 0.390127,-99) , 
14, 33.5422, 0, 0, 0.487009,-99)    );
  // itree = 53
  fBoostWeights.push_back(0.0265203);
  fForest.push_back( 
NN(
NN(
NN(
0, 
0, 
-1, 0.386771, 1, 1, 0.51498,-99) , 
NN(
0, 
0, 
-1, 0, 1, -1, 0.393877,-99) , 
7, 0.265019, 0, 0, 0.507942,-99) , 
NN(
0, 
0, 
-1, 3.71161, 0, -1, 0.39504,-99) , 
9, 3.50758, 1, 0, 0.500637,-99)    );
  // itree = 54
  fBoostWeights.push_back(0.0264047);
  fForest.push_back( 
NN(
NN(
NN(
NN(
0, 
0, 
-1, 0, 1, 1, 0.626717,-99) , 
NN(
0, 
0, 
-1, 0, 1, -1, 0.489813,-99) , 
7, 0.282991, 1, 0, 0.495839,-99) , 
NN(
0, 
0, 
-1, 0, 1, -1, 0.333943,-99) , 
9, 3.95324, 1, 0, 0.491124,-99) , 
NN(
0, 
0, 
-1, 0, 1, -1, 0.356158,-99) , 
11, 0.556519, 0, 0, 0.484947,-99)    );
  // itree = 55
  fBoostWeights.push_back(0.0174014);
  fForest.push_back( 
NN(
NN(
0, 
0, 
-1, 0, 1, 1, 0.598756,-99) , 
NN(
0, 
0, 
-1, 3.90248, 1, -1, 0.486871,-99) , 
4, 119.428, 1, 0, 0.495023,-99)    );
  // itree = 56
  fBoostWeights.push_back(0.0199322);
  fForest.push_back( 
NN(
NN(
NN(
0, 
0, 
-1, 0.324695, 1, 1, 0.520953,-99) , 
NN(
NN(
0, 
0, 
-1, 0, 1, 1, 0.502,-99) , 
NN(
0, 
0, 
-1, 0, 1, -1, 0.275512,-99) , 
7, 0.438952, 0, 0, 0.459246,-99) , 
3, 363.231, 1, 0, 0.510707,-99) , 
NN(
0, 
0, 
-1, 0, 1, -1, 0.361564,-99) , 
9, 0.540152, 0, 0, 0.506042,-99)    );
  // itree = 57
  fBoostWeights.push_back(0.0362836);
  fForest.push_back( 
NN(
NN(
NN(
0, 
0, 
-1, 445.182, 1, 1, 0.629489,-99) , 
NN(
NN(
0, 
0, 
-1, 0, 1, 1, 0.535977,-99) , 
NN(
0, 
0, 
-1, 0, 1, -1, 0.434561,-99) , 
13, 4.09804, 1, 0, 0.497819,-99) , 
9, 3.00891, 0, 0, 0.539012,-99) , 
NN(
NN(
NN(
0, 
0, 
-1, 0, 1, 1, 0.513854,-99) , 
NN(
0, 
0, 
-1, 0, 1, -1, 0.368216,-99) , 
8, 15.2093, 0, 0, 0.502505,-99) , 
NN(
0, 
0, 
-1, 2.59326, 0, -1, 0.443266,-99) , 
14, 101.983, 1, 0, 0.491802,-99) , 
7, 1.53924, 0, 0, 0.500397,-99)    );
  // itree = 58
  fBoostWeights.push_back(0.0191956);
  fForest.push_back( 
NN(
NN(
NN(
NN(
0, 
0, 
-1, 0, 1, 1, 0.565304,-99) , 
NN(
0, 
0, 
-1, 0, 1, -1, 0.493046,-99) , 
11, 1.10714, 1, 0, 0.503615,-99) , 
NN(
0, 
0, 
-1, 392.814, 0, -1, 0.453907,-99) , 
10, 2.55206, 1, 0, 0.486405,-99) , 
NN(
0, 
0, 
-1, 0, 1, -1, 0.330919,-99) , 
9, 0.769448, 0, 0, 0.479366,-99)    );
  // itree = 59
  fBoostWeights.push_back(0.0205945);
  fForest.push_back( 
NN(
NN(
0, 
0, 
-1, 0, 1, 1, 0.725649,-99) , 
NN(
NN(
NN(
0, 
0, 
-1, 0, 1, 1, 0.540577,-99) , 
NN(
0, 
0, 
-1, 0, 1, -1, 0.49354,-99) , 
9, 3.02015, 0, 0, 0.505098,-99) , 
NN(
0, 
0, 
-1, 0, 1, -1, 0.374783,-99) , 
1, 3.66864, 1, 0, 0.499521,-99) , 
10, 0.53295, 1, 0, 0.512174,-99)    );
  // itree = 60
  fBoostWeights.push_back(0.0309432);
  fForest.push_back( 
NN(
NN(
NN(
0, 
0, 
-1, 347.085, 0, 1, 0.556925,-99) , 
NN(
NN(
0, 
0, 
-1, 0, 1, 1, 0.511242,-99) , 
NN(
0, 
0, 
-1, 0, 1, -1, 0.391256,-99) , 
8, 106.942, 1, 0, 0.500581,-99) , 
7, 1.53676, 0, 0, 0.509749,-99) , 
NN(
NN(
NN(
0, 
0, 
-1, 0, 1, 1, 0.597887,-99) , 
NN(
0, 
0, 
-1, 0, 1, -1, 0.473686,-99) , 
6, 330.435, 1, 0, 0.536203,-99) , 
NN(
0, 
0, 
-1, 50.8497, 0, -1, 0.207,-99) , 
1, 2.54213, 1, 0, 0.366463,-99) , 
13, 3.27451, 0, 0, 0.493995,-99)    );
  // itree = 61
  fBoostWeights.push_back(0.0273094);
  fForest.push_back( 
NN(
NN(
NN(
0, 
0, 
-1, 0.410738, 1, 1, 0.52488,-99) , 
NN(
NN(
0, 
0, 
-1, 0, 1, 1, 0.526104,-99) , 
NN(
0, 
0, 
-1, 0, 1, -1, 0.315594,-99) , 
0, 97.7473, 1, 0, 0.434083,-99) , 
9, 3.45121, 1, 0, 0.51844,-99) , 
NN(
NN(
NN(
0, 
0, 
-1, 0, 1, 1, 0.515806,-99) , 
NN(
0, 
0, 
-1, 0, 1, -1, 0.399008,-99) , 
3, 172.299, 0, 0, 0.4792,-99) , 
NN(
0, 
0, 
-1, 0, 1, -1, 0.278627,-99) , 
13, 3.21569, 0, 0, 0.451488,-99) , 
10, 2.99729, 1, 0, 0.506156,-99)    );
  // itree = 62
  fBoostWeights.push_back(0.0403102);
  fForest.push_back( 
NN(
NN(
0, 
0, 
-1, 114.908, 0, 1, 0.609457,-99) , 
NN(
0, 
0, 
-1, 3.70225, 1, -1, 0.471156,-99) , 
4, 130.666, 1, 0, 0.487852,-99)    );
  // itree = 63
  fBoostWeights.push_back(0.0124915);
  fForest.push_back( 
NN(
NN(
NN(
0, 
0, 
-1, 50.7902, 1, 1, 0.553717,-99) , 
NN(
NN(
0, 
0, 
-1, 0, 1, 1, 0.510393,-99) , 
NN(
0, 
0, 
-1, 0, 1, -1, 0.398242,-99) , 
8, 19.3454, 0, 0, 0.500059,-99) , 
6, 786.323, 0, 0, 0.511615,-99) , 
NN(
0, 
0, 
-1, 0, 1, -1, 0.298972,-99) , 
9, 3.96181, 1, 0, 0.504834,-99)    );
  // itree = 64
  fBoostWeights.push_back(0.022143);
  fForest.push_back( 
NN(
NN(
NN(
0, 
0, 
-1, 134.215, 1, 1, 0.521657,-99) , 
NN(
0, 
0, 
-1, 2.97711, 1, -1, 0.469485,-99) , 
3, 162.37, 0, 0, 0.504257,-99) , 
NN(
NN(
NN(
0, 
0, 
-1, 0, 1, 1, 0.535759,-99) , 
NN(
0, 
0, 
-1, 0, 1, -1, 0.46671,-99) , 
1, 3.04988, 0, 0, 0.501263,-99) , 
NN(
0, 
0, 
-1, 88.8185, 0, -1, 0.395056,-99) , 
9, 2.82957, 0, 0, 0.434732,-99) , 
11, 3.10438, 1, 0, 0.4948,-99)    );
  // itree = 65
  fBoostWeights.push_back(0.0116617);
  fForest.push_back( 
NN(
NN(
NN(
NN(
0, 
0, 
-1, 0, 1, 1, 0.512596,-99) , 
NN(
0, 
0, 
-1, 0, 1, -1, 0.393441,-99) , 
3, 569.885, 1, 0, 0.508398,-99) , 
NN(
NN(
0, 
0, 
-1, 0, 1, 1, 0.583651,-99) , 
NN(
0, 
0, 
-1, 0, 1, -1, 0.399337,-99) , 
2, 236.538, 0, 0, 0.438444,-99) , 
11, 3.14468, 1, 0, 0.499567,-99) , 
NN(
0, 
0, 
-1, 0, 1, -1, 0.387661,-99) , 
11, 0.553762, 0, 0, 0.495819,-99)    );
  // itree = 66
  fBoostWeights.push_back(0.0136548);
  fForest.push_back( 
NN(
NN(
NN(
0, 
0, 
-1, 3.65366, 0, 1, 0.505192,-99) , 
NN(
NN(
0, 
0, 
-1, 0, 1, 1, 0.546605,-99) , 
NN(
0, 
0, 
-1, 0, 1, -1, 0.365959,-99) , 
2, 106.846, 1, 0, 0.427434,-99) , 
9, 3.46686, 1, 0, 0.498621,-99) , 
NN(
0, 
0, 
-1, 0, 1, -1, 0.30026,-99) , 
9, 0.669976, 0, 0, 0.490587,-99)    );
  // itree = 67
  fBoostWeights.push_back(0.0242464);
  fForest.push_back( 
NN(
NN(
NN(
0, 
0, 
-1, 0.418031, 1, 1, 0.530667,-99) , 
NN(
NN(
0, 
0, 
-1, 0, 1, 1, 0.551366,-99) , 
NN(
0, 
0, 
-1, 0, 1, -1, 0.456132,-99) , 
4, 155.904, 1, 0, 0.474936,-99) , 
11, 2.37279, 0, 0, 0.499684,-99) , 
NN(
NN(
NN(
0, 
0, 
-1, 0, 1, 1, 0.511996,-99) , 
NN(
0, 
0, 
-1, 0, 1, -1, 0.378019,-99) , 
2, 122.097, 1, 0, 0.460463,-99) , 
NN(
0, 
0, 
-1, 0, 1, -1, 0.283736,-99) , 
5, 2.54906, 1, 0, 0.414404,-99) , 
9, 1.09802, 0, 0, 0.490703,-99)    );
  // itree = 68
  fBoostWeights.push_back(0.00534719);
  fForest.push_back( 
NN(
NN(
NN(
0, 
0, 
-1, 241.245, 0, 1, 0.544682,-99) , 
NN(
NN(
0, 
0, 
-1, 0, 1, 1, 0.508306,-99) , 
NN(
0, 
0, 
-1, 0, 1, -1, 0.45362,-99) , 
11, 2.33419, 0, 0, 0.478395,-99) , 
7, 1.5486, 0, 0, 0.490084,-99) , 
NN(
0, 
0, 
-1, 0, 1, -1, 0.348578,-99) , 
1, 3.66727, 1, 0, 0.484786,-99)    );
  // itree = 69
  fBoostWeights.push_back(0.0279897);
  fForest.push_back( 
NN(
NN(
NN(
NN(
0, 
0, 
-1, 0, 1, 1, 0.603893,-99) , 
NN(
0, 
0, 
-1, 0, 1, -1, 0.49564,-99) , 
14, 32.218, 1, 0, 0.502414,-99) , 
NN(
NN(
0, 
0, 
-1, 0, 1, 1, 0.508781,-99) , 
NN(
0, 
0, 
-1, 0, 1, -1, 0.30647,-99) , 
12, 333.322, 1, 0, 0.448522,-99) , 
11, 0.95486, 0, 0, 0.496484,-99) , 
NN(
0, 
0, 
-1, 1.69431, 0, -1, 0.385999,-99) , 
9, 3.55782, 1, 0, 0.490328,-99)    );
  // itree = 70
  fBoostWeights.push_back(0.0470555);
  fForest.push_back( 
NN(
NN(
NN(
0, 
0, 
-1, 0, 1, 1, 0.605372,-99) , 
NN(
NN(
0, 
0, 
-1, 0, 1, 1, 0.552206,-99) , 
NN(
0, 
0, 
-1, 0, 1, -1, 0.47754,-99) , 
5, 2.82319, 0, 0, 0.485592,-99) , 
7, 0.324976, 1, 0, 0.489533,-99) , 
NN(
NN(
0, 
0, 
-1, 0, 1, 1, 0.53,-99) , 
NN(
0, 
0, 
-1, 0, 1, -1, 0.29315,-99) , 
8, 18.6095, 0, 0, 0.420942,-99) , 
14, 38.4297, 0, 0, 0.480645,-99)    );
  // itree = 71
  fBoostWeights.push_back(0.027742);
  fForest.push_back( 
NN(
NN(
NN(
NN(
0, 
0, 
-1, 0, 1, 1, 0.525293,-99) , 
NN(
0, 
0, 
-1, 0, 1, -1, 0.45591,-99) , 
10, 1.09627, 0, 0, 0.51459,-99) , 
NN(
0, 
0, 
-1, 3.21569, 0, -1, 0.455373,-99) , 
11, 2.74605, 1, 0, 0.49601,-99) , 
NN(
0, 
0, 
-1, 0, 1, -1, 0.349742,-99) , 
11, 0.553762, 0, 0, 0.491167,-99)    );
  // itree = 72
  fBoostWeights.push_back(0.0173733);
  fForest.push_back( 
NN(
NN(
NN(
NN(
0, 
0, 
-1, 0, 1, 1, 0.636864,-99) , 
NN(
0, 
0, 
-1, 0, 1, -1, 0.463081,-99) , 
4, 279.556, 1, 0, 0.555514,-99) , 
NN(
0, 
0, 
-1, 0.358901, 0, -1, 0.482665,-99) , 
1, 1.04297, 1, 0, 0.492863,-99) , 
NN(
0, 
0, 
-1, 0, 1, -1, 0.340916,-99) , 
1, 3.79065, 1, 0, 0.488219,-99)    );
  // itree = 73
  fBoostWeights.push_back(0.0277148);
  fForest.push_back( 
NN(
NN(
NN(
0, 
0, 
-1, 0.961606, 1, 1, 0.57312,-99) , 
NN(
0, 
0, 
-1, 0, 1, -1, 0.363566,-99) , 
1, 3.79976, 1, 0, 0.547759,-99) , 
NN(
NN(
NN(
0, 
0, 
-1, 0, 1, 1, 0.511399,-99) , 
NN(
0, 
0, 
-1, 0, 1, -1, 0.429671,-99) , 
10, 0.943039, 0, 0, 0.505806,-99) , 
NN(
0, 
0, 
-1, 155.186, 1, -1, 0.458298,-99) , 
8, 42.9512, 0, 0, 0.486628,-99) , 
1, 3.02305, 0, 0, 0.500064,-99)    );
  // itree = 74
  fBoostWeights.push_back(0.00499265);
  fForest.push_back( 
NN(
NN(
0, 
0, 
-1, 0, 1, 1, 0.629822,-99) , 
NN(
NN(
0, 
0, 
-1, 0, 1, 1, 0.647502,-99) , 
NN(
0, 
0, 
-1, 3.79408, 1, -1, 0.486019,-99) , 
10, 3.84224, 0, 0, 0.490431,-99) , 
1, 0.70472, 1, 0, 0.500508,-99)    );
  // itree = 75
  fBoostWeights.push_back(0.0234913);
  fForest.push_back( 
NN(
NN(
NN(
0, 
0, 
-1, 121.292, 0, 1, 0.523885,-99) , 
NN(
NN(
0, 
0, 
-1, 0, 1, 1, 0.524596,-99) , 
NN(
0, 
0, 
-1, 0, 1, -1, 0.355887,-99) , 
14, 82.0164, 0, 0, 0.456341,-99) , 
0, 165.46, 1, 0, 0.515903,-99) , 
NN(
0, 
0, 
-1, 0, 1, -1, 0.425346,-99) , 
0, 40.3158, 0, 0, 0.509791,-99)    );
  // itree = 76
  fBoostWeights.push_back(0.0199886);
  fForest.push_back( 
NN(
NN(
NN(
0, 
0, 
-1, 0.535228, 1, 1, 0.520215,-99) , 
NN(
0, 
0, 
-1, 99.5917, 1, -1, 0.41216,-99) , 
9, 3.46578, 1, 0, 0.512828,-99) , 
NN(
0, 
0, 
-1, 2.93529, 1, -1, 0.390717,-99) , 
9, 0.881499, 0, 0, 0.504912,-99)    );
  // itree = 77
  fBoostWeights.push_back(0.0137724);
  fForest.push_back( 
NN(
NN(
NN(
0, 
0, 
-1, 0, 1, 1, 0.623919,-99) , 
NN(
NN(
0, 
0, 
-1, 0, 1, 1, 0.507543,-99) , 
NN(
0, 
0, 
-1, 0, 1, -1, 0.46678,-99) , 
11, 2.50381, 1, 0, 0.491982,-99) , 
11, 3.8411, 0, 0, 0.495497,-99) , 
NN(
0, 
0, 
-1, 0, 1, -1, 0.409232,-99) , 
7, 0.25148, 0, 0, 0.489717,-99)    );
  // itree = 78
  fBoostWeights.push_back(0.0135517);
  fForest.push_back( 
NN(
NN(
NN(
NN(
0, 
0, 
-1, 0, 1, 1, 0.513217,-99) , 
NN(
0, 
0, 
-1, 0, 1, -1, 0.41615,-99) , 
1, 3.19535, 1, 0, 0.506534,-99) , 
NN(
NN(
0, 
0, 
-1, 0, 1, 1, 0.530291,-99) , 
NN(
0, 
0, 
-1, 0, 1, -1, 0.414197,-99) , 
9, 2.96803, 0, 0, 0.446167,-99) , 
11, 3.10438, 1, 0, 0.499213,-99) , 
NN(
0, 
0, 
-1, 0, 1, -1, 0.348006,-99) , 
1, 3.70225, 1, 0, 0.493063,-99)    );
  // itree = 79
  fBoostWeights.push_back(0.0270623);
  fForest.push_back( 
NN(
NN(
0, 
0, 
-1, 2.38783, 0, 1, 0.547989,-99) , 
NN(
NN(
0, 
0, 
-1, 203.29, 0, -1, 0.481083,-99) , 
NN(
NN(
0, 
0, 
-1, 0, 1, 1, 0.511342,-99) , 
NN(
0, 
0, 
-1, 0, 1, -1, 0.34911,-99) , 
6, 726.571, 0, 0, 0.412675,-99) , 
7, 0.377126, 0, 0, 0.474868,-99) , 
4, 123.125, 1, 0, 0.480811,-99)    );
  // itree = 80
  fBoostWeights.push_back(0.0339543);
  fForest.push_back( 
NN(
NN(
NN(
0, 
0, 
-1, 1.80518, 0, 1, 0.538796,-99) , 
NN(
NN(
0, 
0, 
-1, 0, 1, 1, 0.526526,-99) , 
NN(
0, 
0, 
-1, 0, 1, -1, 0.441084,-99) , 
9, 3.06398, 0, 0, 0.48173,-99) , 
9, 2.55535, 1, 0, 0.507989,-99) , 
NN(
NN(
NN(
0, 
0, 
-1, 0, 1, 1, 0.524949,-99) , 
NN(
0, 
0, 
-1, 0, 1, -1, 0.452671,-99) , 
7, 0.536249, 1, 0, 0.475678,-99) , 
NN(
0, 
0, 
-1, 0, 1, -1, 0.345501,-99) , 
13, 3.23529, 0, 0, 0.464955,-99) , 
8, 46.2446, 0, 0, 0.489865,-99)    );
  // itree = 81
  fBoostWeights.push_back(0.0147109);
  fForest.push_back( 
NN(
NN(
NN(
NN(
0, 
0, 
-1, 0, 1, 1, 0.552805,-99) , 
NN(
0, 
0, 
-1, 0, 1, -1, 0.398724,-99) , 
9, 1.17668, 0, 0, 0.53298,-99) , 
NN(
0, 
0, 
-1, 1.84666, 0, -1, 0.47183,-99) , 
5, 2.34407, 0, 0, 0.496378,-99) , 
NN(
0, 
0, 
-1, 0, 1, -1, 0.333861,-99) , 
11, 0.648799, 0, 0, 0.488595,-99)    );
  // itree = 82
  fBoostWeights.push_back(0.0295017);
  fForest.push_back( 
NN(
NN(
NN(
NN(
0, 
0, 
-1, 0, 1, 1, 0.606996,-99) , 
NN(
0, 
0, 
-1, 0, 1, -1, 0.434526,-99) , 
9, 2.10534, 0, 0, 0.558626,-99) , 
NN(
NN(
0, 
0, 
-1, 0, 1, 1, 0.545816,-99) , 
NN(
0, 
0, 
-1, 0, 1, -1, 0.491935,-99) , 
0, 136.653, 0, 0, 0.500004,-99) , 
7, 0.56769, 1, 0, 0.509946,-99) , 
NN(
NN(
0, 
0, 
-1, 0, 1, 1, 0.533931,-99) , 
NN(
0, 
0, 
-1, 0, 1, -1, 0.346668,-99) , 
12, 282.55, 0, 0, 0.427247,-99) , 
0, 197.13, 1, 0, 0.504626,-99)    );
  // itree = 83
  fBoostWeights.push_back(0.0263599);
  fForest.push_back( 
NN(
NN(
NN(
NN(
0, 
0, 
-1, 0, 1, 1, 0.532478,-99) , 
NN(
0, 
0, 
-1, 0, 1, -1, 0.481107,-99) , 
3, 220.325, 1, 0, 0.507841,-99) , 
NN(
NN(
0, 
0, 
-1, 0, 1, 1, 0.558517,-99) , 
NN(
0, 
0, 
-1, 0, 1, -1, 0.384827,-99) , 
11, 2.73625, 0, 0, 0.443457,-99) , 
6, 353.306, 0, 0, 0.500059,-99) , 
NN(
0, 
0, 
-1, 0, 1, -1, 0.361317,-99) , 
7, 0.251154, 0, 0, 0.492736,-99)    );
  // itree = 84
  fBoostWeights.push_back(0.0181937);
  fForest.push_back( 
NN(
NN(
NN(
0, 
0, 
-1, 3.39632, 0, 1, 0.521802,-99) , 
NN(
0, 
0, 
-1, 86.2023, 1, -1, 0.478624,-99) , 
3, 227.492, 0, 0, 0.497954,-99) , 
NN(
0, 
0, 
-1, 0, 1, -1, 0.411103,-99) , 
14, 33.1035, 0, 0, 0.490057,-99)    );
  // itree = 85
  fBoostWeights.push_back(0.0357704);
  fForest.push_back( 
NN(
NN(
NN(
NN(
0, 
0, 
-1, 0, 1, 1, 0.536644,-99) , 
NN(
0, 
0, 
-1, 0, 1, -1, 0.440092,-99) , 
11, 1.06815, 0, 0, 0.528909,-99) , 
NN(
0, 
0, 
-1, 0, 1, -1, 0.38929,-99) , 
9, 0.69428, 0, 0, 0.517248,-99) , 
NN(
NN(
NN(
0, 
0, 
-1, 0, 1, 1, 0.534107,-99) , 
NN(
0, 
0, 
-1, 0, 1, -1, 0.462705,-99) , 
11, 2.0932, 0, 0, 0.495571,-99) , 
NN(
0, 
0, 
-1, 504.199, 1, -1, 0.431311,-99) , 
7, 1.16907, 1, 0, 0.473002,-99) , 
9, 2.52185, 1, 0, 0.494769,-99)    );
  // itree = 86
  fBoostWeights.push_back(0.00733748);
  fForest.push_back( 
NN(
NN(
0, 
0, 
-1, 0, 1, 1, 0.650825,-99) , 
NN(
NN(
0, 
0, 
-1, 0, 1, 1, 0.610828,-99) , 
NN(
NN(
0, 
0, 
-1, 0, 1, 1, 0.508753,-99) , 
NN(
0, 
0, 
-1, 0, 1, -1, 0.391572,-99) , 
1, 3.65522, 1, 0, 0.504552,-99) , 
12, 605.284, 0, 0, 0.510041,-99) , 
10, 0.533262, 1, 0, 0.516097,-99)    );
  // itree = 87
  fBoostWeights.push_back(0.0243177);
  fForest.push_back( 
NN(
NN(
NN(
0, 
0, 
-1, 0, 1, 1, 0.614157,-99) , 
NN(
NN(
0, 
0, 
-1, 0, 1, 1, 0.532758,-99) , 
NN(
0, 
0, 
-1, 0, 1, -1, 0.477304,-99) , 
5, 2.11203, 0, 0, 0.513683,-99) , 
7, 0.334912, 1, 0, 0.524299,-99) , 
NN(
NN(
NN(
0, 
0, 
-1, 0, 1, 1, 0.516774,-99) , 
NN(
0, 
0, 
-1, 0, 1, -1, 0.422039,-99) , 
9, 1.98047, 1, 0, 0.499195,-99) , 
NN(
0, 
0, 
-1, 0, 1, -1, 0.366128,-99) , 
14, 44.9274, 0, 0, 0.480514,-99) , 
9, 2.24395, 0, 0, 0.508337,-99)    );
  // itree = 88
  fBoostWeights.push_back(0.0196395);
  fForest.push_back( 
NN(
NN(
NN(
NN(
0, 
0, 
-1, 0, 1, 1, 0.525509,-99) , 
NN(
0, 
0, 
-1, 0, 1, -1, 0.387684,-99) , 
10, 3.18916, 1, 0, 0.51495,-99) , 
NN(
NN(
0, 
0, 
-1, 0, 1, 1, 0.560328,-99) , 
NN(
0, 
0, 
-1, 0, 1, -1, 0.46514,-99) , 
10, 3.17734, 0, 0, 0.478611,-99) , 
5, 2.11761, 1, 0, 0.492462,-99) , 
NN(
0, 
0, 
-1, 0, 1, -1, 0.37115,-99) , 
11, 0.553762, 0, 0, 0.487733,-99)    );
  // itree = 89
  fBoostWeights.push_back(0.0144936);
  fForest.push_back( 
NN(
NN(
NN(
NN(
0, 
0, 
-1, 0, 1, 1, 0.546706,-99) , 
NN(
0, 
0, 
-1, 0, 1, -1, 0.495554,-99) , 
10, 2.41687, 0, 0, 0.516354,-99) , 
NN(
0, 
0, 
-1, 3.39038, 1, -1, 0.452056,-99) , 
0, 136.087, 1, 0, 0.503555,-99) , 
NN(
0, 
0, 
-1, 59.7871, 1, -1, 0.409634,-99) , 
9, 1.10388, 0, 0, 0.494527,-99)    );
  // itree = 90
  fBoostWeights.push_back(0.0154279);
  fForest.push_back( 
NN(
NN(
NN(
0, 
0, 
-1, 0, 1, 1, 0.605316,-99) , 
NN(
NN(
0, 
0, 
-1, 0, 1, 1, 0.506788,-99) , 
NN(
0, 
0, 
-1, 0, 1, -1, 0.403756,-99) , 
1, 3.65038, 1, 0, 0.503044,-99) , 
8, 190.571, 0, 0, 0.506774,-99) , 
NN(
0, 
0, 
-1, 0, 1, -1, 0.416388,-99) , 
7, 0.251154, 0, 0, 0.500312,-99)    );
  // itree = 91
  fBoostWeights.push_back(0.026138);
  fForest.push_back( 
NN(
NN(
NN(
0, 
0, 
-1, 0, 1, 1, 0.661999,-99) , 
NN(
NN(
0, 
0, 
-1, 0, 1, 1, 0.591691,-99) , 
NN(
0, 
0, 
-1, 0, 1, -1, 0.492415,-99) , 
11, 0.713416, 1, 0, 0.497151,-99) , 
7, 0.292986, 1, 0, 0.508743,-99) , 
NN(
NN(
NN(
0, 
0, 
-1, 0, 1, 1, 0.524268,-99) , 
NN(
0, 
0, 
-1, 0, 1, -1, 0.410351,-99) , 
8, 64.5795, 0, 0, 0.469548,-99) , 
NN(
0, 
0, 
-1, 0, 1, -1, 0.265616,-99) , 
11, 0.963733, 0, 0, 0.43648,-99) , 
10, 2.99009, 1, 0, 0.495365,-99)    );
  // itree = 92
  fBoostWeights.push_back(0.0108664);
  fForest.push_back( 
NN(
NN(
NN(
0, 
0, 
-1, 2.27012, 0, 1, 0.602611,-99) , 
NN(
NN(
0, 
0, 
-1, 0, 1, 1, 0.535558,-99) , 
NN(
0, 
0, 
-1, 0, 1, -1, 0.344178,-99) , 
11, 0.99869, 0, 0, 0.507461,-99) , 
12, 209.723, 1, 0, 0.542937,-99) , 
NN(
NN(
NN(
0, 
0, 
-1, 0, 1, 1, 0.593875,-99) , 
NN(
0, 
0, 
-1, 0, 1, -1, 0.482727,-99) , 
1, 3.40955, 0, 0, 0.487432,-99) , 
NN(
0, 
0, 
-1, 2.60002, 1, -1, 0.421372,-99) , 
6, 354.224, 0, 0, 0.47797,-99) , 
9, 3.01918, 0, 0, 0.496222,-99)    );
  // itree = 93
  fBoostWeights.push_back(0.0180214);
  fForest.push_back( 
NN(
NN(
NN(
0, 
0, 
-1, 0, 1, 1, 0.632789,-99) , 
NN(
NN(
0, 
0, 
-1, 0, 1, 1, 0.547933,-99) , 
NN(
0, 
0, 
-1, 0, 1, -1, 0.498049,-99) , 
5, 2.26981, 0, 0, 0.520413,-99) , 
10, 2.42132, 0, 0, 0.528655,-99) , 
NN(
NN(
NN(
0, 
0, 
-1, 0, 1, 1, 0.610184,-99) , 
NN(
0, 
0, 
-1, 0, 1, -1, 0.487286,-99) , 
12, 558.438, 0, 0, 0.497939,-99) , 
NN(
0, 
0, 
-1, 0, 1, -1, 0.335363,-99) , 
6, 347.142, 0, 0, 0.478251,-99) , 
10, 2.52011, 1, 0, 0.509362,-99)    );
  // itree = 94
  fBoostWeights.push_back(0.0136317);
  fForest.push_back( 
NN(
NN(
NN(
0, 
0, 
-1, 108.85, 0, 1, 0.533443,-99) , 
NN(
0, 
0, 
-1, 99.4211, 1, -1, 0.467914,-99) , 
1, 1.96715, 0, 0, 0.510507,-99) , 
NN(
0, 
0, 
-1, 0, 1, -1, 0.309319,-99) , 
11, 0.554185, 0, 0, 0.500921,-99)    );
  // itree = 95
  fBoostWeights.push_back(0.0199722);
  fForest.push_back( 
NN(
NN(
NN(
NN(
0, 
0, 
-1, 0, 1, 1, 0.64261,-99) , 
NN(
0, 
0, 
-1, 0, 1, -1, 0.461069,-99) , 
6, 519.109, 1, 0, 0.582111,-99) , 
NN(
NN(
0, 
0, 
-1, 0, 1, 1, 0.572456,-99) , 
NN(
0, 
0, 
-1, 0, 1, -1, 0.397355,-99) , 
14, 99.8059, 0, 0, 0.495711,-99) , 
3, 159.7, 0, 0, 0.55009,-99) , 
NN(
NN(
NN(
0, 
0, 
-1, 0, 1, 1, 0.619121,-99) , 
NN(
0, 
0, 
-1, 0, 1, -1, 0.488381,-99) , 
7, 0.633836, 1, 0, 0.527208,-99) , 
NN(
0, 
0, 
-1, 2.74501, 1, -1, 0.468004,-99) , 
5, 2.06527, 1, 0, 0.485997,-99) , 
7, 1.53822, 0, 0, 0.498461,-99)    );
  // itree = 96
  fBoostWeights.push_back(0.0121926);
  fForest.push_back( 
NN(
NN(
NN(
0, 
0, 
-1, 0, 1, 1, 0.677448,-99) , 
NN(
0, 
0, 
-1, 0, 1, -1, 0.490134,-99) , 
7, 0.560104, 1, 0, 0.598544,-99) , 
NN(
NN(
0, 
0, 
-1, 0, 1, 1, 0.591834,-99) , 
NN(
NN(
0, 
0, 
-1, 0, 1, 1, 0.558528,-99) , 
NN(
0, 
0, 
-1, 0, 1, -1, 0.485272,-99) , 
13, 7.11765, 0, 0, 0.490255,-99) , 
12, 619.753, 0, 0, 0.494799,-99) , 
1, 0.824646, 1, 0, 0.504437,-99)    );
  // itree = 97
  fBoostWeights.push_back(0.0382096);
  fForest.push_back( 
NN(
NN(
NN(
0, 
0, 
-1, 4.17647, 1, 1, 0.532896,-99) , 
NN(
NN(
0, 
0, 
-1, 0, 1, 1, 0.516007,-99) , 
NN(
0, 
0, 
-1, 0, 1, -1, 0.428413,-99) , 
6, 527.16, 1, 0, 0.485754,-99) , 
4, 197.017, 0, 0, 0.514274,-99) , 
NN(
0, 
0, 
-1, 0, 1, -1, 0.393373,-99) , 
7, 0.319293, 0, 0, 0.502941,-99)    );
  // itree = 98
  fBoostWeights.push_back(0.0424415);
  fForest.push_back( 
NN(
NN(
NN(
NN(
0, 
0, 
-1, 0, 1, 1, 0.556471,-99) , 
NN(
0, 
0, 
-1, 0, 1, -1, 0.485645,-99) , 
10, 3.08709, 1, 0, 0.545379,-99) , 
NN(
NN(
0, 
0, 
-1, 0, 1, 1, 0.520068,-99) , 
NN(
0, 
0, 
-1, 0, 1, -1, 0.420669,-99) , 
14, 93.6405, 1, 0, 0.502524,-99) , 
1, 2.25227, 0, 0, 0.525555,-99) , 
NN(
NN(
NN(
0, 
0, 
-1, 0, 1, 1, 0.56328,-99) , 
NN(
0, 
0, 
-1, 0, 1, -1, 0.367799,-99) , 
3, 237.527, 1, 0, 0.474342,-99) , 
NN(
0, 
0, 
-1, 0, 1, -1, 0.154521,-99) , 
10, 1.06585, 0, 0, 0.376098,-99) , 
9, 3.442, 1, 0, 0.511888,-99)    );
  // itree = 99
  fBoostWeights.push_back(0);
  fForest.push_back( 
NN(
NN(
NN(
NN(
0, 
0, 
-1, 0, 1, 1, 0.546046,-99) , 
NN(
0, 
0, 
-1, 0, 1, -1, 0.497652,-99) , 
1, 2.77274, 0, 0, 0.512694,-99) , 
NN(
NN(
0, 
0, 
-1, 0, 1, 1, 0.505077,-99) , 
NN(
0, 
0, 
-1, 0, 1, -1, 0.414597,-99) , 
1, 2.63364, 1, 0, 0.456454,-99) , 
11, 3.10417, 1, 0, 0.504831,-99) , 
NN(
0, 
0, 
-1, 0, 1, -1, 0.370275,-99) , 
1, 0.56445, 0, 0, 0.500122,-99)    );
  // itree = 100
  fBoostWeights.push_back(0.0301928);
  fForest.push_back( 
NN(
NN(
NN(
NN(
0, 
0, 
-1, 0, 1, 1, 0.522533,-99) , 
NN(
0, 
0, 
-1, 0, 1, -1, 0.357106,-99) , 
7, 1.63223, 1, 0, 0.514708,-99) , 
NN(
0, 
0, 
-1, 1.97927, 0, -1, 0.463917,-99) , 
14, 84.1204, 1, 0, 0.493517,-99) , 
NN(
0, 
0, 
-1, 0, 1, -1, 0.391686,-99) , 
7, 0.251643, 0, 0, 0.487488,-99)    );
  // itree = 101
  fBoostWeights.push_back(0.0112219);
  fForest.push_back( 
NN(
NN(
NN(
0, 
0, 
-1, 0, 1, 1, 0.581758,-99) , 
NN(
NN(
0, 
0, 
-1, 0, 1, 1, 0.550512,-99) , 
NN(
0, 
0, 
-1, 0, 1, -1, 0.491765,-99) , 
1, 3.06783, 0, 0, 0.502349,-99) , 
7, 0.287146, 1, 0, 0.507782,-99) , 
NN(
0, 
0, 
-1, 0, 1, -1, 0.392458,-99) , 
7, 2.0868, 1, 0, 0.503889,-99)    );
  // itree = 102
  fBoostWeights.push_back(0.0123446);
  fForest.push_back( 
NN(
NN(
NN(
0, 
0, 
-1, 0, 1, 1, 0.570639,-99) , 
NN(
NN(
0, 
0, 
-1, 0, 1, 1, 0.513246,-99) , 
NN(
0, 
0, 
-1, 0, 1, -1, 0.470512,-99) , 
3, 160.5, 0, 0, 0.500179,-99) , 
14, 32.9152, 1, 0, 0.50588,-99) , 
NN(
0, 
0, 
-1, 0, 1, -1, 0.373915,-99) , 
10, 3.72546, 1, 0, 0.501467,-99)    );
  // itree = 103
  fBoostWeights.push_back(0.0105699);
  fForest.push_back( 
NN(
NN(
0, 
0, 
-1, 2.22249, 1, 1, 0.575504,-99) , 
NN(
NN(
0, 
0, 
-1, 0, 1, 1, 0.605936,-99) , 
NN(
NN(
0, 
0, 
-1, 0, 1, 1, 0.510231,-99) , 
NN(
0, 
0, 
-1, 0, 1, -1, 0.46593,-99) , 
10, 2.56524, 1, 0, 0.495194,-99) , 
12, 597.229, 0, 0, 0.500865,-99) , 
7, 0.405659, 1, 0, 0.50765,-99)    );
  // itree = 104
  fBoostWeights.push_back(0.0350026);
  fForest.push_back( 
NN(
NN(
NN(
0, 
0, 
-1, 50.8837, 1, 1, 0.526148,-99) , 
NN(
NN(
0, 
0, 
-1, 0, 1, 1, 0.571033,-99) , 
NN(
0, 
0, 
-1, 0, 1, -1, 0.450514,-99) , 
4, 256.154, 0, 0, 0.469812,-99) , 
10, 1.9955, 1, 0, 0.494341,-99) , 
NN(
NN(
NN(
0, 
0, 
-1, 0, 1, 1, 0.52118,-99) , 
NN(
0, 
0, 
-1, 0, 1, -1, 0.4295,-99) , 
4, 471.827, 0, 0, 0.4687,-99) , 
NN(
0, 
0, 
-1, 0, 1, -1, 0.288377,-99) , 
7, 0.411198, 0, 0, 0.448299,-99) , 
4, 303.505, 1, 0, 0.479756,-99)    );
  // itree = 105
  fBoostWeights.push_back(0);
  fForest.push_back( 
NN(
NN(
0, 
0, 
-1, 0, 1, 1, 0.65187,-99) , 
NN(
NN(
NN(
0, 
0, 
-1, 0, 1, 1, 0.511667,-99) , 
NN(
0, 
0, 
-1, 0, 1, -1, 0.349513,-99) , 
7, 2.17031, 1, 0, 0.506755,-99) , 
NN(
0, 
0, 
-1, 227.428, 1, -1, 0.363819,-99) , 
10, 0.744747, 0, 0, 0.498414,-99) , 
1, 0.550888, 1, 0, 0.507367,-99)    );
  // itree = 106
  fBoostWeights.push_back(0.027172);
  fForest.push_back( 
NN(
NN(
NN(
0, 
0, 
-1, 0, 1, 1, 0.641122,-99) , 
NN(
NN(
0, 
0, 
-1, 0, 1, 1, 0.529792,-99) , 
NN(
0, 
0, 
-1, 0, 1, -1, 0.404145,-99) , 
13, 3.21569, 0, 0, 0.516197,-99) , 
14, 129.07, 0, 0, 0.529821,-99) , 
NN(
NN(
NN(
0, 
0, 
-1, 0, 1, 1, 0.568284,-99) , 
NN(
0, 
0, 
-1, 0, 1, -1, 0.464455,-99) , 
6, 539.193, 1, 0, 0.530843,-99) , 
NN(
0, 
0, 
-1, 3.43997, 1, -1, 0.464074,-99) , 
9, 2.03772, 1, 0, 0.482047,-99) , 
10, 2.76799, 0, 0, 0.49605,-99)    );
  // itree = 107
  fBoostWeights.push_back(0.0246365);
  fForest.push_back( 
NN(
NN(
NN(
0, 
0, 
-1, 1.89514, 1, 1, 0.521306,-99) , 
NN(
NN(
0, 
0, 
-1, 0, 1, 1, 0.534406,-99) , 
NN(
0, 
0, 
-1, 0, 1, -1, 0.451879,-99) , 
3, 112.961, 1, 0, 0.476536,-99) , 
3, 168.004, 0, 0, 0.506156,-99) , 
NN(
NN(
0, 
0, 
-1, 0, 1, 1, 0.554398,-99) , 
NN(
0, 
0, 
-1, 0, 1, -1, 0.325304,-99) , 
4, 256.426, 1, 0, 0.434991,-99) , 
11, 0.887876, 0, 0, 0.499757,-99)    );
  // itree = 108
  fBoostWeights.push_back(0.0295107);
  fForest.push_back( 
NN(
NN(
NN(
0, 
0, 
-1, 0, 1, 1, 0.650031,-99) , 
NN(
0, 
0, 
-1, 0, 1, -1, 0.488643,-99) , 
4, 257.885, 1, 0, 0.569668,-99) , 
NN(
NN(
NN(
0, 
0, 
-1, 0, 1, 1, 0.543312,-99) , 
NN(
0, 
0, 
-1, 0, 1, -1, 0.428484,-99) , 
5, 2.79452, 1, 0, 0.517486,-99) , 
NN(
NN(
0, 
0, 
-1, 0, 1, 1, 0.577526,-99) , 
NN(
0, 
0, 
-1, 0, 1, -1, 0.44995,-99) , 
9, 3.60095, 0, 0, 0.456608,-99) , 
0, 122.193, 0, 0, 0.473078,-99) , 
1, 0.985259, 1, 0, 0.485708,-99)    );
  // itree = 109
  fBoostWeights.push_back(0.026797);
  fForest.push_back( 
NN(
NN(
NN(
0, 
0, 
-1, 0, 1, 1, 0.609729,-99) , 
NN(
NN(
0, 
0, 
-1, 0, 1, 1, 0.601566,-99) , 
NN(
0, 
0, 
-1, 0, 1, -1, 0.42687,-99) , 
3, 268.206, 0, 0, 0.515158,-99) , 
14, 74.9685, 1, 0, 0.558912,-99) , 
NN(
NN(
NN(
0, 
0, 
-1, 0, 1, 1, 0.504503,-99) , 
NN(
0, 
0, 
-1, 0, 1, -1, 0.386588,-99) , 
1, 3.28199, 1, 0, 0.498804,-99) , 
NN(
NN(
0, 
0, 
-1, 0, 1, 1, 0.543066,-99) , 
NN(
0, 
0, 
-1, 0, 1, -1, 0.392257,-99) , 
6, 398.731, 1, 0, 0.429516,-99) , 
11, 3.10438, 1, 0, 0.489832,-99) , 
10, 3.2107, 0, 0, 0.497208,-99)    );
  // itree = 110
  fBoostWeights.push_back(0.0174788);
  fForest.push_back( 
NN(
NN(
NN(
0, 
0, 
-1, 0, 1, 1, 0.610521,-99) , 
NN(
NN(
0, 
0, 
-1, 0, 1, 1, 0.543435,-99) , 
NN(
0, 
0, 
-1, 0, 1, -1, 0.470442,-99) , 
1, 2.17522, 1, 0, 0.51393,-99) , 
11, 2.56746, 0, 0, 0.553633,-99) , 
NN(
0, 
0, 
-1, 30.5333, 0, -1, 0.473276,-99) , 
5, 1.72654, 1, 0, 0.484959,-99)    );
  // itree = 111
  fBoostWeights.push_back(0.0130281);
  fForest.push_back( 
NN(
NN(
0, 
0, 
-1, 1.64522, 1, 1, 0.528056,-99) , 
NN(
NN(
NN(
0, 
0, 
-1, 0, 1, 1, 0.508396,-99) , 
NN(
0, 
0, 
-1, 0, 1, -1, 0.448507,-99) , 
6, 572.731, 0, 0, 0.493927,-99) , 
NN(
0, 
0, 
-1, 3.04839, 1, -1, 0.412937,-99) , 
10, 0.919367, 0, 0, 0.48364,-99) , 
6, 492.699, 1, 0, 0.502856,-99)    );
  // itree = 112
  fBoostWeights.push_back(0.0272019);
  fForest.push_back( 
NN(
NN(
NN(
0, 
0, 
-1, 2.5091, 0, 1, 0.538435,-99) , 
NN(
NN(
0, 
0, 
-1, 0, 1, 1, 0.507599,-99) , 
NN(
0, 
0, 
-1, 0, 1, -1, 0.328553,-99) , 
8, 99.7341, 1, 0, 0.478638,-99) , 
1, 2.01646, 0, 0, 0.518776,-99) , 
NN(
NN(
NN(
0, 
0, 
-1, 0, 1, 1, 0.52106,-99) , 
NN(
0, 
0, 
-1, 0, 1, -1, 0.392527,-99) , 
10, 2.93631, 1, 0, 0.499564,-99) , 
NN(
0, 
0, 
-1, 2.80702, 1, -1, 0.381651,-99) , 
5, 2.5313, 1, 0, 0.475115,-99) , 
7, 0.890326, 0, 0, 0.502066,-99)    );
  // itree = 113
  fBoostWeights.push_back(0);
  fForest.push_back( 
NN(
NN(
0, 
0, 
-1, 0, 1, 1, 0.609459,-99) , 
NN(
NN(
NN(
0, 
0, 
-1, 0, 1, 1, 0.510774,-99) , 
NN(
0, 
0, 
-1, 0, 1, -1, 0.466034,-99) , 
7, 1.50307, 1, 0, 0.501438,-99) , 
NN(
NN(
0, 
0, 
-1, 0, 1, 1, 0.534794,-99) , 
NN(
0, 
0, 
-1, 0, 1, -1, 0.325662,-99) , 
1, 2.57313, 1, 0, 0.426721,-99) , 
9, 0.866104, 0, 0, 0.496045,-99) , 
10, 0.551756, 1, 0, 0.501587,-99)    );
  // itree = 114
  fBoostWeights.push_back(0.0138089);
  fForest.push_back( 
NN(
NN(
NN(
0, 
0, 
-1, 0.355629, 1, 1, 0.513485,-99) , 
NN(
0, 
0, 
-1, 0.962724, 0, -1, 0.466338,-99) , 
1, 2.03238, 0, 0, 0.494054,-99) , 
NN(
0, 
0, 
-1, 0, 1, -1, 0.341669,-99) , 
1, 3.69911, 1, 0, 0.486732,-99)    );
  // itree = 115
  fBoostWeights.push_back(0.0265402);
  fForest.push_back( 
NN(
NN(
NN(
0, 
0, 
-1, 5.15686, 0, 1, 0.564645,-99) , 
NN(
NN(
0, 
0, 
-1, 0, 1, 1, 0.514695,-99) , 
NN(
0, 
0, 
-1, 0, 1, -1, 0.457952,-99) , 
6, 464.65, 0, 0, 0.491778,-99) , 
12, 367.101, 0, 0, 0.504388,-99) , 
NN(
NN(
NN(
0, 
0, 
-1, 0, 1, 1, 0.512867,-99) , 
NN(
0, 
0, 
-1, 0, 1, -1, 0.450311,-99) , 
14, 67.1914, 1, 0, 0.477216,-99) , 
NN(
0, 
0, 
-1, 0, 1, -1, 0.335945,-99) , 
13, 3.21569, 0, 0, 0.46459,-99) , 
9, 2.84806, 1, 0, 0.490793,-99)    );
  // itree = 116
  fBoostWeights.push_back(0.0438038);
  fForest.push_back( 
NN(
NN(
NN(
0, 
0, 
-1, 3.19608, 1, 1, 0.543816,-99) , 
NN(
0, 
0, 
-1, 2.03579, 0, -1, 0.477574,-99) , 
3, 222.302, 1, 0, 0.513384,-99) , 
NN(
NN(
0, 
0, 
-1, 0, 1, 1, 0.584932,-99) , 
NN(
NN(
0, 
0, 
-1, 0, 1, 1, 0.550336,-99) , 
NN(
0, 
0, 
-1, 0, 1, -1, 0.438659,-99) , 
2, 225.476, 0, 0, 0.455544,-99) , 
11, 0.866433, 1, 0, 0.46813,-99) , 
12, 226.42, 0, 0, 0.492617,-99)    );
  // itree = 117
  fBoostWeights.push_back(0.0200575);
  fForest.push_back( 
NN(
NN(
NN(
NN(
0, 
0, 
-1, 0, 1, 1, 0.525434,-99) , 
NN(
0, 
0, 
-1, 0, 1, -1, 0.476584,-99) , 
8, 45.2232, 0, 0, 0.504954,-99) , 
NN(
0, 
0, 
-1, 2.59395, 1, -1, 0.430092,-99) , 
9, 3.17977, 1, 0, 0.493705,-99) , 
NN(
0, 
0, 
-1, 2.35474, 1, -1, 0.42779,-99) , 
0, 61.7765, 0, 0, 0.477037,-99)    );
  // itree = 118
  fBoostWeights.push_back(0.0188653);
  fForest.push_back( 
NN(
NN(
NN(
0, 
0, 
-1, 0, 1, 1, 0.569845,-99) , 
NN(
NN(
0, 
0, 
-1, 0, 1, 1, 0.516408,-99) , 
NN(
0, 
0, 
-1, 0, 1, -1, 0.446948,-99) , 
0, 134.003, 1, 0, 0.501476,-99) , 
12, 136.665, 1, 0, 0.51178,-99) , 
NN(
NN(
0, 
0, 
-1, 0, 1, 1, 0.580575,-99) , 
NN(
0, 
0, 
-1, 1.14933, 1, -1, 0.464706,-99) , 
7, 2.17024, 0, 0, 0.472476,-99) , 
11, 1.99916, 1, 0, 0.489141,-99)    );
  // itree = 119
  fBoostWeights.push_back(0.00782507);
  fForest.push_back( 
NN(
NN(
0, 
0, 
-1, 0, 1, 1, 0.56954,-99) , 
NN(
NN(
NN(
0, 
0, 
-1, 0, 1, 1, 0.682487,-99) , 
NN(
0, 
0, 
-1, 0, 1, -1, 0.41436,-99) , 
2, 131.526, 1, 0, 0.565055,-99) , 
NN(
0, 
0, 
-1, 1.73216, 1, -1, 0.478659,-99) , 
14, 133.513, 0, 0, 0.48538,-99) , 
7, 0.324695, 1, 0, 0.492296,-99)    );
  // itree = 120
  fBoostWeights.push_back(0.0158385);
  fForest.push_back( 
NN(
NN(
NN(
0, 
0, 
-1, 2.58561, 0, 1, 0.590454,-99) , 
NN(
NN(
0, 
0, 
-1, 0, 1, 1, 0.578669,-99) , 
NN(
0, 
0, 
-1, 0, 1, -1, 0.485964,-99) , 
7, 0.333373, 1, 0, 0.494582,-99) , 
7, 1.88459, 0, 0, 0.50138,-99) , 
NN(
NN(
0, 
0, 
-1, 0, 1, 1, 0.526685,-99) , 
NN(
0, 
0, 
-1, 1.13678, 1, -1, 0.306758,-99) , 
12, 408.685, 0, 0, 0.380469,-99) , 
9, 3.5103, 1, 0, 0.49199,-99)    );
  // itree = 121
  fBoostWeights.push_back(0.0195444);
  fForest.push_back( 
NN(
NN(
NN(
0, 
0, 
-1, 0.530842, 1, 1, 0.54014,-99) , 
NN(
NN(
0, 
0, 
-1, 0, 1, 1, 0.602884,-99) , 
NN(
0, 
0, 
-1, 0, 1, -1, 0.489388,-99) , 
14, 125.195, 0, 0, 0.498649,-99) , 
11, 2.11034, 0, 0, 0.522427,-99) , 
NN(
NN(
0, 
0, 
-1, 0, 1, 1, 0.500249,-99) , 
NN(
0, 
0, 
-1, 0, 1, -1, 0.281471,-99) , 
1, 3.42535, 1, 0, 0.412857,-99) , 
9, 3.50838, 1, 0, 0.515477,-99)    );
  // itree = 122
  fBoostWeights.push_back(0.0305335);
  fForest.push_back( 
NN(
NN(
NN(
NN(
0, 
0, 
-1, 0, 1, 1, 0.68278,-99) , 
NN(
0, 
0, 
-1, 0, 1, -1, 0.46444,-99) , 
0, 56.636, 0, 0, 0.586087,-99) , 
NN(
NN(
0, 
0, 
-1, 0, 1, 1, 0.529628,-99) , 
NN(
0, 
0, 
-1, 0, 1, -1, 0.466857,-99) , 
10, 2.50296, 1, 0, 0.504628,-99) , 
9, 3.1403, 0, 0, 0.519526,-99) , 
NN(
NN(
NN(
0, 
0, 
-1, 0, 1, 1, 0.590753,-99) , 
NN(
0, 
0, 
-1, 0, 1, -1, 0.475763,-99) , 
5, 2.24471, 1, 0, 0.509456,-99) , 
NN(
0, 
0, 
-1, 2.62596, 1, -1, 0.4404,-99) , 
3, 275.438, 0, 0, 0.46999,-99) , 
0, 76.8706, 1, 0, 0.491191,-99)    );
  // itree = 123
  fBoostWeights.push_back(0.0187003);
  fForest.push_back( 
NN(
NN(
NN(
0, 
0, 
-1, 1.39639, 0, 1, 0.521542,-99) , 
NN(
0, 
0, 
-1, 0, 1, -1, 0.371266,-99) , 
6, 318.618, 0, 0, 0.516601,-99) , 
NN(
NN(
NN(
0, 
0, 
-1, 0, 1, 1, 0.532526,-99) , 
NN(
0, 
0, 
-1, 0, 1, -1, 0.412013,-99) , 
4, 256.807, 1, 0, 0.471684,-99) , 
NN(
0, 
0, 
-1, 0, 1, -1, 0.277248,-99) , 
9, 2.397, 0, 0, 0.397468,-99) , 
13, 3.27451, 0, 0, 0.505854,-99)    );
  // itree = 124
  fBoostWeights.push_back(0.0162893);
  fForest.push_back( 
NN(
NN(
NN(
NN(
0, 
0, 
-1, 0, 1, 1, 0.595778,-99) , 
NN(
0, 
0, 
-1, 0, 1, -1, 0.485831,-99) , 
5, 2.9183, 0, 0, 0.492628,-99) , 
NN(
NN(
0, 
0, 
-1, 0, 1, 1, 0.509189,-99) , 
NN(
0, 
0, 
-1, 0, 1, -1, 0.28274,-99) , 
5, 2.77048, 1, 0, 0.404877,-99) , 
0, 210.004, 1, 0, 0.487351,-99) , 
NN(
0, 
0, 
-1, 0, 1, -1, 0.37104,-99) , 
9, 0.661494, 0, 0, 0.48288,-99)    );
  // itree = 125
  fBoostWeights.push_back(0.030505);
  fForest.push_back( 
NN(
NN(
NN(
NN(
0, 
0, 
-1, 0, 1, 1, 0.600235,-99) , 
NN(
0, 
0, 
-1, 0, 1, -1, 0.496696,-99) , 
6, 721.192, 1, 0, 0.578912,-99) , 
NN(
NN(
0, 
0, 
-1, 0, 1, 1, 0.520966,-99) , 
NN(
0, 
0, 
-1, 0, 1, -1, 0.438768,-99) , 
2, 96.9996, 1, 0, 0.507338,-99) , 
0, 103.723, 0, 0, 0.523276,-99) , 
NN(
NN(
NN(
0, 
0, 
-1, 0, 1, 1, 0.574486,-99) , 
NN(
0, 
0, 
-1, 0, 1, -1, 0.464502,-99) , 
4, 253.823, 0, 0, 0.535961,-99) , 
NN(
0, 
0, 
-1, 3.30127, 1, -1, 0.453032,-99) , 
7, 1.32725, 0, 0, 0.474431,-99) , 
2, 133.487, 1, 0, 0.504181,-99)    );
  // itree = 126
  fBoostWeights.push_back(0.0170958);
  fForest.push_back( 
NN(
NN(
NN(
0, 
0, 
-1, 3.88773, 0, 1, 0.510114,-99) , 
NN(
0, 
0, 
-1, 2.78199, 1, -1, 0.387154,-99) , 
0, 206.854, 1, 0, 0.503279,-99) , 
NN(
0, 
0, 
-1, 0, 1, -1, 0.397096,-99) , 
9, 0.769448, 0, 0, 0.49815,-99)    );
  // itree = 127
  fBoostWeights.push_back(0.0201403);
  fForest.push_back( 
NN(
NN(
NN(
NN(
0, 
0, 
-1, 0, 1, 1, 0.582086,-99) , 
NN(
0, 
0, 
-1, 0, 1, -1, 0.442991,-99) , 
3, 524.361, 1, 0, 0.544323,-99) , 
NN(
0, 
0, 
-1, 2.75919, 1, -1, 0.490007,-99) , 
3, 349.53, 0, 0, 0.500013,-99) , 
NN(
NN(
NN(
0, 
0, 
-1, 0, 1, 1, 0.546265,-99) , 
NN(
0, 
0, 
-1, 0, 1, -1, 0.42685,-99) , 
6, 556.139, 1, 0, 0.489039,-99) , 
NN(
0, 
0, 
-1, 0, 1, -1, 0.264764,-99) , 
3, 306.143, 1, 0, 0.401772,-99) , 
10, 0.876961, 0, 0, 0.490103,-99)    );
  // itree = 128
  fBoostWeights.push_back(0.00788722);
  fForest.push_back( 
NN(
NN(
NN(
0, 
0, 
-1, 32.2122, 1, 1, 0.513254,-99) , 
NN(
0, 
0, 
-1, 1.15892, 0, -1, 0.463783,-99) , 
1, 2.79199, 1, 0, 0.498792,-99) , 
NN(
0, 
0, 
-1, 0, 1, -1, 0.355754,-99) , 
1, 3.84205, 1, 0, 0.494715,-99)    );
  // itree = 129
  fBoostWeights.push_back(0.0134884);
  fForest.push_back( 
NN(
NN(
NN(
0, 
0, 
-1, 0, 1, 1, 0.625767,-99) , 
NN(
NN(
0, 
0, 
-1, 0, 1, 1, 0.54461,-99) , 
NN(
0, 
0, 
-1, 0, 1, -1, 0.481692,-99) , 
6, 549.748, 1, 0, 0.519474,-99) , 
9, 1.82239, 0, 0, 0.536229,-99) , 
NN(
NN(
0, 
0, 
-1, 0, 1, 1, 0.572234,-99) , 
NN(
0, 
0, 
-1, 2.72939, 1, -1, 0.486687,-99) , 
5, 2.98109, 0, 0, 0.492035,-99) , 
9, 1.97693, 1, 0, 0.505625,-99)    );
  // itree = 130
  fBoostWeights.push_back(0.0293754);
  fForest.push_back( 
NN(
NN(
NN(
0, 
0, 
-1, 2.93808, 0, 1, 0.581033,-99) , 
NN(
NN(
0, 
0, 
-1, 0, 1, 1, 0.542449,-99) , 
NN(
0, 
0, 
-1, 0, 1, -1, 0.448388,-99) , 
1, 2.16563, 0, 0, 0.502923,-99) , 
3, 193.923, 0, 0, 0.535122,-99) , 
NN(
NN(
0, 
0, 
-1, 0, 1, 1, 0.59033,-99) , 
NN(
0, 
0, 
-1, 0.360445, 0, -1, 0.47853,-99) , 
5, 3.05485, 0, 0, 0.48962,-99) , 
5, 2.23699, 1, 0, 0.513896,-99)    );
  // itree = 131
  fBoostWeights.push_back(0.0240848);
  fForest.push_back( 
NN(
NN(
NN(
NN(
0, 
0, 
-1, 0, 1, 1, 0.672184,-99) , 
NN(
0, 
0, 
-1, 0, 1, -1, 0.477168,-99) , 
0, 73.0216, 0, 0, 0.594125,-99) , 
NN(
NN(
0, 
0, 
-1, 0, 1, 1, 0.641307,-99) , 
NN(
0, 
0, 
-1, 0, 1, -1, 0.480785,-99) , 
13, 3.23529, 1, 0, 0.499951,-99) , 
14, 44.0936, 1, 0, 0.520755,-99) , 
NN(
NN(
NN(
0, 
0, 
-1, 0, 1, 1, 0.575672,-99) , 
NN(
0, 
0, 
-1, 0, 1, -1, 0.455492,-99) , 
11, 3.55087, 0, 0, 0.466299,-99) , 
NN(
0, 
0, 
-1, 0, 1, -1, 0.263501,-99) , 
7, 0.33509, 0, 0, 0.443381,-99) , 
1, 2.67468, 1, 0, 0.493485,-99)    );
  // itree = 132
  fBoostWeights.push_back(0.0369287);
  fForest.push_back( 
NN(
NN(
NN(
NN(
0, 
0, 
-1, 0, 1, 1, 0.58644,-99) , 
NN(
0, 
0, 
-1, 0, 1, -1, 0.43424,-99) , 
12, 366.377, 1, 0, 0.556835,-99) , 
NN(
NN(
0, 
0, 
-1, 0, 1, 1, 0.50416,-99) , 
NN(
0, 
0, 
-1, 0, 1, -1, 0.459434,-99) , 
3, 155.776, 0, 0, 0.490938,-99) , 
1, 3.02305, 0, 0, 0.505054,-99) , 
NN(
0, 
0, 
-1, 0, 1, -1, 0.425087,-99) , 
14, 32.9152, 0, 0, 0.497416,-99)    );
  // itree = 133
  fBoostWeights.push_back(0.0176305);
  fForest.push_back( 
NN(
NN(
NN(
NN(
0, 
0, 
-1, 0, 1, 1, 0.562903,-99) , 
NN(
0, 
0, 
-1, 0, 1, -1, 0.411968,-99) , 
5, 2.77061, 1, 0, 0.542227,-99) , 
NN(
NN(
0, 
0, 
-1, 0, 1, 1, 0.519937,-99) , 
NN(
0, 
0, 
-1, 0, 1, -1, 0.48334,-99) , 
9, 1.994, 1, 0, 0.499416,-99) , 
9, 2.98961, 0, 0, 0.511465,-99) , 
NN(
0, 
0, 
-1, 0, 1, -1, 0.363867,-99) , 
11, 0.555854, 0, 0, 0.505648,-99)    );
  // itree = 134
  fBoostWeights.push_back(0.00578617);
  fForest.push_back( 
NN(
NN(
NN(
0, 
0, 
-1, 0, 1, 1, 0.680937,-99) , 
NN(
NN(
0, 
0, 
-1, 0, 1, 1, 0.520802,-99) , 
NN(
0, 
0, 
-1, 0, 1, -1, 0.480286,-99) , 
10, 2.5187, 1, 0, 0.506207,-99) , 
1, 3.7953, 0, 0, 0.511101,-99) , 
NN(
0, 
0, 
-1, 0, 1, -1, 0.393707,-99) , 
7, 0.323909, 0, 0, 0.502001,-99)    );
  // itree = 135
  fBoostWeights.push_back(0.00887431);
  fForest.push_back( 
NN(
NN(
NN(
0, 
0, 
-1, 1.7409, 1, 1, 0.564034,-99) , 
NN(
NN(
0, 
0, 
-1, 0, 1, 1, 0.559843,-99) , 
NN(
0, 
0, 
-1, 0, 1, -1, 0.492772,-99) , 
7, 0.548812, 1, 0, 0.502358,-99) , 
9, 3.11958, 0, 0, 0.514034,-99) , 
NN(
NN(
NN(
0, 
0, 
-1, 0, 1, 1, 0.600537,-99) , 
NN(
0, 
0, 
-1, 0, 1, -1, 0.451179,-99) , 
2, 240.862, 0, 0, 0.525958,-99) , 
NN(
0, 
0, 
-1, 0, 1, -1, 0.37284,-99) , 
4, 492.058, 1, 0, 0.45419,-99) , 
3, 433.89, 1, 0, 0.50805,-99)    );
  // itree = 136
  fBoostWeights.push_back(0.0133769);
  fForest.push_back( 
NN(
NN(
NN(
0, 
0, 
-1, 2.09443, 1, 1, 0.559564,-99) , 
NN(
NN(
0, 
0, 
-1, 0, 1, 1, 0.510248,-99) , 
NN(
0, 
0, 
-1, 0, 1, -1, 0.47214,-99) , 
6, 427.952, 0, 0, 0.500983,-99) , 
1, 0.933796, 1, 0, 0.507549,-99) , 
NN(
NN(
NN(
0, 
0, 
-1, 0, 1, 1, 0.597273,-99) , 
NN(
0, 
0, 
-1, 0, 1, -1, 0.42903,-99) , 
7, 1.25919, 1, 0, 0.524222,-99) , 
NN(
0, 
0, 
-1, 0, 1, -1, 0.250332,-99) , 
11, 2.78988, 1, 0, 0.452637,-99) , 
13, 3.23529, 0, 0, 0.501839,-99)    );
  // itree = 137
  fBoostWeights.push_back(0.00633344);
  fForest.push_back( 
NN(
NN(
NN(
0, 
0, 
-1, 0, 1, 1, 0.644371,-99) , 
NN(
NN(
0, 
0, 
-1, 0, 1, 1, 0.566588,-99) , 
NN(
0, 
0, 
-1, 0, 1, -1, 0.48941,-99) , 
1, 2.78192, 0, 0, 0.531703,-99) , 
10, 3.3429, 1, 0, 0.569994,-99) , 
NN(
NN(
NN(
0, 
0, 
-1, 0, 1, 1, 0.595225,-99) , 
NN(
0, 
0, 
-1, 0, 1, -1, 0.492645,-99) , 
10, 0.630223, 1, 0, 0.499447,-99) , 
NN(
0, 
0, 
-1, 0, 1, -1, 0.361693,-99) , 
9, 3.77396, 1, 0, 0.495482,-99) , 
10, 3.2107, 0, 0, 0.503511,-99)    );
  // itree = 138
  fBoostWeights.push_back(0.00550563);
  fForest.push_back( 
NN(
NN(
NN(
NN(
0, 
0, 
-1, 0, 1, 1, 0.565598,-99) , 
NN(
0, 
0, 
-1, 0, 1, -1, 0.449852,-99) , 
11, 1.1853, 0, 0, 0.550092,-99) , 
NN(
NN(
0, 
0, 
-1, 0, 1, 1, 0.51694,-99) , 
NN(
0, 
0, 
-1, 0, 1, -1, 0.474858,-99) , 
5, 2.11157, 1, 0, 0.493871,-99) , 
5, 2.57844, 0, 0, 0.505436,-99) , 
NN(
0, 
0, 
-1, 0, 1, -1, 0.399471,-99) , 
0, 274.03, 1, 0, 0.502691,-99)    );
  // itree = 139
  fBoostWeights.push_back(0.00913359);
  fForest.push_back( 
NN(
NN(
NN(
0, 
0, 
-1, 4.09804, 1, 1, 0.612574,-99) , 
NN(
NN(
0, 
0, 
-1, 0, 1, 1, 0.5586,-99) , 
NN(
0, 
0, 
-1, 0, 1, -1, 0.348956,-99) , 
13, 5.11765, 0, 0, 0.465821,-99) , 
6, 607.722, 1, 0, 0.559486,-99) , 
NN(
NN(
0, 
0, 
-1, 0.440861, 1, 1, 0.519307,-99) , 
NN(
0, 
0, 
-1, 1.13747, 1, -1, 0.462639,-99) , 
9, 2.80756, 1, 0, 0.501409,-99) , 
1, 3.09959, 0, 0, 0.511889,-99)    );
  // itree = 140
  fBoostWeights.push_back(0.0224886);
  fForest.push_back( 
NN(
NN(
NN(
0, 
0, 
-1, 4.05882, 1, 1, 0.649535,-99) , 
NN(
NN(
0, 
0, 
-1, 0, 1, 1, 0.591918,-99) , 
NN(
0, 
0, 
-1, 0, 1, -1, 0.4493,-99) , 
3, 392.244, 0, 0, 0.490269,-99) , 
2, 93.1321, 1, 0, 0.551976,-99) , 
NN(
NN(
NN(
0, 
0, 
-1, 0, 1, 1, 0.538607,-99) , 
NN(
0, 
0, 
-1, 0, 1, -1, 0.483195,-99) , 
0, 105.816, 0, 0, 0.502566,-99) , 
NN(
0, 
0, 
-1, 0, 1, -1, 0.380755,-99) , 
2, 398.812, 1, 0, 0.498574,-99) , 
1, 3.02232, 0, 0, 0.509646,-99)    );
  // itree = 141
  fBoostWeights.push_back(0);
  fForest.push_back( 
NN(
NN(
NN(
0, 
0, 
-1, 0, 1, 1, 0.631045,-99) , 
NN(
NN(
0, 
0, 
-1, 0, 1, 1, 0.562194,-99) , 
NN(
0, 
0, 
-1, 0, 1, -1, 0.497736,-99) , 
14, 128, 0, 0, 0.504054,-99) , 
10, 0.532018, 1, 0, 0.509384,-99) , 
NN(
0, 
0, 
-1, 2.38084, 0, -1, 0.416888,-99) , 
0, 210.48, 1, 0, 0.504067,-99)    );
  // itree = 142
  fBoostWeights.push_back(0.0204405);
  fForest.push_back( 
NN(
NN(
NN(
0, 
0, 
-1, 45.6617, 1, 1, 0.517922,-99) , 
NN(
0, 
0, 
-1, 0, 1, -1, 0.361925,-99) , 
1, 3.5217, 1, 0, 0.513212,-99) , 
NN(
0, 
0, 
-1, 5.15686, 0, -1, 0.421659,-99) , 
11, 3.31757, 1, 0, 0.506485,-99)    );
  // itree = 143
  fBoostWeights.push_back(0.0113288);
  fForest.push_back( 
NN(
NN(
NN(
0, 
0, 
-1, 19.3662, 1, 1, 0.528336,-99) , 
NN(
NN(
0, 
0, 
-1, 0, 1, 1, 0.525446,-99) , 
NN(
0, 
0, 
-1, 0, 1, -1, 0.438378,-99) , 
9, 2.4622, 1, 0, 0.47581,-99) , 
6, 862.138, 1, 0, 0.521718,-99) , 
NN(
NN(
NN(
0, 
0, 
-1, 0, 1, 1, 0.569656,-99) , 
NN(
0, 
0, 
-1, 0, 1, -1, 0.43211,-99) , 
3, 316.214, 0, 0, 0.489704,-99) , 
NN(
0, 
0, 
-1, 0, 1, -1, 0.37378,-99) , 
6, 593.96, 0, 0, 0.443986,-99) , 
1, 1.10404, 0, 0, 0.511334,-99)    );
  // itree = 144
  fBoostWeights.push_back(0.0109401);
  fForest.push_back( 
NN(
NN(
NN(
NN(
0, 
0, 
-1, 0, 1, 1, 0.532692,-99) , 
NN(
0, 
0, 
-1, 0, 1, -1, 0.493459,-99) , 
11, 2.29414, 1, 0, 0.514217,-99) , 
NN(
0, 
0, 
-1, 234.547, 0, -1, 0.422063,-99) , 
9, 3.49566, 1, 0, 0.508372,-99) , 
NN(
0, 
0, 
-1, 0, 1, -1, 0.378218,-99) , 
7, 0.251643, 0, 0, 0.500294,-99)    );
  // itree = 145
  fBoostWeights.push_back(0.013336);
  fForest.push_back( 
NN(
NN(
NN(
0, 
0, 
-1, 0, 1, 1, 0.647431,-99) , 
NN(
NN(
0, 
0, 
-1, 0, 1, 1, 0.586942,-99) , 
NN(
0, 
0, 
-1, 0, 1, -1, 0.437174,-99) , 
11, 2.0935, 1, 0, 0.512518,-99) , 
13, 4.07843, 1, 0, 0.567633,-99) , 
NN(
NN(
0, 
0, 
-1, 0, 1, 1, 0.57969,-99) , 
NN(
NN(
0, 
0, 
-1, 0, 1, 1, 0.507549,-99) , 
NN(
0, 
0, 
-1, 0, 1, -1, 0.462618,-99) , 
1, 2.74695, 1, 0, 0.493936,-99) , 
13, 7.11765, 0, 0, 0.500194,-99) , 
10, 3.17678, 0, 0, 0.50801,-99)    );
  // itree = 146
  fBoostWeights.push_back(0.0150608);
  fForest.push_back( 
NN(
NN(
NN(
0, 
0, 
-1, 2.93087, 0, 1, 0.523537,-99) , 
NN(
0, 
0, 
-1, 1017.87, 1, -1, 0.485305,-99) , 
1, 2.26955, 0, 0, 0.505359,-99) , 
NN(
NN(
NN(
0, 
0, 
-1, 0, 1, 1, 0.583623,-99) , 
NN(
0, 
0, 
-1, 0, 1, -1, 0.459354,-99) , 
1, 3.12666, 0, 0, 0.500288,-99) , 
NN(
0, 
0, 
-1, 226.083, 1, -1, 0.376826,-99) , 
13, 4.17647, 0, 0, 0.455227,-99) , 
9, 3.17993, 1, 0, 0.49732,-99)    );
  // itree = 147
  fBoostWeights.push_back(0.034489);
  fForest.push_back( 
NN(
NN(
NN(
0, 
0, 
-1, 0.40246, 1, 1, 0.585735,-99) , 
NN(
NN(
0, 
0, 
-1, 0, 1, 1, 0.548205,-99) , 
NN(
0, 
0, 
-1, 0, 1, -1, 0.383152,-99) , 
9, 2.69709, 0, 0, 0.482554,-99) , 
4, 295.491, 1, 0, 0.540135,-99) , 
NN(
NN(
NN(
0, 
0, 
-1, 0, 1, 1, 0.554642,-99) , 
NN(
0, 
0, 
-1, 0, 1, -1, 0.470831,-99) , 
4, 207.18, 0, 0, 0.516293,-99) , 
NN(
0, 
0, 
-1, 583.014, 0, -1, 0.465881,-99) , 
13, 4.17647, 1, 0, 0.486976,-99) , 
7, 0.640959, 1, 0, 0.498952,-99)    );
  // itree = 148
  fBoostWeights.push_back(0.0142566);
  fForest.push_back( 
NN(
NN(
NN(
0, 
0, 
-1, 1.86344, 0, 1, 0.525586,-99) , 
NN(
0, 
0, 
-1, 2.09595, 0, -1, 0.458215,-99) , 
11, 1.32713, 0, 0, 0.512951,-99) , 
NN(
0, 
0, 
-1, 0, 1, -1, 0.35497,-99) , 
9, 0.544378, 0, 0, 0.508454,-99)    );
  // itree = 149
  fBoostWeights.push_back(0.00161719);
  fForest.push_back( 
NN(
NN(
NN(
NN(
0, 
0, 
-1, 0, 1, 1, 0.650264,-99) , 
NN(
0, 
0, 
-1, 0, 1, -1, 0.499116,-99) , 
13, 5.11765, 1, 0, 0.568256,-99) , 
NN(
0, 
0, 
-1, 184.804, 1, -1, 0.494223,-99) , 
4, 580.331, 0, 0, 0.500608,-99) , 
NN(
0, 
0, 
-1, 0, 1, -1, 0.391769,-99) , 
7, 0.251288, 0, 0, 0.494182,-99)    );
   return;
};
 
// Clean up
inline void ReadBDT::Clear() 
{
   for (unsigned int itree=0; itree<fForest.size(); itree++) { 
      delete fForest[itree]; 
   }
}
   inline double ReadBDT::GetMvaValue( const std::vector<double>& inputValues ) const
   {
      // classifier response value
      double retval = 0;

      // classifier response, sanity check first
      if (!IsStatusClean()) {
         std::cout << "Problem in class \"" << fClassName << "\": cannot return classifier response"
                   << " because status is dirty" << std::endl;
         retval = 0;
      }
      else {
         if (IsNormalised()) {
            // normalise variables
            std::vector<double> iV;
            iV.reserve(inputValues.size());
            int ivar = 0;
            for (std::vector<double>::const_iterator varIt = inputValues.begin();
                 varIt != inputValues.end(); varIt++, ivar++) {
               iV.push_back(NormVariable( *varIt, fVmin[ivar], fVmax[ivar] ));
            }
            retval = GetMvaValue__( iV );
         }
         else {
            retval = GetMvaValue__( inputValues );
         }
      }

      return retval;
   }
